-- Category descriptions + tutor/jobs/souq model name translations.

ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS description_ar TEXT,
  ADD COLUMN IF NOT EXISTS description_en TEXT,
  ADD COLUMN IF NOT EXISTS description_ku TEXT,
  ADD COLUMN IF NOT EXISTS description_tr TEXT;


-- Clear Arabic wrongly copied into name_en for tutor/jobs models
UPDATE public.categories SET name_en = NULL, name_ku = NULL, name_tr = NULL
WHERE icon = 'model' AND slug ~ '^(tutor_|jobs_)'
  AND name_en ~ '[\u0600-\u06FF]';
UPDATE public.categories SET description_ar = 'موبايلات ، كمبيوتر ، ملابس ، أثاث', description_en = 'Mobiles, Computers, Clothing, Furniture', description_ku = 'مۆبایل، کۆمپیوتەر، جلوبەرگ، کەلوپەل', description_tr = 'Telefonlar, Bilgisayarlar, Giyim, Mobilya' WHERE slug = 'buy_sell';
UPDATE public.categories SET description_ar = 'سيارات ، SUV ، دراجات ، تجارية', description_en = 'Cars, SUV, Motorcycles, Commercial', description_ku = 'ئۆتۆمبێل، SUV، مۆتۆرسikl، بازرگانی', description_tr = 'Arabalar, SUV, Motosikletler, Ticari' WHERE slug = 'cars';
UPDATE public.categories SET description_ar = 'Apple, Samsung, Huawei, Xiaomi', description_en = 'Apple, Samsung, Huawei, Xiaomi', description_ku = 'Apple, Samsung, Huawei, Xiaomi', description_tr = 'Apple, Samsung, Huawei, Xiaomi' WHERE slug = 'elec_smartphones';
UPDATE public.categories SET description_ar = 'هواتف ذكية ، أجهزة لوحية ، لابتوب وكمبيوتر ، مكيفات', description_en = 'Smartphones, Tablets, Laptops, AC', description_ku = 'مۆبایل، تابلێت، laptop، کۆndیشن', description_tr = 'Akıllı Telefonlar, Tabletler, Laptoplar, Klima' WHERE slug = 'electronics';
UPDATE public.categories SET description_ar = 'تنظيف ، طبخ ، مربيات ، سائق', description_en = 'Cleaning, Cooking, Childcare, Driver', description_ku = 'pak، xwarin، mamani', description_tr = 'Temizlik, Yemek, Bakıcı, Şoför' WHERE slug = 'home_help';
UPDATE public.categories SET description_ar = 'تقنية ، هندسة ، طب ، نفط', description_en = 'IT, Engineering, Medicine, Oil & Energy', description_ku = 'IT، ئەndازیari، پzیشki، neft', description_tr = 'BT, Mühendislik, Tıp, Petrol' WHERE slug = 'jobs';
UPDATE public.categories SET description_ar = 'محاسب ، مدير مالي ، موارد بشرية ، مبيعات', description_en = 'Accountant, Finance Manager, HR, Sales', description_ku = 'ژmێriar، بەڕێwەbەri darayi', description_tr = 'Muhasebeci, Finans Müdürü, İK, Satış' WHERE slug = 'jobs_business';
UPDATE public.categories SET description_ar = 'معلم ، أستاذ جامعي ، مدرب ، مدرس إنجليزي', description_en = 'Teacher, Professor, Trainer, English Teacher', description_ku = 'mamoستa، professor، rahêner', description_tr = 'Öğretmen, Profesör, Eğitmen, İngilizce Öğretmeni' WHERE slug = 'jobs_education';
UPDATE public.categories SET description_ar = 'مدني ، معماري ، كهربائي ، ميكانيكي', description_en = 'Civil, Architect, Electrical, Mechanical', description_ku = 'شارستانی، تەلarsazi، کارەba، mekanik', description_tr = 'İnşaat, Mimar, Elektrik, Makine' WHERE slug = 'jobs_engineering';
UPDATE public.categories SET description_ar = 'فريلانسر ، عمل من المنزل ، دوام جزئي', description_en = 'Freelance, Work from Home, Part-time', description_ku = 'freelance، kar li mal', description_tr = 'Serbest, Evden Çalışma, Yarı Zamanlı' WHERE slug = 'jobs_freelance';
UPDATE public.categories SET description_ar = 'طاهي ، نادل ، استقبال ، مرشد سياحي', description_en = 'Chef, Waiter, Reception, Tour Guide', description_ku = 'aşpز، garson، pêşwazî', description_tr = 'Aşçı, Garson, Resepsiyon, Rehber' WHERE slug = 'jobs_hospitality';
UPDATE public.categories SET description_ar = 'مطور موبايل ، مطور ويب ، باك إند ، فرونت إند', description_en = 'Mobile Dev, Web Dev, Backend, Frontend', description_ku = 'گەشەپێدەری مۆبایل، وێب، باك ئێند، فرۆنت ئێند', description_tr = 'Mobil, Web, Backend, Frontend' WHERE slug = 'jobs_it';
UPDATE public.categories SET description_ar = 'جرافيك ، تصوير ، مونتاج ، صحافة', description_en = 'Graphic Design, Photography, Editing, Journalism', description_ku = 'grafik، wêne، montaj', description_tr = 'Grafik, Fotoğraf, Kurgu, Gazetecilik' WHERE slug = 'jobs_media';
UPDATE public.categories SET description_ar = 'طبيب ، صيدلاني ، ممرض ، معالج فيزيائي', description_en = 'Doctor, Pharmacist, Nurse, Physiotherapist', description_ku = 'pزیشk، dەرmanسaz، pەرstار', description_tr = 'Doktor, Eczacı, Hemşire, Fizyoterapist' WHERE slug = 'jobs_medical';
UPDATE public.categories SET description_ar = 'حفر ، جيولوجي ، فني نفط ، طاقة شمسية', description_en = 'Drilling, Geologist, Oil Tech, Solar', description_ku = 'kon، jeoloj، tekniker neft', description_tr = 'Sondaj, Jeolog, Petrol Teknisyeni, Güneş' WHERE slug = 'jobs_oil_energy';
UPDATE public.categories SET description_ar = 'ميكانيكي ، نجار ، سباك ، كهربائي', description_en = 'Mechanic, Carpenter, Plumber, Electrician', description_ku = 'mekanik، necar، borîçî', description_tr = 'Tamirci, Marangoz, Tesisatçı, Elektrikçi' WHERE slug = 'jobs_trades';
UPDATE public.categories SET description_ar = 'كلاب ، قطط ، طيور ، مزرعة', description_en = 'Dogs, Cats, Birds, Farm Animals', description_ku = 'sag، pisîl، balinde', description_tr = 'Köpekler, Kediler, Kuşlar, Çiftlik' WHERE slug = 'pets';
UPDATE public.categories SET description_ar = 'سكني ، سياحي ، مشاريع ، أراضي', description_en = 'Residential, Tourism, Projects, Land', description_ku = 'نیشتەجێبوون، گەشتیاری، پڕۆژە، زەوی', description_tr = 'Konut, Turizm, Projeler, Arsa' WHERE slug = 'real_estate';
UPDATE public.categories SET description_ar = 'لابتوب ، ماك ، كمبيوتر مكتبي ، شاشات', description_en = 'Laptops, Mac, Desktop, Monitors', description_ku = 'laptop، mac، desktop', description_tr = 'Laptop, Mac, Masaüstü, Monitörler' WHERE slug = 'souq_computer';
UPDATE public.categories SET description_ar = 'رجالي ، نسائي ، أطفال ، أحذية', description_en = 'Men, Women, Kids, Shoes', description_ku = 'pîyan، jinan، zarok', description_tr = 'Erkek, Kadın, Çocuk, Ayakkabı' WHERE slug = 'souq_fashion';
UPDATE public.categories SET description_ar = 'غرف نوم ، صالون ، مطبخ ، مكتب', description_en = 'Bedroom, Living Room, Kitchen, Office', description_ku = 'jûr، salon، metbex', description_tr = 'Yatak Odası, Salon, Mutfak, Ofis' WHERE slug = 'souq_furniture';
UPDATE public.categories SET description_ar = 'متنوع ، أدوات ، هدايا ، أخرى', description_en = 'Miscellaneous, Tools, Gifts, Other', description_ku = 'cihêj، amûr، diyari', description_tr = 'Çeşitli, Araçlar, Hediyeler, Diğer' WHERE slug = 'souq_misc';
UPDATE public.categories SET description_ar = 'هواتف ذكية ، آيفون ، سامسونج ، هواوي', description_en = 'Smartphones, iPhone, Samsung, Huawei', description_ku = 'smartphone، iphone، samsung', description_tr = 'Akıllı Telefonlar, iPhone, Samsung, Huawei' WHERE slug = 'souq_mobile';
UPDATE public.categories SET description_ar = 'كرة قدم ، لياقة ، دراجات ، صيد', description_en = 'Football, Fitness, Bikes, Hunting', description_ku = 'topy، fitness، bisiklet', description_tr = 'Futbol, Fitness, Bisiklet, Av' WHERE slug = 'souq_sports';
UPDATE public.categories SET description_ar = 'الإنجليزية ، العربية للأجانب ، الكردية ، التركية', description_en = 'English, Arabic for Foreigners, Kurdish, Turkish', description_ku = 'ئینگلیزی، عەرەبی بۆ بیانی، کوردی، تورکی', description_tr = 'İngilizce, Yabancılar İçin Arapça, Kürtçe, Türkçe' WHERE slug = 'tutor_languages';
UPDATE public.categories SET description_ar = 'برمجة ، تصميم ، مونتاج ، تسويق', description_en = 'Programming, Design, Video Editing, Marketing', description_ku = 'بەرنامەسازی، دیزایn، مۆنتاج، مارکێتینگ', description_tr = 'Programlama, Tasarım, Video Kurgu, Pazarlama' WHERE slug = 'tutor_professional';
UPDATE public.categories SET description_ar = 'حفظ القرآن ، تجويد ، فقه ، عقيدة', description_en = 'Quran Memorization, Tajweed, Fiqh, Aqeedah', description_ku = 'لەبەرکردنی قورئان، تەجوید، فیقه، عەقیدە', description_tr = 'Kuran Ezberleme, Tecvid, Fıkıh, Akide' WHERE slug = 'tutor_quran';
UPDATE public.categories SET description_ar = 'الرياضيات ، الفيزياء ، الكيمياء ، الأحياء', description_en = 'Mathematics, Physics, Chemistry, Biology', description_ku = 'بیرکاری، فیزیا، کیمیا، زیندەزانی', description_tr = 'Matematik, Fizik, Kimya, Biyoloji' WHERE slug = 'tutor_school';
UPDATE public.categories SET description_ar = 'هندسة البرمجيات ، علوم الحاسوب ، الذكاء الاصطناعي ، الخوارزميات', description_en = 'Software Engineering, Computer Science, AI, Algorithms', description_ku = 'ئەندازیاری نەرمامێر، زanستی کۆمپیوتەر، زیرەکی دەستکرد، ئەلگۆریtm', description_tr = 'Yazılım Mühendisliği, Bilgisayar Bilimleri, Yapay Zeka, Algoritmalar' WHERE slug = 'tutor_university';
UPDATE public.categories SET description_ar = 'مدرسة ، جامعة ، لغات ، قرآن', description_en = 'School, University, Languages, Quran', description_ku = 'قوتابخانە، زانکۆ، زمان، قورئان', description_tr = 'Okul, Üniversite, Diller, Kuran' WHERE slug = 'tutoring';
UPDATE public.categories SET description_ar = 'Toyota, Mercedes-Benz, BMW, Kia', description_en = 'Toyota, Mercedes-Benz, BMW, Kia', description_ku = 'Toyota, Mercedes-Benz, BMW, Kia', description_tr = 'Toyota, Mercedes-Benz, BMW, Kia' WHERE slug = 'veh_accessible';
UPDATE public.categories SET description_ar = 'طائرات ، مروحيات', description_en = 'Planes, Helicopters', description_ku = 'فڕۆkە، هێلیکۆپتەر', description_tr = 'Uçaklar, Helikopterler' WHERE slug = 'veh_aircraft';
UPDATE public.categories SET description_ar = 'Robinson, Bell, Airbus Helicopters, Sikorsky', description_en = 'Robinson, Bell, Airbus Helicopters, Sikorsky', description_ku = 'Robinson, Bell, Airbus Helicopters, Sikorsky', description_tr = 'Robinson, Bell, Airbus Helicopters, Sikorsky' WHERE slug = 'veh_aircraft_helicopters';
UPDATE public.categories SET description_ar = 'Cessna, Piper, Gulfstream, Embraer', description_en = 'Cessna, Piper, Gulfstream, Embraer', description_ku = 'Cessna, Piper, Gulfstream, Embraer', description_tr = 'Cessna, Piper, Gulfstream, Embraer' WHERE slug = 'veh_aircraft_planes';
UPDATE public.categories SET description_ar = 'Coachmen, Airstream, Jayco, Winnebago', description_en = 'Coachmen, Airstream, Jayco, Winnebago', description_ku = 'Coachmen, Airstream, Jayco, Winnebago', description_tr = 'Coachmen, Airstream, Jayco, Winnebago' WHERE slug = 'veh_caravan';
UPDATE public.categories SET description_ar = 'Mercedes-Benz, BMW, Toyota, Ford', description_en = 'Mercedes-Benz, BMW, Toyota, Ford', description_ku = 'Mercedes-Benz, BMW, Toyota, Ford', description_tr = 'Mercedes-Benz, BMW, Toyota, Ford' WHERE slug = 'veh_classic';
UPDATE public.categories SET description_ar = 'Toyota, Hino, Isuzu, IVECO', description_en = 'Toyota, Hino, Isuzu, IVECO', description_ku = 'Toyota, Hino, Isuzu, IVECO', description_tr = 'Toyota, Hino, Isuzu, IVECO' WHERE slug = 'veh_commercial';
UPDATE public.categories SET description_ar = 'Toyota, Mercedes-Benz, BMW, Kia', description_en = 'Toyota, Mercedes-Benz, BMW, Kia', description_ku = 'Toyota, Mercedes-Benz, BMW, Kia', description_tr = 'Toyota, Mercedes-Benz, BMW, Kia' WHERE slug = 'veh_damaged';
UPDATE public.categories SET description_ar = 'Tesla, BMW, Mercedes-Benz, Audi', description_en = 'Tesla, BMW, Mercedes-Benz, Audi', description_ku = 'Tesla, BMW, Mercedes-Benz, Audi', description_tr = 'Tesla, BMW, Mercedes-Benz, Audi' WHERE slug = 'veh_electric';
UPDATE public.categories SET description_ar = 'Yamaha, Sea-Doo, Honda Marine, Mercury', description_en = 'Yamaha, Sea-Doo, Honda Marine, Mercury', description_ku = 'Yamaha, Sea-Doo, Honda Marine, Mercury', description_tr = 'Yamaha, Sea-Doo, Honda Marine, Mercury' WHERE slug = 'veh_marine';
UPDATE public.categories SET description_ar = 'Toyota, Kia, Hyundai, Nissan', description_en = 'Toyota, Kia, Hyundai, Nissan', description_ku = 'Toyota, Kia, Hyundai, Nissan', description_tr = 'Toyota, Kia, Hyundai, Nissan' WHERE slug = 'veh_minivan';
UPDATE public.categories SET description_ar = 'دراجات نارية ، دراجات هوائية ، سكوتر', description_en = 'Motorcycles, Bicycles, Scooters', description_ku = 'مۆتۆرسikl، پاسکیل، سکوoter', description_tr = 'Motosikletler, Bisikletler, Scooter' WHERE slug = 'veh_motorcycle';
UPDATE public.categories SET description_ar = 'Chevrolet, Audi, Tesla, BMW', description_en = 'Chevrolet, Audi, Tesla, BMW', description_ku = 'Chevrolet, Audi, Tesla, BMW', description_tr = 'Chevrolet, Audi, Tesla, BMW' WHERE slug = 'veh_rental';
UPDATE public.categories SET description_ar = 'Toyota, Land Rover, Jeep, Lexus', description_en = 'Toyota, Land Rover, Jeep, Lexus', description_ku = 'Toyota, Land Rover, Jeep, Lexus', description_tr = 'Toyota, Land Rover, Jeep, Lexus' WHERE slug = 'veh_suv_pickup';

-- Tutor subject names
UPDATE public.categories SET name_en = 'Aqeedah & Tafsir', name_ku = 'عەقیدە و تفسیر', name_tr = 'Akide ve Tefsir' WHERE slug = 'tutor_islamic_aqeedah';
UPDATE public.categories SET name_en = 'Islamic Arabic', name_ku = 'عەرەبی شەرعی', name_tr = 'İslami Arapça' WHERE slug = 'tutor_islamic_arabic';
UPDATE public.categories SET name_en = 'Islamic Jurisprudence', name_ku = 'فیقهی ئیسلامی', name_tr = 'İslam Hukuku' WHERE slug = 'tutor_islamic_fiqh';
UPDATE public.categories SET name_en = 'Arabic for Foreigners', name_ku = 'عەرەبی بۆ بیانییەکان', name_tr = 'Yabancılar İçin Arapça' WHERE slug = 'tutor_lang_arabic_foreign';
UPDATE public.categories SET name_en = 'Chinese Language', name_ku = 'زمانی چینی', name_tr = 'Çince' WHERE slug = 'tutor_lang_chinese';
UPDATE public.categories SET name_en = 'English Language', name_ku = 'زمانی ئینگلیزی', name_tr = 'İngilizce' WHERE slug = 'tutor_lang_english';
UPDATE public.categories SET name_en = 'French Language', name_ku = 'زمانی فەڕەنسی', name_tr = 'Fransızca' WHERE slug = 'tutor_lang_french';
UPDATE public.categories SET name_en = 'German Language', name_ku = 'زمانی ئەڵمانی', name_tr = 'Almanca' WHERE slug = 'tutor_lang_german';
UPDATE public.categories SET name_en = 'IELTS / TOEFL Prep', name_ku = 'ئامادەکاری IELTS / TOEFL', name_tr = 'IELTS / TOEFL Hazırlık' WHERE slug = 'tutor_lang_ielts';
UPDATE public.categories SET name_en = 'Korean Language', name_ku = 'زمانی کۆری', name_tr = 'Korece' WHERE slug = 'tutor_lang_korean';
UPDATE public.categories SET name_en = 'Kurdish Language', name_ku = 'زمانی کوردی', name_tr = 'Kürtçe' WHERE slug = 'tutor_lang_kurdish';
UPDATE public.categories SET name_en = 'Persian Language', name_ku = 'زمانی فارسی', name_tr = 'Farsça' WHERE slug = 'tutor_lang_persian';
UPDATE public.categories SET name_en = 'Russian Language', name_ku = 'زمانی ڕووسی', name_tr = 'Rusça' WHERE slug = 'tutor_lang_russian';
UPDATE public.categories SET name_en = 'Turkish Language', name_ku = 'زمانی تورکی', name_tr = 'Türkçe' WHERE slug = 'tutor_lang_turkish';
UPDATE public.categories SET name_en = 'Accounting & Finance Software', name_ku = 'ژمێریاری و نەرمامێری دارایی', name_tr = 'Muhasebe ve Finans Yazılımı' WHERE slug = 'tutor_prof_accounting_sw';
UPDATE public.categories SET name_en = 'AI & Machine Learning', name_ku = 'زیرەکی دەستکرد و فێربوونی ئامێر', name_tr = 'Yapay Zeka ve Makine Öğrenimi' WHERE slug = 'tutor_prof_ai_ml';
UPDATE public.categories SET name_en = 'Cybersecurity', name_ku = 'ئاسایشی سایبری', name_tr = 'Siber Güvenlik' WHERE slug = 'tutor_prof_cybersecurity';
UPDATE public.categories SET name_en = 'Entrepreneurship', name_ku = 'کارگێڕی', name_tr = 'Girişimcilik' WHERE slug = 'tutor_prof_entrepreneurship';
UPDATE public.categories SET name_en = 'Graphic Design', name_ku = 'دیزاینی گرافیک', name_tr = 'Grafik Tasarım' WHERE slug = 'tutor_prof_graphic_design';
UPDATE public.categories SET name_en = 'Digital Marketing', name_ku = 'مارکێتینگی دیجیتاڵ', name_tr = 'Dijital Pazarlama' WHERE slug = 'tutor_prof_marketing';
UPDATE public.categories SET name_en = 'Office Skills (Word/Excel)', name_ku = 'لێهاتوویی ئۆفیس (Word/Excel)', name_tr = 'Ofis Becerileri (Word/Excel)' WHERE slug = 'tutor_prof_office';
UPDATE public.categories SET name_en = 'Programming & App Development', name_ku = 'بەرنامەسازی و گەشەپێدانی ئەپ', name_tr = 'Programlama ve Uygulama Geliştirme' WHERE slug = 'tutor_prof_programming';
UPDATE public.categories SET name_en = 'Project Management', name_ku = 'بەڕێوەبردنی پڕۆژە', name_tr = 'Proje Yönetimi' WHERE slug = 'tutor_prof_project_mgmt';
UPDATE public.categories SET name_en = 'Video Editing & Production', name_ku = 'مۆنتاج و بەرهەمهێنانی ڤیدیۆ', name_tr = 'Video Kurgu ve Prodüksiyon' WHERE slug = 'tutor_prof_video';
UPDATE public.categories SET name_en = 'Quran Memorization', name_ku = 'لەبەرکردنی قورئان', name_tr = 'Kuran Ezberleme' WHERE slug = 'tutor_quran_memorization';
UPDATE public.categories SET name_en = 'Quran Tajweed', name_ku = 'تەجویدی قورئان', name_tr = 'Kuran Tecvid' WHERE slug = 'tutor_quran_tajweed';
UPDATE public.categories SET name_en = 'Arabic Language', name_ku = 'زمانی عەرەبی', name_tr = 'Arapça' WHERE slug = 'tutor_school_arabic';
UPDATE public.categories SET name_en = 'Biology', name_ku = 'زیندەزانی', name_tr = 'Biyoloji' WHERE slug = 'tutor_school_biology';
UPDATE public.categories SET name_en = 'Chemistry', name_ku = 'کیمیا', name_tr = 'Kimya' WHERE slug = 'tutor_school_chemistry';
UPDATE public.categories SET name_en = 'Civics', name_ku = 'پەروەردەی نیشتمانی', name_tr = 'Vatandaşlık' WHERE slug = 'tutor_school_civic';
UPDATE public.categories SET name_en = 'Computer & Technology', name_ku = 'کۆمپیوتەر و تەکنەلۆژیا', name_tr = 'Bilgisayar ve Teknoloji' WHERE slug = 'tutor_school_computer';
UPDATE public.categories SET name_en = 'English Language', name_ku = 'زمانی ئینگلیزی', name_tr = 'İngilizce' WHERE slug = 'tutor_school_english';
UPDATE public.categories SET name_en = 'Grade 12 Literary', name_ku = 'پۆلی شەشەمی ئامادەیی (وێژەیی)', name_tr = '12. Sınıf Sözel' WHERE slug = 'tutor_school_grade12_art';
UPDATE public.categories SET name_en = 'Grade 12 Scientific', name_ku = 'پۆلی شەشەمی ئامادەیی (زانستی)', name_tr = '12. Sınıf Fen' WHERE slug = 'tutor_school_grade12_sci';
UPDATE public.categories SET name_en = 'Grade 6 Primary', name_ku = 'پۆلی شەشەمی سەرەتایی', name_tr = '6. Sınıf İlkokul' WHERE slug = 'tutor_school_grade6';
UPDATE public.categories SET name_en = 'Grade 9 Intermediate', name_ku = 'پۆلی سێیەمی ناوەند', name_tr = '9. Sınıf Ortaokul' WHERE slug = 'tutor_school_grade9';
UPDATE public.categories SET name_en = 'History & Geography', name_ku = 'مێژوو و جوgrafiya', name_tr = 'Tarih ve Coğrafya' WHERE slug = 'tutor_school_history_geo';
UPDATE public.categories SET name_en = 'Islamic Education', name_ku = 'پەروەردەی ئیسلامی', name_tr = 'İslam Eğitimi' WHERE slug = 'tutor_school_islamic';
UPDATE public.categories SET name_en = 'Mathematics', name_ku = 'بیرکاری', name_tr = 'Matematik' WHERE slug = 'tutor_school_math';
UPDATE public.categories SET name_en = 'Physics', name_ku = 'فیزیا', name_tr = 'Fizik' WHERE slug = 'tutor_school_physics';
UPDATE public.categories SET name_en = 'General Science', name_ku = 'زانستی گشتی', name_tr = 'Genel Fen' WHERE slug = 'tutor_school_science';
UPDATE public.categories SET name_en = 'Accounting & Management', name_ku = 'ژمێریاری و بەڕێوەبردن', name_tr = 'Muhasebe ve Yönetim' WHERE slug = 'tutor_uni_accounting';
UPDATE public.categories SET name_en = 'Agriculture & Environment', name_ku = 'کشتوکاڵ و ژینگە', name_tr = 'Tarım ve Çevre' WHERE slug = 'tutor_uni_agriculture';
UPDATE public.categories SET name_en = 'Artificial Intelligence', name_ku = 'زیرەکی دەستکرد', name_tr = 'Yapay Zeka' WHERE slug = 'tutor_uni_ai';
UPDATE public.categories SET name_en = 'Algorithms & Data Structures', name_ku = 'ئەلگۆریتم و پێکهاتەی داتا', name_tr = 'Algoritmalar ve Veri Yapıları' WHERE slug = 'tutor_uni_algorithms';
UPDATE public.categories SET name_en = 'Arabic Language & Literature', name_ku = 'زمانی عەرەبی و ئەدەبیات', name_tr = 'Arap Dili ve Edebiyatı' WHERE slug = 'tutor_uni_arabic_lit';
UPDATE public.categories SET name_en = 'Architecture', name_ku = 'ئەندازیاری تەلارسازی', name_tr = 'Mimarlık' WHERE slug = 'tutor_uni_architecture';
UPDATE public.categories SET name_en = 'University Chemistry', name_ku = 'کیمیای زانکۆ', name_tr = 'Üniversite Kimyası' WHERE slug = 'tutor_uni_chemistry';
UPDATE public.categories SET name_en = 'Civil Engineering', name_ku = 'ئەندازیاری شارستانی', name_tr = 'İnşaat Mühendisliği' WHERE slug = 'tutor_uni_civil_eng';
UPDATE public.categories SET name_en = 'Computer Science', name_ku = 'زانستی کۆمپیوتەر', name_tr = 'Bilgisayar Bilimleri' WHERE slug = 'tutor_uni_cs';
UPDATE public.categories SET name_en = 'Databases', name_ku = 'بنکەی زانیاری', name_tr = 'Veritabanları' WHERE slug = 'tutor_uni_databases';
UPDATE public.categories SET name_en = 'Economics & Banking', name_ku = 'ئابووری و بانک', name_tr = 'Ekonomi ve Bankacılık' WHERE slug = 'tutor_uni_economics';
UPDATE public.categories SET name_en = 'Education & Psychology', name_ku = 'پەروەردە و دەروونناسی', name_tr = 'Eğitim ve Psikoloji' WHERE slug = 'tutor_uni_education';
UPDATE public.categories SET name_en = 'Electrical Engineering', name_ku = 'ئەندازیاری کارەبا', name_tr = 'Elektrik Mühendisliği' WHERE slug = 'tutor_uni_electrical_eng';
UPDATE public.categories SET name_en = 'English Language & Literature', name_ku = 'زمانی ئینگلیزی و ئەدەبیات', name_tr = 'İngiliz Dili ve Edebiyatı' WHERE slug = 'tutor_uni_english_lit';
UPDATE public.categories SET name_en = 'Law', name_ku = 'یاسا', name_tr = 'Hukuk' WHERE slug = 'tutor_uni_law';
UPDATE public.categories SET name_en = 'Applied Mathematics', name_ku = 'بیرکاری کاربردی', name_tr = 'Uygulamalı Matematik' WHERE slug = 'tutor_uni_math';
UPDATE public.categories SET name_en = 'Mechanical Engineering', name_ku = 'ئەندازیاری میکانیک', name_tr = 'Makine Mühendisliği' WHERE slug = 'tutor_uni_mechanical_eng';
UPDATE public.categories SET name_en = 'Media & Journalism', name_ku = 'میدیا و ڕۆژنامەگەری', name_tr = 'Medya ve Gazetecilik' WHERE slug = 'tutor_uni_media';
UPDATE public.categories SET name_en = 'Medicine & Pharmacy', name_ku = 'پزیشکی و دەرمانسازی', name_tr = 'Tıp ve Eczacılık' WHERE slug = 'tutor_uni_medicine';
UPDATE public.categories SET name_en = 'Computer Networks', name_ku = 'تۆڕەکانی کۆمپیوتەر', name_tr = 'Bilgisayar Ağları' WHERE slug = 'tutor_uni_networks';
UPDATE public.categories SET name_en = 'Nursing & Health Sciences', name_ku = 'پەرستاری و زانستی تەندروستی', name_tr = 'Hemşirelik ve Sağlık Bilimleri' WHERE slug = 'tutor_uni_nursing';
UPDATE public.categories SET name_en = 'University Physics', name_ku = 'فیزیاکانی زانکۆ', name_tr = 'Üniversite Fiziği' WHERE slug = 'tutor_uni_physics';
UPDATE public.categories SET name_en = 'Software Engineering', name_ku = 'ئەندازیاری نەرمامێر', name_tr = 'Yazılım Mühendisliği' WHERE slug = 'tutor_uni_software_eng';

-- Jobs role names
UPDATE public.categories SET name_en = 'Accountant & Auditor', name_ku = 'ژمێریار و پشکن', name_tr = 'Muhasebeci ve Denetçi' WHERE slug = 'jobs_bus_accountant';
UPDATE public.categories SET name_en = 'Customer Service', name_ku = 'خزمەتگوزاری کڕیار', name_tr = 'Müşteri Hizmetleri' WHERE slug = 'jobs_bus_customer_service';
UPDATE public.categories SET name_en = 'Finance Manager', name_ku = 'بەڕێوەبەری دارایی', name_tr = 'Finans Müdürü' WHERE slug = 'jobs_bus_finance_manager';
UPDATE public.categories SET name_en = 'Human Resources', name_ku = 'سەرچاوەی مرۆیی', name_tr = 'İnsan Kaynakları' WHERE slug = 'jobs_bus_hr';
UPDATE public.categories SET name_en = 'Legal Consultant & Lawyer', name_ku = 'ڕاوێژکاری یاسایی', name_tr = 'Avukat ve Hukuk Danışmanı' WHERE slug = 'jobs_bus_lawyer';
UPDATE public.categories SET name_en = 'Project Manager', name_ku = 'بەڕێوەبەری پڕۆژە', name_tr = 'Proje Müdürü' WHERE slug = 'jobs_bus_project_manager';
UPDATE public.categories SET name_en = 'Real Estate Agent', name_ku = 'بریکاری خانوبەرە', name_tr = 'Emlak Danışmanı' WHERE slug = 'jobs_bus_real_estate_agent';
UPDATE public.categories SET name_en = 'Sales & Marketing Manager', name_ku = 'بەڕێوەبەری فرۆشتن و مارکێتینگ', name_tr = 'Satış ve Pazarlama Müdürü' WHERE slug = 'jobs_bus_sales_marketing';
UPDATE public.categories SET name_en = 'Sales Representative', name_ku = 'نوێنەری فرۆشتن', name_tr = 'Satış Temsilcisi' WHERE slug = 'jobs_bus_sales_rep';
UPDATE public.categories SET name_en = 'Secretary & Administrator', name_ku = 'سekreter و بەڕێوەبەر', name_tr = 'Sekreter ve Yönetici' WHERE slug = 'jobs_bus_secretary';
UPDATE public.categories SET name_en = 'English Teacher', name_ku = 'مامۆستای ئینگلیزی', name_tr = 'İngilizce Öğretmeni' WHERE slug = 'jobs_edu_english_teacher';
UPDATE public.categories SET name_en = 'Nanny & Childcare', name_ku = 'مامانی منداڵ', name_tr = 'Çocuk Bakıcısı' WHERE slug = 'jobs_edu_nanny_teacher';
UPDATE public.categories SET name_en = 'School Teacher', name_ku = 'مامۆستای قوتابخانە', name_tr = 'Okul Öğretmeni' WHERE slug = 'jobs_edu_school_teacher';
UPDATE public.categories SET name_en = 'Education Supervisor', name_ku = 'سەرپەرشتیاری پەروەردەیی', name_tr = 'Eğitim Denetmeni' WHERE slug = 'jobs_edu_supervisor';
UPDATE public.categories SET name_en = 'Professional Trainer', name_ku = 'ڕاهێنەری پیشەیی', name_tr = 'Mesleki Eğitmen' WHERE slug = 'jobs_edu_trainer';
UPDATE public.categories SET name_en = 'University Professor', name_ku = 'پrofessorی زانکۆ', name_tr = 'Üniversite Profesörü' WHERE slug = 'jobs_edu_university_prof';
UPDATE public.categories SET name_en = 'Architect', name_ku = 'ئەندازیاری تەلارسازی', name_tr = 'Mimar' WHERE slug = 'jobs_eng_architect';
UPDATE public.categories SET name_en = 'Civil Engineer', name_ku = 'ئەندازیاری شارستانی', name_tr = 'İnşaat Mühendisi' WHERE slug = 'jobs_eng_civil';
UPDATE public.categories SET name_en = 'Construction Worker', name_ku = 'کرێکاری بیناسازی', name_tr = 'İnşaat İşçisi' WHERE slug = 'jobs_eng_construction_worker';
UPDATE public.categories SET name_en = 'Electrical Engineer', name_ku = 'ئەندازیاری کارەبا', name_tr = 'Elektrik Mühendisi' WHERE slug = 'jobs_eng_electrical';
UPDATE public.categories SET name_en = 'Electrician & Plumber', name_ku = 'کارەباچی و بۆریچی', name_tr = 'Elektrikçi ve Tesisatçı' WHERE slug = 'jobs_eng_electrician_plumber';
UPDATE public.categories SET name_en = 'Environmental Engineer', name_ku = 'ئەندازیاری ژینگە', name_tr = 'Çevre Mühendisi' WHERE slug = 'jobs_eng_environment';
UPDATE public.categories SET name_en = 'Mechanical Engineer', name_ku = 'ئەندازیاری میکانیک', name_tr = 'Makine Mühendisi' WHERE slug = 'jobs_eng_mechanical';
UPDATE public.categories SET name_en = 'Petroleum Engineer', name_ku = 'ئەندازیاری نەوت', name_tr = 'Petrol Mühendisi' WHERE slug = 'jobs_eng_petroleum';
UPDATE public.categories SET name_en = 'Site Supervisor', name_ku = 'سەرپەرشتیاری شوێن', name_tr = 'Saha Sorumlusu' WHERE slug = 'jobs_eng_site_supervisor';
UPDATE public.categories SET name_en = 'Surveyor & Planner', name_ku = 'پێوان و پلاندانەر', name_tr = 'Harita Mühendisi' WHERE slug = 'jobs_eng_surveyor';
UPDATE public.categories SET name_en = 'Freelance Design', name_ku = 'فریلانسەری دیزاین', name_tr = 'Serbest Tasarım' WHERE slug = 'jobs_free_design';
UPDATE public.categories SET name_en = 'Internship & Volunteering', name_ku = 'ڕاهێnan و خۆبەخشی', name_tr = 'Staj ve Gönüllülük' WHERE slug = 'jobs_free_internship';
UPDATE public.categories SET name_en = 'Part-time Work', name_ku = 'کارکردنی بەشەکی', name_tr = 'Yarı Zamanlı' WHERE slug = 'jobs_free_part_time';
UPDATE public.categories SET name_en = 'Freelance Tech', name_ku = 'فریلانسەری تەکنەلۆژیا', name_tr = 'Serbest Teknoloji' WHERE slug = 'jobs_free_tech';
UPDATE public.categories SET name_en = 'Work from Home', name_ku = 'کارکردن لە ماڵەوە', name_tr = 'Evden Çalışma' WHERE slug = 'jobs_free_wfh';
UPDATE public.categories SET name_en = 'Freelance Writing & Translation', name_ku = 'فریلانسەری نووسین و وەرگێڕan', name_tr = 'Serbest Yazarlık ve Çeviri' WHERE slug = 'jobs_free_writing';
UPDATE public.categories SET name_en = 'Chef', name_ku = 'چێشتلێن', name_tr = 'Aşçı' WHERE slug = 'jobs_hosp_chef';
UPDATE public.categories SET name_en = 'Cleaning & Hospitality Staff', name_ku = 'کارمەندی پاککردنەوە', name_tr = 'Temizlik Personeli' WHERE slug = 'jobs_hosp_cleaning';
UPDATE public.categories SET name_en = 'Hotel Receptionist', name_ku = 'کارمەندی پێشوازی هۆtel', name_tr = 'Otel Resepsiyonisti' WHERE slug = 'jobs_hosp_hotel_reception';
UPDATE public.categories SET name_en = 'Restaurant or Hotel Manager', name_ku = 'بەڕێوەبەری چێشتخانە یان هۆtel', name_tr = 'Restoran veya Otel Müdürü' WHERE slug = 'jobs_hosp_manager';
UPDATE public.categories SET name_en = 'Tour Guide', name_ku = 'ڕێبەری گەشتیاری', name_tr = 'Tur Rehberi' WHERE slug = 'jobs_hosp_tour_guide';
UPDATE public.categories SET name_en = 'Waiter', name_ku = 'گارسۆn', name_tr = 'Garson' WHERE slug = 'jobs_hosp_waiter';
UPDATE public.categories SET name_en = 'Backend Engineer', name_ku = 'ئەندازیاری باك ئێند', name_tr = 'Backend Mühendisi' WHERE slug = 'jobs_it_backend';
UPDATE public.categories SET name_en = 'Cybersecurity Specialist', name_ku = 'پسپۆڕی ئاسایشی سایبری', name_tr = 'Siber Güvenlik Uzmanı' WHERE slug = 'jobs_it_cybersecurity';
UPDATE public.categories SET name_en = 'Data Analyst & AI', name_ku = 'شیکردنەوەی داتا و زیرەکی دەستکرد', name_tr = 'Veri Analisti ve Yapay Zeka' WHERE slug = 'jobs_it_data_ai';
UPDATE public.categories SET name_en = 'DevOps & Cloud Engineer', name_ku = 'ئەندازیاری DevOps و Cloud', name_tr = 'DevOps ve Bulut Mühendisi' WHERE slug = 'jobs_it_devops';
UPDATE public.categories SET name_en = 'Frontend Engineer', name_ku = 'ئەندازیاری فرۆنت ئێند', name_tr = 'Frontend Mühendisi' WHERE slug = 'jobs_it_frontend';
UPDATE public.categories SET name_en = 'Mobile App Developer', name_ku = 'گەشەپێدەری ئەپی مۆبایل', name_tr = 'Mobil Uygulama Geliştirici' WHERE slug = 'jobs_it_mobile_dev';
UPDATE public.categories SET name_en = 'Network Engineer', name_ku = 'ئەندازیاری تۆڕ', name_tr = 'Ağ Mühendisi' WHERE slug = 'jobs_it_networks';
UPDATE public.categories SET name_en = 'Technical Support', name_ku = 'پشتگیری تەکنیکی', name_tr = 'Teknik Destek' WHERE slug = 'jobs_it_tech_support';
UPDATE public.categories SET name_en = 'UI/UX Designer', name_ku = 'دیزاینەری UI/UX', name_tr = 'UI/UX Tasarımcı' WHERE slug = 'jobs_it_ui_ux';
UPDATE public.categories SET name_en = 'Web Developer', name_ku = 'گەشەپێدەری وێب', name_tr = 'Web Geliştirici' WHERE slug = 'jobs_it_web_dev';
UPDATE public.categories SET name_en = 'Dentist', name_ku = 'ددانساز', name_tr = 'Diş Hekimi' WHERE slug = 'jobs_med_dentist';
UPDATE public.categories SET name_en = 'Doctor', name_ku = 'پزیشک', name_tr = 'Doktor' WHERE slug = 'jobs_med_doctor';
UPDATE public.categories SET name_en = 'Hospital Administrator', name_ku = 'بەڕێوەبەری نەخۆشخانە', name_tr = 'Hastane Yöneticisi' WHERE slug = 'jobs_med_hospital_admin';
UPDATE public.categories SET name_en = 'Medical Lab Technician', name_ku = 'تەکنیکی تاقیگەی پزیشکی', name_tr = 'Tıbbi Laborant' WHERE slug = 'jobs_med_lab_tech';
UPDATE public.categories SET name_en = 'Nurse', name_ku = 'پەرستار', name_tr = 'Hemşire' WHERE slug = 'jobs_med_nurse';
UPDATE public.categories SET name_en = 'Paramedic', name_ku = 'پزیشکی فریاکەوتن', name_tr = 'Paramedik' WHERE slug = 'jobs_med_paramedic';
UPDATE public.categories SET name_en = 'Pharmacist', name_ku = 'دەرمانساز', name_tr = 'Eczacı' WHERE slug = 'jobs_med_pharmacist';
UPDATE public.categories SET name_en = 'Physiotherapist', name_ku = 'چارەسەری فیزیایی', name_tr = 'Fizyoterapist' WHERE slug = 'jobs_med_physiotherapist';
UPDATE public.categories SET name_en = 'Content Writer', name_ku = 'نووسەری ناوەڕۆk', name_tr = 'İçerik Yazarı' WHERE slug = 'jobs_media_content_writer';
UPDATE public.categories SET name_en = 'Graphic Designer', name_ku = 'دیزاینەری گرافیک', name_tr = 'Grafik Tasarımcı' WHERE slug = 'jobs_media_graphic_designer';
UPDATE public.categories SET name_en = 'Journalist & Presenter', name_ku = 'ڕۆژنامەvan و پێشکەشکار', name_tr = 'Gazeteci ve Sunucu' WHERE slug = 'jobs_media_journalist';
UPDATE public.categories SET name_en = 'Photographer & Videographer', name_ku = 'وێنەگر و ڤیدیۆگر', name_tr = 'Fotoğrafçı ve Videograf' WHERE slug = 'jobs_media_photographer';
UPDATE public.categories SET name_en = 'Broadcast Producer', name_ku = 'بەرهەمهێنەری ڕادیۆ و تەلەفزیۆn', name_tr = 'Yapımcı' WHERE slug = 'jobs_media_producer';
UPDATE public.categories SET name_en = 'Social Media Manager', name_ku = 'بەڕێوەبەری تۆڕە کۆمەڵایەتییەکان', name_tr = 'Sosyal Medya Yöneticisi' WHERE slug = 'jobs_media_social_media';
UPDATE public.categories SET name_en = 'Translator', name_ku = 'وەرگێڕ', name_tr = 'Tercüman' WHERE slug = 'jobs_media_translator';
UPDATE public.categories SET name_en = 'Video Editor', name_ku = 'مۆنتێر', name_tr = 'Video Editörü' WHERE slug = 'jobs_media_video_editor';
UPDATE public.categories SET name_en = 'Drilling Engineer', name_ku = 'ئەندازیاری کۆنکردن', name_tr = 'Sondaj Mühendisi' WHERE slug = 'jobs_oil_drilling_eng';
UPDATE public.categories SET name_en = 'Geologist', name_ku = 'جیۆلۆژ', name_tr = 'Jeolog' WHERE slug = 'jobs_oil_geologist';
UPDATE public.categories SET name_en = 'HSE Safety & Environment', name_ku = 'سلامەت و HSE', name_tr = 'İSG ve Çevre' WHERE slug = 'jobs_oil_hse';
UPDATE public.categories SET name_en = 'Power Plant Operator', name_ku = 'کارگێڕی وێستگەی وزە', name_tr = 'Enerji Santrali Operatörü' WHERE slug = 'jobs_oil_power_plant';
UPDATE public.categories SET name_en = 'Solar Energy Technician', name_ku = 'تەکنیکی وزەی خۆر', name_tr = 'Güneş Enerjisi Teknisyeni' WHERE slug = 'jobs_oil_solar_tech';
UPDATE public.categories SET name_en = 'Oil Facilities Technician', name_ku = 'تەکنیکی دامەزراوەی نەوت', name_tr = 'Petrol Tesis Teknisyeni' WHERE slug = 'jobs_oil_tech';
UPDATE public.categories SET name_en = 'AC & Refrigeration Technician', name_ku = 'تەکنیکی کۆndیشن', name_tr = 'Klima Teknisyeni' WHERE slug = 'jobs_trade_ac_tech';
UPDATE public.categories SET name_en = 'Barber & Salon', name_ku = 'سەرتاش و سالۆn', name_tr = 'Berber' WHERE slug = 'jobs_trade_barber';
UPDATE public.categories SET name_en = 'Carpenter & Furniture', name_ku = 'نجار و کەلوپەل', name_tr = 'Marangoz' WHERE slug = 'jobs_trade_carpenter';
UPDATE public.categories SET name_en = 'Driver', name_ku = 'شۆfêr', name_tr = 'Şoför' WHERE slug = 'jobs_trade_driver';
UPDATE public.categories SET name_en = 'Auto Mechanic', name_ku = 'میکانیکی ئۆتۆمبێل', name_tr = 'Oto Tamircisi' WHERE slug = 'jobs_trade_mechanic';
UPDATE public.categories SET name_en = 'Painter & Decorator', name_ku = 'ڕەنگکەر و دیکۆr', name_tr = 'Boyacı' WHERE slug = 'jobs_trade_painter';
UPDATE public.categories SET name_en = 'Plumber', name_ku = 'بۆریچی', name_tr = 'Tesisatçı' WHERE slug = 'jobs_trade_plumber';
UPDATE public.categories SET name_en = 'Security Guard', name_ku = 'پاسewan', name_tr = 'Güvenlik Görevlisi' WHERE slug = 'jobs_trade_security';
UPDATE public.categories SET name_en = 'Tailor', name_ku = 'خیاط', name_tr = 'Terzi' WHERE slug = 'jobs_trade_tailor';
UPDATE public.categories SET name_en = 'Welder & Blacksmith', name_ku = 'ئاسنگەر و جوڵکەر', name_tr = 'Kaynakçı' WHERE slug = 'jobs_trade_welder';

-- Clear Arabic wrongly copied into name_en for souq models
UPDATE public.categories SET name_en = NULL, name_ku = NULL, name_tr = NULL
WHERE icon = 'model' AND slug LIKE 'souq_%'
  AND name_en ~ '[\u0600-\u06FF]';

-- Souq marketplace item names
UPDATE public.categories SET name_en = 'Smartphones', name_ku = 'Smartphones', name_tr = 'Akıllı Telefonlar' WHERE slug = 'souq_mobile_item_01';
UPDATE public.categories SET name_en = 'iPhone', name_ku = 'iPhone', name_tr = 'iPhone' WHERE slug = 'souq_mobile_item_02';
UPDATE public.categories SET name_en = 'Samsung', name_ku = 'Samsung', name_tr = 'Samsung' WHERE slug = 'souq_mobile_item_03';
UPDATE public.categories SET name_en = 'Huawei', name_ku = 'Huawei', name_tr = 'Huawei' WHERE slug = 'souq_mobile_item_04';
UPDATE public.categories SET name_en = 'Xiaomi & Redmi', name_ku = 'Xiaomi & Redmi', name_tr = 'Xiaomi ve Redmi' WHERE slug = 'souq_mobile_item_05';
UPDATE public.categories SET name_en = 'Oppo & Vivo', name_ku = 'Oppo & Vivo', name_tr = 'Oppo ve Vivo' WHERE slug = 'souq_mobile_item_06';
UPDATE public.categories SET name_en = 'Basic Phones', name_ku = 'Basic Phones', name_tr = 'Basit Telefonlar' WHERE slug = 'souq_mobile_item_07';
UPDATE public.categories SET name_en = 'Chargers & Cables', name_ku = 'Chargers & Cables', name_tr = 'Şarj Aletleri ve Kablolar' WHERE slug = 'souq_mobile_item_08';
UPDATE public.categories SET name_en = 'Power Banks', name_ku = 'Power Banks', name_tr = 'Powerbank' WHERE slug = 'souq_mobile_item_09';
UPDATE public.categories SET name_en = 'Cases & Protection', name_ku = 'Cases & Protection', name_tr = 'Kılıf ve Koruma' WHERE slug = 'souq_mobile_item_10';
UPDATE public.categories SET name_en = 'Bluetooth Headsets', name_ku = 'Bluetooth Headsets', name_tr = 'Bluetooth Kulaklık' WHERE slug = 'souq_mobile_item_11';
UPDATE public.categories SET name_en = 'Smartwatches', name_ku = 'Smartwatches', name_tr = 'Akıllı Saatler' WHERE slug = 'souq_mobile_item_12';
UPDATE public.categories SET name_en = 'Phone Spare Parts', name_ku = 'Phone Spare Parts', name_tr = 'Telefon Yedek Parça' WHERE slug = 'souq_mobile_item_13';
UPDATE public.categories SET name_en = 'Phone Batteries', name_ku = 'Phone Batteries', name_tr = 'Telefon Bataryası' WHERE slug = 'souq_mobile_item_14';
UPDATE public.categories SET name_en = 'Laptops', name_ku = 'Laptops', name_tr = 'Laptop' WHERE slug = 'souq_computer_item_01';
UPDATE public.categories SET name_en = 'Mac Laptops', name_ku = 'Mac Laptops', name_tr = 'Mac Laptop' WHERE slug = 'souq_computer_item_02';
UPDATE public.categories SET name_en = 'Desktop Computers', name_ku = 'Desktop Computers', name_tr = 'Masaüstü Bilgisayar' WHERE slug = 'souq_computer_item_03';
UPDATE public.categories SET name_en = 'Monitors', name_ku = 'Monitors', name_tr = 'Monitörler' WHERE slug = 'souq_computer_item_04';
UPDATE public.categories SET name_en = 'Keyboard & Mouse', name_ku = 'Keyboard & Mouse', name_tr = 'Klavye ve Fare' WHERE slug = 'souq_computer_item_05';
UPDATE public.categories SET name_en = 'Printers & Scanners', name_ku = 'Printers & Scanners', name_tr = 'Yazıcı ve Tarayıcı' WHERE slug = 'souq_computer_item_06';
UPDATE public.categories SET name_en = 'Hard Drives', name_ku = 'Hard Drives', name_tr = 'Hard Disk' WHERE slug = 'souq_computer_item_07';
UPDATE public.categories SET name_en = 'RAM & Internal Parts', name_ku = 'RAM & Internal Parts', name_tr = 'RAM ve Dahili Parçalar' WHERE slug = 'souq_computer_item_08';
UPDATE public.categories SET name_en = 'Graphics Cards (GPU)', name_ku = 'Graphics Cards (GPU)', name_tr = 'Ekran Kartı (GPU)' WHERE slug = 'souq_computer_gpu';
UPDATE public.categories SET name_en = 'Routers & Networking', name_ku = 'Routers & Networking', name_tr = 'Router ve Ağ' WHERE slug = 'souq_computer_item_10';
UPDATE public.categories SET name_en = 'UPS & Batteries', name_ku = 'UPS & Batteries', name_tr = 'UPS ve Batarya' WHERE slug = 'souq_computer_ups';
UPDATE public.categories SET name_en = 'USB Drives & Memory', name_ku = 'USB Drives & Memory', name_tr = 'Flash Bellek' WHERE slug = 'souq_computer_item_12';
UPDATE public.categories SET name_en = 'Smart TV', name_ku = 'Smart TV', name_tr = 'Smart TV' WHERE slug = 'souq_tv_audio_item_01';
UPDATE public.categories SET name_en = 'OLED TV', name_ku = 'OLED TV', name_tr = 'OLED TV' WHERE slug = 'souq_tv_audio_oled';
UPDATE public.categories SET name_en = 'QLED TV', name_ku = 'QLED TV', name_tr = 'QLED TV' WHERE slug = 'souq_tv_audio_qled';
UPDATE public.categories SET name_en = 'Standard TV', name_ku = 'Standard TV', name_tr = 'Normal TV' WHERE slug = 'souq_tv_audio_item_04';
UPDATE public.categories SET name_en = 'Receivers & Satellite', name_ku = 'Receivers & Satellite', name_tr = 'Uydu Alıcı' WHERE slug = 'souq_tv_audio_item_05';
UPDATE public.categories SET name_en = 'Home Theater', name_ku = 'Home Theater', name_tr = 'Ev Sineması' WHERE slug = 'souq_tv_audio_item_06';
UPDATE public.categories SET name_en = 'Speakers', name_ku = 'Speakers', name_tr = 'Hoparlör' WHERE slug = 'souq_tv_audio_item_07';
UPDATE public.categories SET name_en = 'Home Audio', name_ku = 'Home Audio', name_tr = 'Ev Ses Sistemi' WHERE slug = 'souq_tv_audio_item_08';
UPDATE public.categories SET name_en = 'Projectors', name_ku = 'Projectors', name_tr = 'Projektör' WHERE slug = 'souq_tv_audio_item_09';
UPDATE public.categories SET name_en = 'Remotes & Accessories', name_ku = 'Remotes & Accessories', name_tr = 'Kumanda ve Aksesuar' WHERE slug = 'souq_tv_audio_item_10';
UPDATE public.categories SET name_en = 'Washing Machines', name_ku = 'Washing Machines', name_tr = 'Çamaşır Makinesi' WHERE slug = 'souq_appliances_item_01';
UPDATE public.categories SET name_en = 'Dishwashers', name_ku = 'Dishwashers', name_tr = 'Bulaşık Makinesi' WHERE slug = 'souq_appliances_item_02';
UPDATE public.categories SET name_en = 'Refrigerators', name_ku = 'Refrigerators', name_tr = 'Buzdolabı' WHERE slug = 'souq_appliances_item_03';
UPDATE public.categories SET name_en = 'Freezers', name_ku = 'Freezers', name_tr = 'Derin Dondurucu' WHERE slug = 'souq_appliances_item_04';
UPDATE public.categories SET name_en = 'Split AC', name_ku = 'Split AC', name_tr = 'Split Klima' WHERE slug = 'souq_appliances_item_05';
UPDATE public.categories SET name_en = 'Window AC', name_ku = 'Window AC', name_tr = 'Pencere Kliması' WHERE slug = 'souq_appliances_item_06';
UPDATE public.categories SET name_en = 'Portable AC', name_ku = 'Portable AC', name_tr = 'Taşınabilir Klima' WHERE slug = 'souq_appliances_item_07';
UPDATE public.categories SET name_en = 'Fans', name_ku = 'Fans', name_tr = 'Vantilatör' WHERE slug = 'souq_appliances_item_08';
UPDATE public.categories SET name_en = 'Electric Heaters', name_ku = 'Electric Heaters', name_tr = 'Elektrikli Isıtıcı' WHERE slug = 'souq_appliances_item_09';
UPDATE public.categories SET name_en = 'Vacuum Cleaners', name_ku = 'Vacuum Cleaners', name_tr = 'Elektrikli Süpürge' WHERE slug = 'souq_appliances_item_10';
UPDATE public.categories SET name_en = 'Irons', name_ku = 'Irons', name_tr = 'Ütü' WHERE slug = 'souq_appliances_item_11';
UPDATE public.categories SET name_en = 'Sterilizers', name_ku = 'Sterilizers', name_tr = 'Sterilizatör' WHERE slug = 'souq_appliances_item_12';
UPDATE public.categories SET name_en = 'Gas Stoves', name_ku = 'Gas Stoves', name_tr = 'Gaz Ocağı' WHERE slug = 'souq_kitchen_item_01';
UPDATE public.categories SET name_en = 'Electric Ovens', name_ku = 'Electric Ovens', name_tr = 'Elektrikli Fırın' WHERE slug = 'souq_kitchen_item_02';
UPDATE public.categories SET name_en = 'Microwaves', name_ku = 'Microwaves', name_tr = 'Mikrodalga' WHERE slug = 'souq_kitchen_item_03';
UPDATE public.categories SET name_en = 'Air Fryers', name_ku = 'Air Fryers', name_tr = 'Air Fryer' WHERE slug = 'souq_kitchen_item_04';
UPDATE public.categories SET name_en = 'Blenders & Juicers', name_ku = 'Blenders & Juicers', name_tr = 'Blender ve Sıkacağı' WHERE slug = 'souq_kitchen_item_05';
UPDATE public.categories SET name_en = 'Coffee & Tea Makers', name_ku = 'Coffee & Tea Makers', name_tr = 'Kahve ve Çay Makinesi' WHERE slug = 'souq_kitchen_item_06';
UPDATE public.categories SET name_en = 'Sandwich & Toaster', name_ku = 'Sandwich & Toaster', name_tr = 'Tost Makinesi' WHERE slug = 'souq_kitchen_item_07';
UPDATE public.categories SET name_en = 'Electric Pressure Cooker', name_ku = 'Electric Pressure Cooker', name_tr = 'Elektrikli Düdüklü' WHERE slug = 'souq_kitchen_item_08';
UPDATE public.categories SET name_en = 'Bread Makers', name_ku = 'Bread Makers', name_tr = 'Ekmek Yapma Makinesi' WHERE slug = 'souq_kitchen_item_09';
UPDATE public.categories SET name_en = 'Kitchenware & Accessories', name_ku = 'Kitchenware & Accessories', name_tr = 'Mutfak Gereçleri' WHERE slug = 'souq_kitchen_item_10';
UPDATE public.categories SET name_en = 'PlayStation 5', name_ku = 'PlayStation 5', name_tr = 'PlayStation 5' WHERE slug = 'souq_gaming_5';
UPDATE public.categories SET name_en = 'PlayStation 4', name_ku = 'PlayStation 4', name_tr = 'PlayStation 4' WHERE slug = 'souq_gaming_4';
UPDATE public.categories SET name_en = 'Xbox Series X/S', name_ku = 'Xbox Series X/S', name_tr = 'Xbox Series X/S' WHERE slug = 'souq_gaming_xbox_series_x_s';
UPDATE public.categories SET name_en = 'Nintendo Switch', name_ku = 'Nintendo Switch', name_tr = 'Nintendo Switch' WHERE slug = 'souq_gaming_nintendo_switch';
UPDATE public.categories SET name_en = 'Game Discs & Cards', name_ku = 'Game Discs & Cards', name_tr = 'Oyun CD ve Kartları' WHERE slug = 'souq_gaming_cd';
UPDATE public.categories SET name_en = 'Controllers & Accessories', name_ku = 'Controllers & Accessories', name_tr = 'Kol ve Aksesuar' WHERE slug = 'souq_gaming_item_06';
UPDATE public.categories SET name_en = 'VR Headsets', name_ku = 'VR Headsets', name_tr = 'VR Headset' WHERE slug = 'souq_gaming_vr_headset';
UPDATE public.categories SET name_en = 'Electronic Kids Toys', name_ku = 'Electronic Kids Toys', name_tr = 'Elektronik Çocuk Oyuncakları' WHERE slug = 'souq_gaming_item_08';
UPDATE public.categories SET name_en = 'Men''s Clothing', name_ku = 'Men''s Clothing', name_tr = 'Erkek Giyim' WHERE slug = 'souq_fashion_item_01';
UPDATE public.categories SET name_en = 'Women''s Clothing', name_ku = 'Women''s Clothing', name_tr = 'Kadın Giyim' WHERE slug = 'souq_fashion_item_02';
UPDATE public.categories SET name_en = 'Kids'' Clothing', name_ku = 'Kids'' Clothing', name_tr = 'Çocuk Giyim' WHERE slug = 'souq_fashion_item_03';
UPDATE public.categories SET name_en = 'Abayas & Dishdashas', name_ku = 'Abayas & Dishdashas', name_tr = 'Abaya ve Dış Giyim' WHERE slug = 'souq_fashion_item_04';
UPDATE public.categories SET name_en = 'Men''s Shoes', name_ku = 'Men''s Shoes', name_tr = 'Erkek Ayakkabı' WHERE slug = 'souq_fashion_item_05';
UPDATE public.categories SET name_en = 'Women''s Shoes', name_ku = 'Women''s Shoes', name_tr = 'Kadın Ayakkabı' WHERE slug = 'souq_fashion_item_06';
UPDATE public.categories SET name_en = 'Kids'' Shoes', name_ku = 'Kids'' Shoes', name_tr = 'Çocuk Ayakkabı' WHERE slug = 'souq_fashion_item_07';
UPDATE public.categories SET name_en = 'Handbags', name_ku = 'Handbags', name_tr = 'El Çantası' WHERE slug = 'souq_fashion_item_08';
UPDATE public.categories SET name_en = 'Travel Bags & Luggage', name_ku = 'Travel Bags & Luggage', name_tr = 'Valiz ve Çanta' WHERE slug = 'souq_fashion_item_09';
UPDATE public.categories SET name_en = 'Wristwatches', name_ku = 'Wristwatches', name_tr = 'Kol Saati' WHERE slug = 'souq_fashion_item_10';
UPDATE public.categories SET name_en = 'Glasses', name_ku = 'Glasses', name_tr = 'Gözlük' WHERE slug = 'souq_fashion_item_11';
UPDATE public.categories SET name_en = 'Fashion Accessories', name_ku = 'Fashion Accessories', name_tr = 'Moda Aksesuarları' WHERE slug = 'souq_fashion_item_12';
UPDATE public.categories SET name_en = 'Men''s Perfumes', name_ku = 'Men''s Perfumes', name_tr = 'Erkek Parfüm' WHERE slug = 'souq_beauty_item_01';
UPDATE public.categories SET name_en = 'Women''s Perfumes', name_ku = 'Women''s Perfumes', name_tr = 'Kadın Parfüm' WHERE slug = 'souq_beauty_item_02';
UPDATE public.categories SET name_en = 'Skincare Products', name_ku = 'Skincare Products', name_tr = 'Cilt Bakım Ürünleri' WHERE slug = 'souq_beauty_item_03';
UPDATE public.categories SET name_en = 'Makeup & Beauty', name_ku = 'Makeup & Beauty', name_tr = 'Makyaj ve Güzellik' WHERE slug = 'souq_beauty_item_04';
UPDATE public.categories SET name_en = 'Beauty Devices', name_ku = 'Beauty Devices', name_tr = 'Güzellik Cihazları' WHERE slug = 'souq_beauty_item_05';
UPDATE public.categories SET name_en = 'Health Monitors', name_ku = 'Health Monitors', name_tr = 'Sağlık Ölçüm Cihazları' WHERE slug = 'souq_beauty_item_06';
UPDATE public.categories SET name_en = 'Vitamins & Supplements', name_ku = 'Vitamins & Supplements', name_tr = 'Vitamin ve Takviye' WHERE slug = 'souq_beauty_item_07';
UPDATE public.categories SET name_en = 'Massage Chairs', name_ku = 'Massage Chairs', name_tr = 'Masaj Koltuğu' WHERE slug = 'souq_beauty_item_08';
UPDATE public.categories SET name_en = 'Prescription Glasses', name_ku = 'Prescription Glasses', name_tr = 'Numaralı Gözlük' WHERE slug = 'souq_beauty_item_09';
UPDATE public.categories SET name_en = 'Shaving Tools', name_ku = 'Shaving Tools', name_tr = 'Tıraş Aletleri' WHERE slug = 'souq_beauty_item_10';
UPDATE public.categories SET name_en = 'Bedroom Furniture', name_ku = 'Bedroom Furniture', name_tr = 'Yatak Odası' WHERE slug = 'souq_furniture_item_01';
UPDATE public.categories SET name_en = 'Living Room Furniture', name_ku = 'Living Room Furniture', name_tr = 'Oturma Odası' WHERE slug = 'souq_furniture_item_02';
UPDATE public.categories SET name_en = 'Dining Tables & Sets', name_ku = 'Dining Tables & Sets', name_tr = 'Yemek Masası' WHERE slug = 'souq_furniture_item_03';
UPDATE public.categories SET name_en = 'Office & Study', name_ku = 'Office & Study', name_tr = 'Ofis ve Çalışma' WHERE slug = 'souq_furniture_item_04';
UPDATE public.categories SET name_en = 'Curtains & Carpets', name_ku = 'Curtains & Carpets', name_tr = 'Perde ve Halı' WHERE slug = 'souq_furniture_item_05';
UPDATE public.categories SET name_en = 'Kitchen & Cabinets', name_ku = 'Kitchen & Cabinets', name_tr = 'Mutfak ve Dolap' WHERE slug = 'souq_furniture_item_06';
UPDATE public.categories SET name_en = 'Lighting & Chandeliers', name_ku = 'Lighting & Chandeliers', name_tr = 'Aydınlatma ve Avize' WHERE slug = 'souq_furniture_item_07';
UPDATE public.categories SET name_en = 'Decor & Art', name_ku = 'Decor & Art', name_tr = 'Dekor ve Tablo' WHERE slug = 'souq_furniture_item_08';
UPDATE public.categories SET name_en = 'Linens & Bedding', name_ku = 'Linens & Bedding', name_tr = 'Nevresim ve Yatak' WHERE slug = 'souq_furniture_item_09';
UPDATE public.categories SET name_en = 'Misc Home Items', name_ku = 'Misc Home Items', name_tr = 'Ev Eşyaları' WHERE slug = 'souq_furniture_item_10';
UPDATE public.categories SET name_en = 'Home Gym Equipment', name_ku = 'Home Gym Equipment', name_tr = 'Ev Spor Aletleri' WHERE slug = 'souq_sports_item_01';
UPDATE public.categories SET name_en = 'Treadmills & Exercise Bikes', name_ku = 'Treadmills & Exercise Bikes', name_tr = 'Koşu Bandı ve Bisiklet' WHERE slug = 'souq_sports_item_02';
UPDATE public.categories SET name_en = 'Weights & Dumbbells', name_ku = 'Weights & Dumbbells', name_tr = 'Ağırlık ve Dambıl' WHERE slug = 'souq_sports_item_03';
UPDATE public.categories SET name_en = 'Sportswear', name_ku = 'Sportswear', name_tr = 'Spor Giyim' WHERE slug = 'souq_sports_item_04';
UPDATE public.categories SET name_en = 'Sports Shoes', name_ku = 'Sports Shoes', name_tr = 'Spor Ayakkabı' WHERE slug = 'souq_sports_item_05';
UPDATE public.categories SET name_en = 'Football & Gear', name_ku = 'Football & Gear', name_tr = 'Futbol ve Malzemeleri' WHERE slug = 'souq_sports_item_06';
UPDATE public.categories SET name_en = 'Basketball & Volleyball', name_ku = 'Basketball & Volleyball', name_tr = 'Basketbol ve Voleybol' WHERE slug = 'souq_sports_item_07';
UPDATE public.categories SET name_en = 'Swimming & Diving', name_ku = 'Swimming & Diving', name_tr = 'Yüzme ve Dalış' WHERE slug = 'souq_sports_item_08';
UPDATE public.categories SET name_en = 'Bicycles', name_ku = 'Bicycles', name_tr = 'Bisiklet' WHERE slug = 'souq_sports_item_09';
UPDATE public.categories SET name_en = 'Boxing & Martial Arts', name_ku = 'Boxing & Martial Arts', name_tr = 'Boks ve Dövüş Sanatları' WHERE slug = 'souq_sports_item_10';
UPDATE public.categories SET name_en = 'Camping & Outdoors', name_ku = 'Camping & Outdoors', name_tr = 'Kamp ve Outdoor' WHERE slug = 'souq_sports_item_11';
UPDATE public.categories SET name_en = 'Fishing', name_ku = 'Fishing', name_tr = 'Balık Tutma' WHERE slug = 'souq_sports_item_12';
UPDATE public.categories SET name_en = 'Strollers', name_ku = 'Strollers', name_tr = 'Bebek Arabası' WHERE slug = 'souq_baby_item_01';
UPDATE public.categories SET name_en = 'Car Seats', name_ku = 'Car Seats', name_tr = 'Oto Koltuğu' WHERE slug = 'souq_baby_item_02';
UPDATE public.categories SET name_en = 'Cribs & Beds', name_ku = 'Cribs & Beds', name_tr = 'Bebek Yatağı' WHERE slug = 'souq_baby_item_03';
UPDATE public.categories SET name_en = 'Baby & Infant Clothing', name_ku = 'Baby & Infant Clothing', name_tr = 'Bebek Giyim' WHERE slug = 'souq_baby_item_04';
UPDATE public.categories SET name_en = 'Kids Toys', name_ku = 'Kids Toys', name_tr = 'Çocuk Oyuncakları' WHERE slug = 'souq_baby_item_05';
UPDATE public.categories SET name_en = 'Feeding Supplies', name_ku = 'Feeding Supplies', name_tr = 'Beslenme Gereçleri' WHERE slug = 'souq_baby_item_06';
UPDATE public.categories SET name_en = 'Baby Monitors', name_ku = 'Baby Monitors', name_tr = 'Bebek Telsizi' WHERE slug = 'souq_baby_item_07';
UPDATE public.categories SET name_en = 'Baby Formula & Food', name_ku = 'Baby Formula & Food', name_tr = 'Bebek Maması' WHERE slug = 'souq_baby_item_08';
UPDATE public.categories SET name_en = 'School Bags & Supplies', name_ku = 'School Bags & Supplies', name_tr = 'Okul Çantası' WHERE slug = 'souq_baby_item_09';
UPDATE public.categories SET name_en = 'Kids Bikes & Ride-ons', name_ku = 'Kids Bikes & Ride-ons', name_tr = 'Çocuk Bisikleti' WHERE slug = 'souq_baby_item_10';
UPDATE public.categories SET name_en = 'Arabic Books', name_ku = 'Arabic Books', name_tr = 'Arapça Kitaplar' WHERE slug = 'souq_books_item_01';
UPDATE public.categories SET name_en = 'English Books', name_ku = 'English Books', name_tr = 'İngilizce Kitaplar' WHERE slug = 'souq_books_item_02';
UPDATE public.categories SET name_en = 'Textbooks & Curricula', name_ku = 'Textbooks & Curricula', name_tr = 'Ders Kitapları' WHERE slug = 'souq_books_item_03';
UPDATE public.categories SET name_en = 'Religious Books', name_ku = 'Religious Books', name_tr = 'Dini Kitaplar' WHERE slug = 'souq_books_item_04';
UPDATE public.categories SET name_en = 'Novels & Stories', name_ku = 'Novels & Stories', name_tr = 'Roman ve Hikaye' WHERE slug = 'souq_books_item_05';
UPDATE public.categories SET name_en = 'Magazines & Newspapers', name_ku = 'Magazines & Newspapers', name_tr = 'Dergi ve Gazete' WHERE slug = 'souq_books_item_06';
UPDATE public.categories SET name_en = 'Stationery & Office Supplies', name_ku = 'Stationery & Office Supplies', name_tr = 'Kırtasiye' WHERE slug = 'souq_books_item_07';
UPDATE public.categories SET name_en = 'Art & Drawing Supplies', name_ku = 'Art & Drawing Supplies', name_tr = 'Sanat Malzemeleri' WHERE slug = 'souq_books_item_08';
UPDATE public.categories SET name_en = 'Guitar', name_ku = 'Guitar', name_tr = 'Gitar' WHERE slug = 'souq_music_item_01';
UPDATE public.categories SET name_en = 'Oud & Qanun', name_ku = 'Oud & Qanun', name_tr = 'Ud ve Kanun' WHERE slug = 'souq_music_item_02';
UPDATE public.categories SET name_en = 'Piano & Organ', name_ku = 'Piano & Organ', name_tr = 'Piyano ve Org' WHERE slug = 'souq_music_item_03';
UPDATE public.categories SET name_en = 'Drums & Percussion', name_ku = 'Drums & Percussion', name_tr = 'Davul ve Perküsyon' WHERE slug = 'souq_music_item_04';
UPDATE public.categories SET name_en = 'DJ Mixers', name_ku = 'DJ Mixers', name_tr = 'DJ Mikser' WHERE slug = 'souq_music_dj';
UPDATE public.categories SET name_en = 'Microphones & Recording', name_ku = 'Microphones & Recording', name_tr = 'Mikrofon ve Kayıt' WHERE slug = 'souq_music_item_06';
UPDATE public.categories SET name_en = 'Flutes & Wind Instruments', name_ku = 'Flutes & Wind Instruments', name_tr = 'Nefesli Enstrüman' WHERE slug = 'souq_music_item_07';
UPDATE public.categories SET name_en = 'Karaoke Machine', name_ku = 'Karaoke Machine', name_tr = 'Karaoke Makinesi' WHERE slug = 'souq_music_item_08';
UPDATE public.categories SET name_en = 'Antiques & Collectibles', name_ku = 'Antiques & Collectibles', name_tr = 'Antika' WHERE slug = 'souq_hobbies_item_01';
UPDATE public.categories SET name_en = 'Stamps & Old Coins', name_ku = 'Stamps & Old Coins', name_tr = 'Pul ve Eski Para' WHERE slug = 'souq_hobbies_item_02';
UPDATE public.categories SET name_en = 'Art Paintings', name_ku = 'Art Paintings', name_tr = 'Tablo' WHERE slug = 'souq_hobbies_item_03';
UPDATE public.categories SET name_en = 'Board & Card Games', name_ku = 'Board & Card Games', name_tr = 'Kutu Oyunları' WHERE slug = 'souq_hobbies_item_04';
UPDATE public.categories SET name_en = 'Models & Miniatures', name_ku = 'Models & Miniatures', name_tr = 'Maket ve Model' WHERE slug = 'souq_hobbies_item_05';
UPDATE public.categories SET name_en = 'Drones & RC', name_ku = 'Drones & RC', name_tr = 'Drone ve RC' WHERE slug = 'souq_hobbies_item_06';
UPDATE public.categories SET name_en = 'Statues & Figurines', name_ku = 'Statues & Figurines', name_tr = 'Heykel ve Figür' WHERE slug = 'souq_hobbies_item_07';
UPDATE public.categories SET name_en = 'Sports Collectibles', name_ku = 'Sports Collectibles', name_tr = 'Spor Koleksiyon' WHERE slug = 'souq_hobbies_item_08';
UPDATE public.categories SET name_en = '21K Gold', name_ku = '21K Gold', name_tr = '21 Ayar Altın' WHERE slug = 'souq_jewelry_21';
UPDATE public.categories SET name_en = '18K Gold', name_ku = '18K Gold', name_tr = '18 Ayar Altın' WHERE slug = 'souq_jewelry_18';
UPDATE public.categories SET name_en = 'Silver', name_ku = 'Silver', name_tr = 'Gümüş' WHERE slug = 'souq_jewelry_item_03';
UPDATE public.categories SET name_en = 'Diamonds & Gemstones', name_ku = 'Diamonds & Gemstones', name_tr = 'Elmas ve Taş' WHERE slug = 'souq_jewelry_item_04';
UPDATE public.categories SET name_en = 'Rings & Bracelets', name_ku = 'Rings & Bracelets', name_tr = 'Yüzük ve Bilezik' WHERE slug = 'souq_jewelry_item_05';
UPDATE public.categories SET name_en = 'Necklaces', name_ku = 'Necklaces', name_tr = 'Kolye' WHERE slug = 'souq_jewelry_item_06';
UPDATE public.categories SET name_en = 'Luxury Watches', name_ku = 'Luxury Watches', name_tr = 'Lüks Saat' WHERE slug = 'souq_jewelry_item_07';
UPDATE public.categories SET name_en = 'Prayer Beads', name_ku = 'Prayer Beads', name_tr = 'Tesbih' WHERE slug = 'souq_jewelry_item_08';
UPDATE public.categories SET name_en = 'Iron & Steel', name_ku = 'Iron & Steel', name_tr = 'Demir ve Çelik' WHERE slug = 'souq_building_item_01';
UPDATE public.categories SET name_en = 'Cement & Blocks', name_ku = 'Cement & Blocks', name_tr = 'Çimento ve Blok' WHERE slug = 'souq_building_item_02';
UPDATE public.categories SET name_en = 'Bricks & Stone', name_ku = 'Bricks & Stone', name_tr = 'Tuğla ve Taş' WHERE slug = 'souq_building_item_03';
UPDATE public.categories SET name_en = 'Tiles & Ceramics', name_ku = 'Tiles & Ceramics', name_tr = 'Fayans ve Seramik' WHERE slug = 'souq_building_item_04';
UPDATE public.categories SET name_en = 'Paint & Wallpaper', name_ku = 'Paint & Wallpaper', name_tr = 'Boya ve Duvar Kağıdı' WHERE slug = 'souq_building_item_05';
UPDATE public.categories SET name_en = 'Doors & Windows', name_ku = 'Doors & Windows', name_tr = 'Kapı ve Pencere' WHERE slug = 'souq_building_item_06';
UPDATE public.categories SET name_en = 'Plumbing & Sanitary', name_ku = 'Plumbing & Sanitary', name_tr = 'Tesisat ve Banyo' WHERE slug = 'souq_building_item_07';
UPDATE public.categories SET name_en = 'Electrical & Lighting', name_ku = 'Electrical & Lighting', name_tr = 'Elektrik ve Aydınlatma' WHERE slug = 'souq_building_item_08';
UPDATE public.categories SET name_en = 'Hand & Power Tools', name_ku = 'Hand & Power Tools', name_tr = 'El ve Elektrikli Alet' WHERE slug = 'souq_building_item_09';
UPDATE public.categories SET name_en = 'Generators & Solar', name_ku = 'Generators & Solar', name_tr = 'Jeneratör ve Güneş' WHERE slug = 'souq_building_item_10';
UPDATE public.categories SET name_en = 'Plants & Trees', name_ku = 'Plants & Trees', name_tr = 'Bitki ve Ağaç' WHERE slug = 'souq_garden_item_01';
UPDATE public.categories SET name_en = 'Seeds & Fertilizer', name_ku = 'Seeds & Fertilizer', name_tr = 'Tohum ve Gübre' WHERE slug = 'souq_garden_item_02';
UPDATE public.categories SET name_en = 'Garden Tools', name_ku = 'Garden Tools', name_tr = 'Bahçe Aletleri' WHERE slug = 'souq_garden_item_03';
UPDATE public.categories SET name_en = 'Water Pumps', name_ku = 'Water Pumps', name_tr = 'Su Pompası' WHERE slug = 'souq_garden_item_04';
UPDATE public.categories SET name_en = 'Artificial Plants', name_ku = 'Artificial Plants', name_tr = 'Yapay Bitki' WHERE slug = 'souq_garden_item_05';
UPDATE public.categories SET name_en = 'Pots & Soil', name_ku = 'Pots & Soil', name_tr = 'Saksı ve Toprak' WHERE slug = 'souq_garden_item_06';
UPDATE public.categories SET name_en = 'Garden Fountains', name_ku = 'Garden Fountains', name_tr = 'Bahçe Fıskiyesi' WHERE slug = 'souq_garden_item_07';
UPDATE public.categories SET name_en = 'Dates & Iraqi Sweets', name_ku = 'Dates & Iraqi Sweets', name_tr = 'Hurma ve Irak Tatlıları' WHERE slug = 'souq_food_item_01';
UPDATE public.categories SET name_en = 'Natural Honey', name_ku = 'Natural Honey', name_tr = 'Doğal Bal' WHERE slug = 'souq_food_item_02';
UPDATE public.categories SET name_en = 'Olive Oil & Oils', name_ku = 'Olive Oil & Oils', name_tr = 'Zeytinyağı ve Yağlar' WHERE slug = 'souq_food_item_03';
UPDATE public.categories SET name_en = 'Dairy Products', name_ku = 'Dairy Products', name_tr = 'Süt Ürünleri' WHERE slug = 'souq_food_item_04';
UPDATE public.categories SET name_en = 'Jam & Canned Food', name_ku = 'Jam & Canned Food', name_tr = 'Reçel ve Konserve' WHERE slug = 'souq_food_item_05';
UPDATE public.categories SET name_en = 'Energy Drinks & Water', name_ku = 'Energy Drinks & Water', name_tr = 'Enerji İçeceği ve Su' WHERE slug = 'souq_food_item_06';
UPDATE public.categories SET name_en = 'Spices & Herbs', name_ku = 'Spices & Herbs', name_tr = 'Baharat ve Otlar' WHERE slug = 'souq_food_item_07';
UPDATE public.categories SET name_en = 'Organic Food', name_ku = 'Organic Food', name_tr = 'Organik Gıda' WHERE slug = 'souq_food_item_08';
UPDATE public.categories SET name_en = 'Gifts & Occasions', name_ku = 'Gifts & Occasions', name_tr = 'Hediye ve Özel Günler' WHERE slug = 'souq_misc_item_01';
UPDATE public.categories SET name_en = 'Religious Supplies', name_ku = 'Religious Supplies', name_tr = 'Dini Malzemeler' WHERE slug = 'souq_misc_item_02';
UPDATE public.categories SET name_en = 'Office Supplies', name_ku = 'Office Supplies', name_tr = 'Ofis Malzemeleri' WHERE slug = 'souq_misc_item_03';
UPDATE public.categories SET name_en = 'Travel Bags', name_ku = 'Travel Bags', name_tr = 'Seyahat Çantası' WHERE slug = 'souq_misc_item_04';
UPDATE public.categories SET name_en = 'Photography Supplies', name_ku = 'Photography Supplies', name_tr = 'Fotoğraf Malzemeleri' WHERE slug = 'souq_misc_item_05';
UPDATE public.categories SET name_en = 'Pro Photography Gear', name_ku = 'Pro Photography Gear', name_tr = 'Profesyonel Fotoğraf' WHERE slug = 'souq_misc_item_06';
UPDATE public.categories SET name_en = 'Wholesale Goods', name_ku = 'Wholesale Goods', name_tr = 'Toptan Ürün' WHERE slug = 'souq_misc_item_07';
UPDATE public.categories SET name_en = 'Other', name_ku = 'Other', name_tr = 'Diğer' WHERE slug = 'souq_misc_other';
