-- سيارات — brands and models (Arabic display where applicable, Latin brand/model names)
-- Safe to re-run: ON CONFLICT (slug) upserts; replaces veh_automobile / suv / ev / commercial subtrees.

CREATE OR REPLACE FUNCTION public._seed_car_node(
  p_slug TEXT,
  p_name_ar TEXT,
  p_parent_slug TEXT,
  p_icon TEXT DEFAULT 'category',
  p_display_order INT DEFAULT 0
) RETURNS VOID AS $$
DECLARE
  v_parent_id INT;
BEGIN
  SELECT id INTO v_parent_id FROM public.categories WHERE slug = p_parent_slug;
  IF v_parent_id IS NULL THEN
    RAISE EXCEPTION 'Parent category not found: %', p_parent_slug;
  END IF;

  INSERT INTO public.categories (slug, name_ar, name_ku, name_en, icon, parent_id, display_order)
  VALUES (p_slug, p_name_ar, NULL, NULL, p_icon, v_parent_id, p_display_order)
  ON CONFLICT (slug) DO UPDATE SET
    name_ar = EXCLUDED.name_ar,
    name_ku = NULL,
    name_en = NULL,
    icon = EXCLUDED.icon,
    parent_id = EXCLUDED.parent_id,
    display_order = EXCLUDED.display_order;
END;
$$ LANGUAGE plpgsql;

-- Clear existing subtrees (sale types + any prior brand/model rows)
DELETE FROM public.categories
WHERE id IN (
  WITH RECURSIVE targets AS (
    SELECT unnest(ARRAY[
      'veh_automobile', 'veh_suv_pickup', 'veh_electric', 'veh_commercial'
    ]) AS slug
  ),
  roots AS (
    SELECT c.id FROM public.categories c
    INNER JOIN targets t ON c.slug = t.slug
  ),
  subtree AS (
    SELECT c.id FROM public.categories c
    INNER JOIN roots r ON c.parent_id = r.id
    UNION ALL
    SELECT c.id FROM public.categories c
    INNER JOIN subtree s ON c.parent_id = s.id
  )
  SELECT id FROM subtree
);

SELECT public._seed_car_node('veh_auto_br_toyota', 'Toyota', 'veh_automobile', 'brand', 1);
SELECT public._seed_car_node('veh_auto_br_toyota_corolla', 'Corolla', 'veh_auto_br_toyota', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_toyota_camry', 'Camry', 'veh_auto_br_toyota', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_toyota_yaris', 'Yaris', 'veh_auto_br_toyota', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_toyota_avensis', 'Avensis', 'veh_auto_br_toyota', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_toyota_auris', 'Auris', 'veh_auto_br_toyota', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_toyota_verso', 'Verso', 'veh_auto_br_toyota', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_toyota_prius', 'Prius', 'veh_auto_br_toyota', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_toyota_supra', 'Supra', 'veh_auto_br_toyota', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_toyota_celica', 'Celica', 'veh_auto_br_toyota', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_toyota_gt86', 'GT86', 'veh_auto_br_toyota', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_toyota_land_cruiser', 'Land Cruiser', 'veh_auto_br_toyota', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_toyota_urban_cruiser', 'Urban Cruiser', 'veh_auto_br_toyota', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_toyota_starlet', 'Starlet', 'veh_auto_br_toyota', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_toyota_previa', 'Previa', 'veh_auto_br_toyota', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz', 'Mercedes-Benz', 'veh_automobile', 'brand', 2);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_a_class', 'A-Class', 'veh_auto_br_mercedes_benz', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_c_class', 'C-Class', 'veh_auto_br_mercedes_benz', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_e_class', 'E-Class', 'veh_auto_br_mercedes_benz', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_s_class', 'S-Class', 'veh_auto_br_mercedes_benz', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_cla', 'CLA', 'veh_auto_br_mercedes_benz', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_cls', 'CLS', 'veh_auto_br_mercedes_benz', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_gle', 'GLE', 'veh_auto_br_mercedes_benz', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_amg_gt', 'AMG GT', 'veh_auto_br_mercedes_benz', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_eqe', 'EQE', 'veh_auto_br_mercedes_benz', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_eqs', 'EQS', 'veh_auto_br_mercedes_benz', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_sl', 'SL', 'veh_auto_br_mercedes_benz', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_slk', 'SLK', 'veh_auto_br_mercedes_benz', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_clk', 'CLK', 'veh_auto_br_mercedes_benz', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_cl', 'CL', 'veh_auto_br_mercedes_benz', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_maybach_s_class', 'Maybach S-Class', 'veh_auto_br_mercedes_benz', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_b_class', 'B-Class', 'veh_auto_br_mercedes_benz', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_190', '190', 'veh_auto_br_mercedes_benz', 'model', 17);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_200', '200', 'veh_auto_br_mercedes_benz', 'model', 18);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_230', '230', 'veh_auto_br_mercedes_benz', 'model', 19);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_280', '280', 'veh_auto_br_mercedes_benz', 'model', 20);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_300', '300', 'veh_auto_br_mercedes_benz', 'model', 21);
SELECT public._seed_car_node('veh_auto_br_mercedes_benz_500', '500', 'veh_auto_br_mercedes_benz', 'model', 22);
SELECT public._seed_car_node('veh_auto_br_bmw', 'BMW', 'veh_automobile', 'brand', 3);
SELECT public._seed_car_node('veh_auto_br_bmw_1_series', '1-Series', 'veh_auto_br_bmw', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_bmw_2_series', '2-Series', 'veh_auto_br_bmw', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_bmw_3_series', '3-Series', 'veh_auto_br_bmw', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_bmw_4_series', '4-Series', 'veh_auto_br_bmw', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_bmw_5_series', '5-Series', 'veh_auto_br_bmw', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_bmw_6_series', '6-Series', 'veh_auto_br_bmw', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_bmw_7_series', '7-Series', 'veh_auto_br_bmw', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_bmw_8_series', '8-Series', 'veh_auto_br_bmw', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_bmw_x1', 'X1', 'veh_auto_br_bmw', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_bmw_x2', 'X2', 'veh_auto_br_bmw', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_bmw_x3', 'X3', 'veh_auto_br_bmw', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_bmw_x4', 'X4', 'veh_auto_br_bmw', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_bmw_x5', 'X5', 'veh_auto_br_bmw', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_bmw_x6', 'X6', 'veh_auto_br_bmw', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_bmw_x7', 'X7', 'veh_auto_br_bmw', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_bmw_xm', 'XM', 'veh_auto_br_bmw', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_bmw_z3', 'Z3', 'veh_auto_br_bmw', 'model', 17);
SELECT public._seed_car_node('veh_auto_br_bmw_z4', 'Z4', 'veh_auto_br_bmw', 'model', 18);
SELECT public._seed_car_node('veh_auto_br_bmw_i3', 'i3', 'veh_auto_br_bmw', 'model', 19);
SELECT public._seed_car_node('veh_auto_br_bmw_i4', 'i4', 'veh_auto_br_bmw', 'model', 20);
SELECT public._seed_car_node('veh_auto_br_bmw_i5', 'i5', 'veh_auto_br_bmw', 'model', 21);
SELECT public._seed_car_node('veh_auto_br_bmw_i8', 'i8', 'veh_auto_br_bmw', 'model', 22);
SELECT public._seed_car_node('veh_auto_br_bmw_ix', 'iX', 'veh_auto_br_bmw', 'model', 23);
SELECT public._seed_car_node('veh_auto_br_bmw_ix1', 'iX1', 'veh_auto_br_bmw', 'model', 24);
SELECT public._seed_car_node('veh_auto_br_bmw_ix3', 'iX3', 'veh_auto_br_bmw', 'model', 25);
SELECT public._seed_car_node('veh_auto_br_kia', 'Kia', 'veh_automobile', 'brand', 4);
SELECT public._seed_car_node('veh_auto_br_kia_cerato', 'Cerato', 'veh_auto_br_kia', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_kia_sportage', 'Sportage', 'veh_auto_br_kia', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_kia_sorento', 'Sorento', 'veh_auto_br_kia', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_kia_picanto', 'Picanto', 'veh_auto_br_kia', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_kia_rio', 'Rio', 'veh_auto_br_kia', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_kia_ceed', 'Ceed', 'veh_auto_br_kia', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_kia_optima', 'Optima', 'veh_auto_br_kia', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_kia_stinger', 'Stinger', 'veh_auto_br_kia', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_kia_carnival', 'Carnival', 'veh_auto_br_kia', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_kia_carens', 'Carens', 'veh_auto_br_kia', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_kia_venga', 'Venga', 'veh_auto_br_kia', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_kia_magentis', 'Magentis', 'veh_auto_br_kia', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_kia_capital', 'Capital', 'veh_auto_br_kia', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_kia_clarus', 'Clarus', 'veh_auto_br_kia', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_hyundai', 'Hyundai', 'veh_automobile', 'brand', 5);
SELECT public._seed_car_node('veh_auto_br_hyundai_elantra', 'Elantra', 'veh_auto_br_hyundai', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_hyundai_sonata', 'Sonata', 'veh_auto_br_hyundai', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_hyundai_tucson', 'Tucson', 'veh_auto_br_hyundai', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_hyundai_santa_fe', 'Santa Fe', 'veh_auto_br_hyundai', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_hyundai_i10', 'i10', 'veh_auto_br_hyundai', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_hyundai_i20', 'i20', 'veh_auto_br_hyundai', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_hyundai_i30', 'i30', 'veh_auto_br_hyundai', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_hyundai_i40', 'i40', 'veh_auto_br_hyundai', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_hyundai_accent', 'Accent', 'veh_auto_br_hyundai', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_hyundai_getz', 'Getz', 'veh_auto_br_hyundai', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_hyundai_genesis', 'Genesis', 'veh_auto_br_hyundai', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_hyundai_grandeur', 'Grandeur', 'veh_auto_br_hyundai', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_hyundai_ioniq', 'Ioniq', 'veh_auto_br_hyundai', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_hyundai_coupe', 'Coupe', 'veh_auto_br_hyundai', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_hyundai_matrix', 'Matrix', 'veh_auto_br_hyundai', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_hyundai_trajet', 'Trajet', 'veh_auto_br_hyundai', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_volkswagen', 'Volkswagen', 'veh_automobile', 'brand', 6);
SELECT public._seed_car_node('veh_auto_br_volkswagen_golf', 'Golf', 'veh_auto_br_volkswagen', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_volkswagen_passat', 'Passat', 'veh_auto_br_volkswagen', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_volkswagen_jetta', 'Jetta', 'veh_auto_br_volkswagen', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_volkswagen_polo', 'Polo', 'veh_auto_br_volkswagen', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_volkswagen_tiguan', 'Tiguan', 'veh_auto_br_volkswagen', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_volkswagen_touareg', 'Touareg', 'veh_auto_br_volkswagen', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_volkswagen_arteon', 'Arteon', 'veh_auto_br_volkswagen', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_volkswagen_beetle', 'Beetle', 'veh_auto_br_volkswagen', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_volkswagen_bora', 'Bora', 'veh_auto_br_volkswagen', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_volkswagen_scirocco', 'Scirocco', 'veh_auto_br_volkswagen', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_volkswagen_sharan', 'Sharan', 'veh_auto_br_volkswagen', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_volkswagen_touran', 'Touran', 'veh_auto_br_volkswagen', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_volkswagen_phaeton', 'Phaeton', 'veh_auto_br_volkswagen', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_volkswagen_eos', 'EOS', 'veh_auto_br_volkswagen', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_volkswagen_id_3', 'ID.3', 'veh_auto_br_volkswagen', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_volkswagen_id_7', 'ID.7', 'veh_auto_br_volkswagen', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_nissan', 'Nissan', 'veh_automobile', 'brand', 7);
SELECT public._seed_car_node('veh_auto_br_nissan_patrol', 'Patrol', 'veh_auto_br_nissan', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_nissan_x_trail', 'X-Trail', 'veh_auto_br_nissan', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_nissan_sunny', 'Sunny', 'veh_auto_br_nissan', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_nissan_sentra', 'Sentra', 'veh_auto_br_nissan', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_nissan_qashqai', 'Qashqai', 'veh_auto_br_nissan', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_nissan_navara', 'Navara', 'veh_auto_br_nissan', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_nissan_altima', 'Altima', 'veh_auto_br_nissan', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_nissan_maxima', 'Maxima', 'veh_auto_br_nissan', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_nissan_murano', 'Murano', 'veh_auto_br_nissan', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_nissan_pathfinder', 'Pathfinder', 'veh_auto_br_nissan', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_nissan_kicks', 'Kicks', 'veh_auto_br_nissan', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_nissan_frontier', 'Frontier', 'veh_auto_br_nissan', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_nissan_armada', 'Armada', 'veh_auto_br_nissan', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_nissan_tiida', 'Tiida', 'veh_auto_br_nissan', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_nissan_370z', '370Z', 'veh_auto_br_nissan', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_nissan_gt_r', 'GT-R', 'veh_auto_br_nissan', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_nissan_350z', '350Z', 'veh_auto_br_nissan', 'model', 17);
SELECT public._seed_car_node('veh_auto_br_nissan_leaf', 'Leaf', 'veh_auto_br_nissan', 'model', 18);
SELECT public._seed_car_node('veh_auto_br_nissan_juke', 'Juke', 'veh_auto_br_nissan', 'model', 19);
SELECT public._seed_car_node('veh_auto_br_nissan_rogue', 'Rogue', 'veh_auto_br_nissan', 'model', 20);
SELECT public._seed_car_node('veh_auto_br_nissan_versa', 'Versa', 'veh_auto_br_nissan', 'model', 21);
SELECT public._seed_car_node('veh_auto_br_nissan_z', 'Z', 'veh_auto_br_nissan', 'model', 22);
SELECT public._seed_car_node('veh_auto_br_nissan_ariya', 'Ariya', 'veh_auto_br_nissan', 'model', 23);
SELECT public._seed_car_node('veh_auto_br_nissan_almera', 'Almera', 'veh_auto_br_nissan', 'model', 24);
SELECT public._seed_car_node('veh_auto_br_honda', 'Honda', 'veh_automobile', 'brand', 8);
SELECT public._seed_car_node('veh_auto_br_honda_civic', 'Civic', 'veh_auto_br_honda', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_honda_accord', 'Accord', 'veh_auto_br_honda', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_honda_cr_v', 'CR-V', 'veh_auto_br_honda', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_honda_hr_v', 'HR-V', 'veh_auto_br_honda', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_honda_jazz', 'Jazz', 'veh_auto_br_honda', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_honda_city', 'City', 'veh_auto_br_honda', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_honda_pilot', 'Pilot', 'veh_auto_br_honda', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_honda_odyssey', 'Odyssey', 'veh_auto_br_honda', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_honda_legend', 'Legend', 'veh_auto_br_honda', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_honda_passport', 'Passport', 'veh_auto_br_honda', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_honda_ridgeline', 'Ridgeline', 'veh_auto_br_honda', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_honda_civic_type_r', 'Civic Type R', 'veh_auto_br_honda', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_honda_zr_v', 'ZR-V', 'veh_auto_br_honda', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_honda_prologue', 'Prologue', 'veh_auto_br_honda', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_ford', 'Ford', 'veh_automobile', 'brand', 9);
SELECT public._seed_car_node('veh_auto_br_ford_f_150', 'F-150', 'veh_auto_br_ford', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_ford_ranger', 'Ranger', 'veh_auto_br_ford', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_ford_explorer', 'Explorer', 'veh_auto_br_ford', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_ford_mustang', 'Mustang', 'veh_auto_br_ford', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_ford_focus', 'Focus', 'veh_auto_br_ford', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_ford_fusion', 'Fusion', 'veh_auto_br_ford', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_ford_escape', 'Escape', 'veh_auto_br_ford', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_ford_fiesta', 'Fiesta', 'veh_auto_br_ford', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_ford_expedition', 'Expedition', 'veh_auto_br_ford', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_ford_transit', 'Transit', 'veh_auto_br_ford', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_ford_bronco', 'Bronco', 'veh_auto_br_ford', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_ford_taurus', 'Taurus', 'veh_auto_br_ford', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_ford_territory', 'Territory', 'veh_auto_br_ford', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_ford_everest', 'Everest', 'veh_auto_br_ford', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_ford_maverick', 'Maverick', 'veh_auto_br_ford', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_ford_ecosport', 'EcoSport', 'veh_auto_br_ford', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_ford_mustang_mach_e', 'Mustang Mach-E', 'veh_auto_br_ford', 'model', 17);
SELECT public._seed_car_node('veh_auto_br_ford_f_250', 'F-250', 'veh_auto_br_ford', 'model', 18);
SELECT public._seed_car_node('veh_auto_br_ford_f_350', 'F-350', 'veh_auto_br_ford', 'model', 19);
SELECT public._seed_car_node('veh_auto_br_chevrolet', 'Chevrolet', 'veh_automobile', 'brand', 10);
SELECT public._seed_car_node('veh_auto_br_chevrolet_camaro', 'Camaro', 'veh_auto_br_chevrolet', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_chevrolet_corvette', 'Corvette', 'veh_auto_br_chevrolet', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_chevrolet_cruze', 'Cruze', 'veh_auto_br_chevrolet', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_chevrolet_impala', 'Impala', 'veh_auto_br_chevrolet', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_chevrolet_aveo', 'Aveo', 'veh_auto_br_chevrolet', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_chevrolet_caprice', 'Caprice', 'veh_auto_br_chevrolet', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_chevrolet_spark', 'Spark', 'veh_auto_br_chevrolet', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_chevrolet_lacetti', 'Lacetti', 'veh_auto_br_chevrolet', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_chevrolet_kalos', 'Kalos', 'veh_auto_br_chevrolet', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_chevrolet_epica', 'Epica', 'veh_auto_br_chevrolet', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_chevrolet_evanda', 'Evanda', 'veh_auto_br_chevrolet', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_chevrolet_monte_carlo', 'Monte Carlo', 'veh_auto_br_chevrolet', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_mitsubishi', 'Mitsubishi', 'veh_automobile', 'brand', 11);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_lancer', 'Lancer', 'veh_auto_br_mitsubishi', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_galant', 'Galant', 'veh_auto_br_mitsubishi', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_colt', 'Colt', 'veh_auto_br_mitsubishi', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_attrage', 'Attrage', 'veh_auto_br_mitsubishi', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_space_star', 'Space Star', 'veh_auto_br_mitsubishi', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_lancer_evolution', 'Lancer Evolution', 'veh_auto_br_mitsubishi', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_eclipse', 'Eclipse', 'veh_auto_br_mitsubishi', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_grandis', 'Grandis', 'veh_auto_br_mitsubishi', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_carisma', 'Carisma', 'veh_auto_br_mitsubishi', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_sigma', 'Sigma', 'veh_auto_br_mitsubishi', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_mitsubishi_3000gt', '3000GT', 'veh_auto_br_mitsubishi', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_land_rover', 'Land Rover', 'veh_automobile', 'brand', 12);
SELECT public._seed_car_node('veh_auto_br_land_rover_range_rover', 'Range Rover', 'veh_auto_br_land_rover', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_land_rover_range_rover_sport', 'Range Rover Sport', 'veh_auto_br_land_rover', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_land_rover_range_rover_vogue', 'Range Rover Vogue', 'veh_auto_br_land_rover', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_land_rover_defender', 'Defender', 'veh_auto_br_land_rover', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_land_rover_discovery', 'Discovery', 'veh_auto_br_land_rover', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_land_rover_freelander', 'Freelander', 'veh_auto_br_land_rover', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_land_rover_evoque', 'Evoque', 'veh_auto_br_land_rover', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_land_rover_velar', 'Velar', 'veh_auto_br_land_rover', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_land_rover_lr2', 'LR2', 'veh_auto_br_land_rover', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_land_rover_lr3', 'LR3', 'veh_auto_br_land_rover', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_land_rover_lr4', 'LR4', 'veh_auto_br_land_rover', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_jeep', 'Jeep', 'veh_automobile', 'brand', 13);
SELECT public._seed_car_node('veh_auto_br_jeep_grand_cherokee', 'Grand Cherokee', 'veh_auto_br_jeep', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_jeep_wrangler', 'Wrangler', 'veh_auto_br_jeep', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_jeep_cherokee', 'Cherokee', 'veh_auto_br_jeep', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_jeep_compass', 'Compass', 'veh_auto_br_jeep', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_jeep_commander', 'Commander', 'veh_auto_br_jeep', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_jeep_gladiator', 'Gladiator', 'veh_auto_br_jeep', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_jeep_renegade', 'Renegade', 'veh_auto_br_jeep', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_jeep_wagoneer', 'Wagoneer', 'veh_auto_br_jeep', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_jeep_grand_wagoneer', 'Grand Wagoneer', 'veh_auto_br_jeep', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_lexus', 'Lexus', 'veh_automobile', 'brand', 14);
SELECT public._seed_car_node('veh_auto_br_lexus_lx', 'LX', 'veh_auto_br_lexus', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_lexus_ls', 'LS', 'veh_auto_br_lexus', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_lexus_es', 'ES', 'veh_auto_br_lexus', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_lexus_gs', 'GS', 'veh_auto_br_lexus', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_lexus_gx', 'GX', 'veh_auto_br_lexus', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_lexus_rx', 'RX', 'veh_auto_br_lexus', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_lexus_is', 'IS', 'veh_auto_br_lexus', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_lexus_is_f', 'IS F', 'veh_auto_br_lexus', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_lexus_rc', 'RC', 'veh_auto_br_lexus', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_lexus_rc_f', 'RC F', 'veh_auto_br_lexus', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_lexus_nx', 'NX', 'veh_auto_br_lexus', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_lexus_ct', 'CT', 'veh_auto_br_lexus', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_lexus_sc', 'SC', 'veh_auto_br_lexus', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_lexus_ux', 'UX', 'veh_auto_br_lexus', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_lexus_tx', 'TX', 'veh_auto_br_lexus', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_lexus_lc', 'LC', 'veh_auto_br_lexus', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_lexus_lfa', 'LFA', 'veh_auto_br_lexus', 'model', 17);
SELECT public._seed_car_node('veh_auto_br_audi', 'Audi', 'veh_automobile', 'brand', 15);
SELECT public._seed_car_node('veh_auto_br_audi_a1', 'A1', 'veh_auto_br_audi', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_audi_a3', 'A3', 'veh_auto_br_audi', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_audi_a4', 'A4', 'veh_auto_br_audi', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_audi_a5', 'A5', 'veh_auto_br_audi', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_audi_a6', 'A6', 'veh_auto_br_audi', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_audi_a7', 'A7', 'veh_auto_br_audi', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_audi_a8', 'A8', 'veh_auto_br_audi', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_audi_s4', 'S4', 'veh_auto_br_audi', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_audi_s5', 'S5', 'veh_auto_br_audi', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_audi_s6', 'S6', 'veh_auto_br_audi', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_audi_s7', 'S7', 'veh_auto_br_audi', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_audi_s8', 'S8', 'veh_auto_br_audi', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_audi_q2', 'Q2', 'veh_auto_br_audi', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_audi_q3', 'Q3', 'veh_auto_br_audi', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_audi_q5', 'Q5', 'veh_auto_br_audi', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_audi_q7', 'Q7', 'veh_auto_br_audi', 'model', 16);
SELECT public._seed_car_node('veh_auto_br_audi_q8', 'Q8', 'veh_auto_br_audi', 'model', 17);
SELECT public._seed_car_node('veh_auto_br_audi_rs3', 'RS3', 'veh_auto_br_audi', 'model', 18);
SELECT public._seed_car_node('veh_auto_br_audi_rs5', 'RS5', 'veh_auto_br_audi', 'model', 19);
SELECT public._seed_car_node('veh_auto_br_audi_rs6', 'RS6', 'veh_auto_br_audi', 'model', 20);
SELECT public._seed_car_node('veh_auto_br_audi_rs7', 'RS7', 'veh_auto_br_audi', 'model', 21);
SELECT public._seed_car_node('veh_auto_br_audi_r8', 'R8', 'veh_auto_br_audi', 'model', 22);
SELECT public._seed_car_node('veh_auto_br_audi_tt', 'TT', 'veh_auto_br_audi', 'model', 23);
SELECT public._seed_car_node('veh_auto_br_audi_sq5', 'SQ5', 'veh_auto_br_audi', 'model', 24);
SELECT public._seed_car_node('veh_auto_br_audi_sq8', 'SQ8', 'veh_auto_br_audi', 'model', 25);
SELECT public._seed_car_node('veh_auto_br_porsche', 'Porsche', 'veh_automobile', 'brand', 16);
SELECT public._seed_car_node('veh_auto_br_porsche_911', '911', 'veh_auto_br_porsche', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_porsche_cayenne', 'Cayenne', 'veh_auto_br_porsche', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_porsche_panamera', 'Panamera', 'veh_auto_br_porsche', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_porsche_macan', 'Macan', 'veh_auto_br_porsche', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_porsche_boxster', 'Boxster', 'veh_auto_br_porsche', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_porsche_cayman', 'Cayman', 'veh_auto_br_porsche', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_porsche_taycan', 'Taycan', 'veh_auto_br_porsche', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_porsche_911_turbo', '911 Turbo', 'veh_auto_br_porsche', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_porsche_911_gt3', '911 GT3', 'veh_auto_br_porsche', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_dodge', 'Dodge', 'veh_automobile', 'brand', 17);
SELECT public._seed_car_node('veh_auto_br_dodge_charger', 'Charger', 'veh_auto_br_dodge', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_dodge_challenger', 'Challenger', 'veh_auto_br_dodge', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_dodge_durango', 'Durango', 'veh_auto_br_dodge', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_dodge_ram', 'Ram', 'veh_auto_br_dodge', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_dodge_journey', 'Journey', 'veh_auto_br_dodge', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_dodge_viper', 'Viper', 'veh_auto_br_dodge', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_dodge_dart', 'Dart', 'veh_auto_br_dodge', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_dodge_nitro', 'Nitro', 'veh_auto_br_dodge', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_dodge_dakota', 'Dakota', 'veh_auto_br_dodge', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_dodge_hornet', 'Hornet', 'veh_auto_br_dodge', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_dodge_magnum', 'Magnum', 'veh_auto_br_dodge', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_cadillac', 'Cadillac', 'veh_automobile', 'brand', 18);
SELECT public._seed_car_node('veh_auto_br_cadillac_escalade', 'Escalade', 'veh_auto_br_cadillac', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_cadillac_cts', 'CTS', 'veh_auto_br_cadillac', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_cadillac_ct4', 'CT4', 'veh_auto_br_cadillac', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_cadillac_ct5', 'CT5', 'veh_auto_br_cadillac', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_cadillac_ct6', 'CT6', 'veh_auto_br_cadillac', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_cadillac_ats', 'ATS', 'veh_auto_br_cadillac', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_cadillac_xt5', 'XT5', 'veh_auto_br_cadillac', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_cadillac_xt6', 'XT6', 'veh_auto_br_cadillac', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_cadillac_srx', 'SRX', 'veh_auto_br_cadillac', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_cadillac_dts', 'DTS', 'veh_auto_br_cadillac', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_cadillac_sts', 'STS', 'veh_auto_br_cadillac', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_cadillac_xts', 'XTS', 'veh_auto_br_cadillac', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_cadillac_lyriq', 'Lyriq', 'veh_auto_br_cadillac', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_cadillac_optiq', 'Optiq', 'veh_auto_br_cadillac', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_gmc', 'GMC', 'veh_automobile', 'brand', 19);
SELECT public._seed_car_node('veh_auto_br_gmc_yukon', 'Yukon', 'veh_auto_br_gmc', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_gmc_sierra', 'Sierra', 'veh_auto_br_gmc', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_gmc_terrain', 'Terrain', 'veh_auto_br_gmc', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_gmc_acadia', 'Acadia', 'veh_auto_br_gmc', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_gmc_canyon', 'Canyon', 'veh_auto_br_gmc', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_gmc_envoy', 'Envoy', 'veh_auto_br_gmc', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_gmc_jimmy', 'Jimmy', 'veh_auto_br_gmc', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_gmc_savana', 'Savana', 'veh_auto_br_gmc', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_gmc_yukon_xl', 'Yukon XL', 'veh_auto_br_gmc', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_gmc_hummer_ev', 'Hummer EV', 'veh_auto_br_gmc', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_volvo', 'Volvo', 'veh_automobile', 'brand', 20);
SELECT public._seed_car_node('veh_auto_br_volvo_s40', 'S40', 'veh_auto_br_volvo', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_volvo_s60', 'S60', 'veh_auto_br_volvo', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_volvo_s80', 'S80', 'veh_auto_br_volvo', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_volvo_s90', 'S90', 'veh_auto_br_volvo', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_volvo_v40', 'V40', 'veh_auto_br_volvo', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_volvo_v50', 'V50', 'veh_auto_br_volvo', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_volvo_v60', 'V60', 'veh_auto_br_volvo', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_volvo_v70', 'V70', 'veh_auto_br_volvo', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_volvo_v90', 'V90', 'veh_auto_br_volvo', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_volvo_xc40', 'XC40', 'veh_auto_br_volvo', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_volvo_xc60', 'XC60', 'veh_auto_br_volvo', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_volvo_xc70', 'XC70', 'veh_auto_br_volvo', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_volvo_xc90', 'XC90', 'veh_auto_br_volvo', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_volvo_c30', 'C30', 'veh_auto_br_volvo', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_volvo_c70', 'C70', 'veh_auto_br_volvo', 'model', 15);
SELECT public._seed_car_node('veh_auto_br_tesla', 'Tesla', 'veh_automobile', 'brand', 21);
SELECT public._seed_car_node('veh_auto_br_tesla_model_3', 'Model 3', 'veh_auto_br_tesla', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_tesla_model_s', 'Model S', 'veh_auto_br_tesla', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_tesla_model_x', 'Model X', 'veh_auto_br_tesla', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_tesla_model_y', 'Model Y', 'veh_auto_br_tesla', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_tesla_cybertruck', 'Cybertruck', 'veh_auto_br_tesla', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_maserati', 'Maserati', 'veh_automobile', 'brand', 22);
SELECT public._seed_car_node('veh_auto_br_maserati_quattroporte', 'Quattroporte', 'veh_auto_br_maserati', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_maserati_ghibli', 'Ghibli', 'veh_auto_br_maserati', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_maserati_levante', 'Levante', 'veh_auto_br_maserati', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_maserati_granturismo', 'GranTurismo', 'veh_auto_br_maserati', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_maserati_grancabrio', 'GranCabrio', 'veh_auto_br_maserati', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_maserati_grecale', 'Grecale', 'veh_auto_br_maserati', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_lamborghini', 'Lamborghini', 'veh_automobile', 'brand', 23);
SELECT public._seed_car_node('veh_auto_br_lamborghini_urus', 'Urus', 'veh_auto_br_lamborghini', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_lamborghini_aventador', 'Aventador', 'veh_auto_br_lamborghini', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_lamborghini_huracan', 'Huracan', 'veh_auto_br_lamborghini', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_lamborghini_gallardo', 'Gallardo', 'veh_auto_br_lamborghini', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_lamborghini_murcielago', 'Murcielago', 'veh_auto_br_lamborghini', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_lamborghini_temerario', 'Temerario', 'veh_auto_br_lamborghini', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_ferrari', 'Ferrari', 'veh_automobile', 'brand', 24);
SELECT public._seed_car_node('veh_auto_br_ferrari_f8_tributo', 'F8 Tributo', 'veh_auto_br_ferrari', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_ferrari_458', '458', 'veh_auto_br_ferrari', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_ferrari_488', '488', 'veh_auto_br_ferrari', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_ferrari_f430', 'F430', 'veh_auto_br_ferrari', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_ferrari_california', 'California', 'veh_auto_br_ferrari', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_ferrari_roma', 'Roma', 'veh_auto_br_ferrari', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_ferrari_812_superfast', '812 Superfast', 'veh_auto_br_ferrari', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_ferrari_portofino', 'Portofino', 'veh_auto_br_ferrari', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_ferrari_laferrari', 'LaFerrari', 'veh_auto_br_ferrari', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_rolls_royce', 'Rolls-Royce', 'veh_automobile', 'brand', 25);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_phantom', 'Phantom', 'veh_auto_br_rolls_royce', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_ghost', 'Ghost', 'veh_auto_br_rolls_royce', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_wraith', 'Wraith', 'veh_auto_br_rolls_royce', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_dawn', 'Dawn', 'veh_auto_br_rolls_royce', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_cullinan', 'Cullinan', 'veh_auto_br_rolls_royce', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_silver_shadow', 'Silver Shadow', 'veh_auto_br_rolls_royce', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_rolls_royce_spectre', 'Spectre', 'veh_auto_br_rolls_royce', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_bentley', 'Bentley', 'veh_automobile', 'brand', 26);
SELECT public._seed_car_node('veh_auto_br_bentley_continental_gt', 'Continental GT', 'veh_auto_br_bentley', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_bentley_flying_spur', 'Flying Spur', 'veh_auto_br_bentley', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_bentley_bentayga', 'Bentayga', 'veh_auto_br_bentley', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_bentley_mulsanne', 'Mulsanne', 'veh_auto_br_bentley', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_bentley_arnage', 'Arnage', 'veh_auto_br_bentley', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_bentley_azure', 'Azure', 'veh_auto_br_bentley', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_aston_martin', 'Aston Martin', 'veh_automobile', 'brand', 27);
SELECT public._seed_car_node('veh_auto_br_aston_martin_db9', 'DB9', 'veh_auto_br_aston_martin', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_aston_martin_db11', 'DB11', 'veh_auto_br_aston_martin', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_aston_martin_vantage', 'Vantage', 'veh_auto_br_aston_martin', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_aston_martin_dbs', 'DBS', 'veh_auto_br_aston_martin', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_aston_martin_rapide', 'Rapide', 'veh_auto_br_aston_martin', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_aston_martin_dbx', 'DBX', 'veh_auto_br_aston_martin', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_aston_martin_vanquish', 'Vanquish', 'veh_auto_br_aston_martin', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_mclaren', 'McLaren', 'veh_automobile', 'brand', 28);
SELECT public._seed_car_node('veh_auto_br_mclaren_720s', '720S', 'veh_auto_br_mclaren', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mclaren_570s', '570S', 'veh_auto_br_mclaren', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mclaren_650s', '650S', 'veh_auto_br_mclaren', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mclaren_gt', 'GT', 'veh_auto_br_mclaren', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_mclaren_p1', 'P1', 'veh_auto_br_mclaren', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_mclaren_675lt', '675LT', 'veh_auto_br_mclaren', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_bugatti', 'Bugatti', 'veh_automobile', 'brand', 29);
SELECT public._seed_car_node('veh_auto_br_bugatti_chiron', 'Chiron', 'veh_auto_br_bugatti', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_bugatti_veyron', 'Veyron', 'veh_auto_br_bugatti', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_renault', 'Renault', 'veh_automobile', 'brand', 30);
SELECT public._seed_car_node('veh_auto_br_renault_megane', 'Megane', 'veh_auto_br_renault', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_renault_clio', 'Clio', 'veh_auto_br_renault', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_renault_duster', 'Duster', 'veh_auto_br_renault', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_renault_koleos', 'Koleos', 'veh_auto_br_renault', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_renault_symbol', 'Symbol', 'veh_auto_br_renault', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_renault_logan', 'Logan', 'veh_auto_br_renault', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_renault_sandero', 'Sandero', 'veh_auto_br_renault', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_renault_captur', 'Captur', 'veh_auto_br_renault', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_renault_fluence', 'Fluence', 'veh_auto_br_renault', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_renault_talisman', 'Talisman', 'veh_auto_br_renault', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_renault_arkana', 'Arkana', 'veh_auto_br_renault', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_renault_zoe', 'Zoe', 'veh_auto_br_renault', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_peugeot', 'Peugeot', 'veh_automobile', 'brand', 31);
SELECT public._seed_car_node('veh_auto_br_peugeot_206', '206', 'veh_auto_br_peugeot', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_peugeot_207', '207', 'veh_auto_br_peugeot', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_peugeot_208', '208', 'veh_auto_br_peugeot', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_peugeot_301', '301', 'veh_auto_br_peugeot', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_peugeot_307', '307', 'veh_auto_br_peugeot', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_peugeot_308', '308', 'veh_auto_br_peugeot', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_peugeot_3008', '3008', 'veh_auto_br_peugeot', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_peugeot_5008', '5008', 'veh_auto_br_peugeot', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_peugeot_2008', '2008', 'veh_auto_br_peugeot', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_peugeot_408', '408', 'veh_auto_br_peugeot', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_peugeot_607', '607', 'veh_auto_br_peugeot', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_peugeot_rcz', 'RCZ', 'veh_auto_br_peugeot', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_citroen', 'Citroen', 'veh_automobile', 'brand', 32);
SELECT public._seed_car_node('veh_auto_br_citroen_c2', 'C2', 'veh_auto_br_citroen', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_citroen_c3', 'C3', 'veh_auto_br_citroen', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_citroen_c4', 'C4', 'veh_auto_br_citroen', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_citroen_c5', 'C5', 'veh_auto_br_citroen', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_citroen_c8', 'C8', 'veh_auto_br_citroen', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_citroen_ds3', 'DS3', 'veh_auto_br_citroen', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_citroen_ds4', 'DS4', 'veh_auto_br_citroen', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_citroen_ds5', 'DS5', 'veh_auto_br_citroen', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_citroen_saxo', 'Saxo', 'veh_auto_br_citroen', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_fiat', 'Fiat', 'veh_automobile', 'brand', 33);
SELECT public._seed_car_node('veh_auto_br_fiat_500', '500', 'veh_auto_br_fiat', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_fiat_punto', 'Punto', 'veh_auto_br_fiat', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_fiat_bravo', 'Bravo', 'veh_auto_br_fiat', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_fiat_linea', 'Linea', 'veh_auto_br_fiat', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_fiat_ducato', 'Ducato', 'veh_auto_br_fiat', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_fiat_tipo', 'Tipo', 'veh_auto_br_fiat', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_fiat_egea', 'Egea', 'veh_auto_br_fiat', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo', 'Alfa Romeo', 'veh_automobile', 'brand', 34);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_147', '147', 'veh_auto_br_alfa_romeo', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_156', '156', 'veh_auto_br_alfa_romeo', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_159', '159', 'veh_auto_br_alfa_romeo', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_166', '166', 'veh_auto_br_alfa_romeo', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_giulia', 'Giulia', 'veh_auto_br_alfa_romeo', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_giulietta', 'Giulietta', 'veh_auto_br_alfa_romeo', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_stelvio', 'Stelvio', 'veh_auto_br_alfa_romeo', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_mito', 'Mito', 'veh_auto_br_alfa_romeo', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_alfa_romeo_brera', 'Brera', 'veh_auto_br_alfa_romeo', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_seat', 'Seat', 'veh_automobile', 'brand', 35);
SELECT public._seed_car_node('veh_auto_br_seat_leon', 'Leon', 'veh_auto_br_seat', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_seat_altea', 'Altea', 'veh_auto_br_seat', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_seat_toledo', 'Toledo', 'veh_auto_br_seat', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_seat_cordoba', 'Cordoba', 'veh_auto_br_seat', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_seat_cupra_formentor', 'Cupra Formentor', 'veh_auto_br_seat', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_skoda', 'Skoda', 'veh_automobile', 'brand', 36);
SELECT public._seed_car_node('veh_auto_br_skoda_octavia', 'Octavia', 'veh_auto_br_skoda', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_skoda_fabia', 'Fabia', 'veh_auto_br_skoda', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_skoda_superb', 'Superb', 'veh_auto_br_skoda', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_skoda_kodiaq', 'Kodiaq', 'veh_auto_br_skoda', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_skoda_yeti', 'Yeti', 'veh_auto_br_skoda', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_skoda_rapid', 'Rapid', 'veh_auto_br_skoda', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_skoda_roomster', 'Roomster', 'veh_auto_br_skoda', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_mazda', 'Mazda', 'veh_automobile', 'brand', 37);
SELECT public._seed_car_node('veh_auto_br_mazda_2', '2', 'veh_auto_br_mazda', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mazda_3', '3', 'veh_auto_br_mazda', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mazda_6', '6', 'veh_auto_br_mazda', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mazda_cx_3', 'CX-3', 'veh_auto_br_mazda', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_mazda_cx_5', 'CX-5', 'veh_auto_br_mazda', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_mazda_cx_7', 'CX-7', 'veh_auto_br_mazda', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_mazda_cx_9', 'CX-9', 'veh_auto_br_mazda', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_mazda_cx_30', 'CX-30', 'veh_auto_br_mazda', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_mazda_cx_50', 'CX-50', 'veh_auto_br_mazda', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_mazda_mx_5', 'MX-5', 'veh_auto_br_mazda', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_mazda_bt_50', 'BT-50', 'veh_auto_br_mazda', 'model', 11);
SELECT public._seed_car_node('veh_auto_br_mazda_323', '323', 'veh_auto_br_mazda', 'model', 12);
SELECT public._seed_car_node('veh_auto_br_mazda_626', '626', 'veh_auto_br_mazda', 'model', 13);
SELECT public._seed_car_node('veh_auto_br_mazda_mx_30', 'MX-30', 'veh_auto_br_mazda', 'model', 14);
SELECT public._seed_car_node('veh_auto_br_subaru', 'Subaru', 'veh_automobile', 'brand', 38);
SELECT public._seed_car_node('veh_auto_br_subaru_impreza', 'Impreza', 'veh_auto_br_subaru', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_subaru_forester', 'Forester', 'veh_auto_br_subaru', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_subaru_outback', 'Outback', 'veh_auto_br_subaru', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_subaru_legacy', 'Legacy', 'veh_auto_br_subaru', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_subaru_xv', 'XV', 'veh_auto_br_subaru', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_subaru_brz', 'BRZ', 'veh_auto_br_subaru', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_subaru_wrx', 'WRX', 'veh_auto_br_subaru', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_subaru_crosstrek', 'Crosstrek', 'veh_auto_br_subaru', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_suzuki', 'Suzuki', 'veh_automobile', 'brand', 39);
SELECT public._seed_car_node('veh_auto_br_suzuki_swift', 'Swift', 'veh_auto_br_suzuki', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_suzuki_vitara', 'Vitara', 'veh_auto_br_suzuki', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_suzuki_jimny', 'Jimny', 'veh_auto_br_suzuki', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_suzuki_baleno', 'Baleno', 'veh_auto_br_suzuki', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_suzuki_ciaz', 'Ciaz', 'veh_auto_br_suzuki', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_suzuki_ertiga', 'Ertiga', 'veh_auto_br_suzuki', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_suzuki_grand_vitara', 'Grand Vitara', 'veh_auto_br_suzuki', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_suzuki_sx4', 'SX4', 'veh_auto_br_suzuki', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_suzuki_alto', 'Alto', 'veh_auto_br_suzuki', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_suzuki_celerio', 'Celerio', 'veh_auto_br_suzuki', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_isuzu', 'Isuzu', 'veh_automobile', 'brand', 40);
SELECT public._seed_car_node('veh_auto_br_isuzu_d_max', 'D-Max', 'veh_auto_br_isuzu', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_isuzu_mu_x', 'MU-X', 'veh_auto_br_isuzu', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_isuzu_trooper', 'Trooper', 'veh_auto_br_isuzu', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_isuzu_rodeo', 'Rodeo', 'veh_auto_br_isuzu', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_infiniti', 'Infiniti', 'veh_automobile', 'brand', 41);
SELECT public._seed_car_node('veh_auto_br_infiniti_q50', 'Q50', 'veh_auto_br_infiniti', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_infiniti_q60', 'Q60', 'veh_auto_br_infiniti', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_infiniti_q70', 'Q70', 'veh_auto_br_infiniti', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_infiniti_qx50', 'QX50', 'veh_auto_br_infiniti', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_infiniti_qx56', 'QX56', 'veh_auto_br_infiniti', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_infiniti_qx60', 'QX60', 'veh_auto_br_infiniti', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_infiniti_qx70', 'QX70', 'veh_auto_br_infiniti', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_infiniti_qx80', 'QX80', 'veh_auto_br_infiniti', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_infiniti_g35', 'G35', 'veh_auto_br_infiniti', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_infiniti_g37', 'G37', 'veh_auto_br_infiniti', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_acura', 'Acura', 'veh_automobile', 'brand', 42);
SELECT public._seed_car_node('veh_auto_br_acura_mdx', 'MDX', 'veh_auto_br_acura', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_acura_rdx', 'RDX', 'veh_auto_br_acura', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_acura_tlx', 'TLX', 'veh_auto_br_acura', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_acura_nsx', 'NSX', 'veh_auto_br_acura', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_acura_integra', 'Integra', 'veh_auto_br_acura', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_acura_ilx', 'ILX', 'veh_auto_br_acura', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_genesis', 'Genesis', 'veh_automobile', 'brand', 43);
SELECT public._seed_car_node('veh_auto_br_genesis_g70', 'G70', 'veh_auto_br_genesis', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_genesis_g80', 'G80', 'veh_auto_br_genesis', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_genesis_g90', 'G90', 'veh_auto_br_genesis', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_genesis_gv60', 'GV60', 'veh_auto_br_genesis', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_genesis_gv70', 'GV70', 'veh_auto_br_genesis', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_genesis_gv80', 'GV80', 'veh_auto_br_genesis', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_lincoln', 'Lincoln', 'veh_automobile', 'brand', 44);
SELECT public._seed_car_node('veh_auto_br_lincoln_navigator', 'Navigator', 'veh_auto_br_lincoln', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_lincoln_continental', 'Continental', 'veh_auto_br_lincoln', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_lincoln_mkz', 'MKZ', 'veh_auto_br_lincoln', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_lincoln_mkx', 'MKX', 'veh_auto_br_lincoln', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_lincoln_aviator', 'Aviator', 'veh_auto_br_lincoln', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_lincoln_nautilus', 'Nautilus', 'veh_auto_br_lincoln', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_mercury', 'Mercury', 'veh_automobile', 'brand', 45);
SELECT public._seed_car_node('veh_auto_br_mercury_mariner', 'Mariner', 'veh_auto_br_mercury', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mercury_grand_marquis', 'Grand Marquis', 'veh_auto_br_mercury', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mercury_milan', 'Milan', 'veh_auto_br_mercury', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mercury_mountaineer', 'Mountaineer', 'veh_auto_br_mercury', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_opel', 'Opel', 'veh_automobile', 'brand', 46);
SELECT public._seed_car_node('veh_auto_br_opel_astra', 'Astra', 'veh_auto_br_opel', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_opel_corsa', 'Corsa', 'veh_auto_br_opel', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_opel_meriva', 'Meriva', 'veh_auto_br_opel', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_opel_zafira', 'Zafira', 'veh_auto_br_opel', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_opel_insignia', 'Insignia', 'veh_auto_br_opel', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_opel_mokka', 'Mokka', 'veh_auto_br_opel', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_opel_vectra', 'Vectra', 'veh_auto_br_opel', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_opel_antara', 'Antara', 'veh_auto_br_opel', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_opel_grandland_x', 'Grandland X', 'veh_auto_br_opel', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_opel_omega', 'Omega', 'veh_auto_br_opel', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_saab', 'Saab', 'veh_automobile', 'brand', 47);
SELECT public._seed_car_node('veh_auto_br_saab_9_5', '9-5', 'veh_auto_br_saab', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_saab_9_7x', '9-7X', 'veh_auto_br_saab', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_daewoo', 'Daewoo', 'veh_automobile', 'brand', 48);
SELECT public._seed_car_node('veh_auto_br_daewoo_lanos', 'Lanos', 'veh_auto_br_daewoo', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_daewoo_leganza', 'Leganza', 'veh_auto_br_daewoo', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_daewoo_nubira', 'Nubira', 'veh_auto_br_daewoo', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_daewoo_lacetti', 'Lacetti', 'veh_auto_br_daewoo', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_daewoo_espero', 'Espero', 'veh_auto_br_daewoo', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_daewoo_magnus', 'Magnus', 'veh_auto_br_daewoo', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_daewoo_cielo', 'Cielo', 'veh_auto_br_daewoo', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_daewoo_gentra', 'Gentra', 'veh_auto_br_daewoo', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_daewoo_kalos', 'Kalos', 'veh_auto_br_daewoo', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_daewoo_tosca', 'Tosca', 'veh_auto_br_daewoo', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_chery', 'Chery', 'veh_automobile', 'brand', 49);
SELECT public._seed_car_node('veh_auto_br_chery_tiggo_2', 'Tiggo 2', 'veh_auto_br_chery', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_chery_tiggo_3', 'Tiggo 3', 'veh_auto_br_chery', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_chery_tiggo_4', 'Tiggo 4', 'veh_auto_br_chery', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_chery_tiggo_5', 'Tiggo 5', 'veh_auto_br_chery', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_chery_tiggo_7', 'Tiggo 7', 'veh_auto_br_chery', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_chery_tiggo_8', 'Tiggo 8', 'veh_auto_br_chery', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_chery_arrizo_3', 'Arrizo 3', 'veh_auto_br_chery', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_chery_arrizo_6', 'Arrizo 6', 'veh_auto_br_chery', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_chery_arrizo_7', 'Arrizo 7', 'veh_auto_br_chery', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_chery_arrizo_8', 'Arrizo 8', 'veh_auto_br_chery', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_changan', 'Changan', 'veh_automobile', 'brand', 50);
SELECT public._seed_car_node('veh_auto_br_changan_alsvin', 'Alsvin', 'veh_auto_br_changan', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_changan_cs35', 'CS35', 'veh_auto_br_changan', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_changan_cs75', 'CS75', 'veh_auto_br_changan', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_changan_cs95', 'CS95', 'veh_auto_br_changan', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_changan_eado', 'Eado', 'veh_auto_br_changan', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_changan_hunter', 'Hunter', 'veh_auto_br_changan', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_changan_uni_k', 'UNI-K', 'veh_auto_br_changan', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_changan_uni_t', 'UNI-T', 'veh_auto_br_changan', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_haval', 'Haval', 'veh_automobile', 'brand', 51);
SELECT public._seed_car_node('veh_auto_br_haval_h6', 'H6', 'veh_auto_br_haval', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_haval_h7', 'H7', 'veh_auto_br_haval', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_haval_h9', 'H9', 'veh_auto_br_haval', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_haval_jolion', 'JOLION', 'veh_auto_br_haval', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_haval_dargo', 'DARGO', 'veh_auto_br_haval', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_haval_h2', 'H2', 'veh_auto_br_haval', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_mg', 'MG', 'veh_automobile', 'brand', 52);
SELECT public._seed_car_node('veh_auto_br_mg_3', '3', 'veh_auto_br_mg', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mg_5', '5', 'veh_auto_br_mg', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mg_6', '6', 'veh_auto_br_mg', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mg_7', '7', 'veh_auto_br_mg', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_mg_zs', 'ZS', 'veh_auto_br_mg', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_mg_hs', 'HS', 'veh_auto_br_mg', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_mg_rx5', 'RX5', 'veh_auto_br_mg', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_mg_rx8', 'RX8', 'veh_auto_br_mg', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_mg_gt', 'GT', 'veh_auto_br_mg', 'model', 9);
SELECT public._seed_car_node('veh_auto_br_mg_mg4_ev', 'MG4 EV', 'veh_auto_br_mg', 'model', 10);
SELECT public._seed_car_node('veh_auto_br_byd', 'BYD', 'veh_automobile', 'brand', 53);
SELECT public._seed_car_node('veh_auto_br_byd_dolphin', 'Dolphin', 'veh_auto_br_byd', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_byd_han', 'Han', 'veh_auto_br_byd', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_byd_seal', 'Seal', 'veh_auto_br_byd', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_byd_f3', 'F3', 'veh_auto_br_byd', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_gac', 'GAC', 'veh_automobile', 'brand', 54);
SELECT public._seed_car_node('veh_auto_br_gac_gs3', 'GS3', 'veh_auto_br_gac', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_gac_gs4', 'GS4', 'veh_auto_br_gac', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_gac_gs5', 'GS5', 'veh_auto_br_gac', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_gac_gs7', 'GS7', 'veh_auto_br_gac', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_gac_gs8', 'GS8', 'veh_auto_br_gac', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_gac_empow', 'Empow', 'veh_auto_br_gac', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_gac_emkoo', 'EMKOO', 'veh_auto_br_gac', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_gac_aion_es', 'Aion ES', 'veh_auto_br_gac', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_jac', 'JAC', 'veh_automobile', 'brand', 55);
SELECT public._seed_car_node('veh_auto_br_jac_js3', 'JS3', 'veh_auto_br_jac', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_jac_js4', 'JS4', 'veh_auto_br_jac', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_jac_js6', 'JS6', 'veh_auto_br_jac', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_jac_j4', 'J4', 'veh_auto_br_jac', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_jac_j5', 'J5', 'veh_auto_br_jac', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_jac_j6', 'J6', 'veh_auto_br_jac', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_jac_j7', 'J7', 'veh_auto_br_jac', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_jac_t8', 'T8', 'veh_auto_br_jac', 'model', 8);
SELECT public._seed_car_node('veh_auto_br_geely', 'Geely', 'veh_automobile', 'brand', 56);
SELECT public._seed_car_node('veh_auto_br_geely_echo', 'Echo', 'veh_auto_br_geely', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_geely_emgrand', 'Emgrand', 'veh_auto_br_geely', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_geely_familia', 'Familia', 'veh_auto_br_geely', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_geely_fc', 'FC', 'veh_auto_br_geely', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_great_wall', 'Great Wall', 'veh_automobile', 'brand', 57);
SELECT public._seed_car_node('veh_auto_br_great_wall_wingle', 'Wingle', 'veh_auto_br_great_wall', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_great_wall_haval_h5', 'Haval H5', 'veh_auto_br_great_wall', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_great_wall_hover', 'Hover', 'veh_auto_br_great_wall', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_brilliance', 'Brilliance', 'veh_automobile', 'brand', 58);
SELECT public._seed_car_node('veh_auto_br_brilliance_fsv', 'FSV', 'veh_auto_br_brilliance', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_brilliance_h530', 'H530', 'veh_auto_br_brilliance', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_brilliance_v5', 'V5', 'veh_auto_br_brilliance', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_brilliance_frv', 'FRV', 'veh_auto_br_brilliance', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_baic', 'BAIC', 'veh_automobile', 'brand', 59);
SELECT public._seed_car_node('veh_auto_br_baic_bj40', 'BJ40', 'veh_auto_br_baic', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_baic_bj80', 'BJ80', 'veh_auto_br_baic', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_baic_x25', 'X25', 'veh_auto_br_baic', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_baic_x35', 'X35', 'veh_auto_br_baic', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_baic_senova', 'Senova', 'veh_auto_br_baic', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_dongfeng', 'Dongfeng', 'veh_automobile', 'brand', 60);
SELECT public._seed_car_node('veh_auto_br_dongfeng_ax7', 'AX7', 'veh_auto_br_dongfeng', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_dongfeng_s30', 'S30', 'veh_auto_br_dongfeng', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_dongfeng_h30', 'H30', 'veh_auto_br_dongfeng', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_dongfeng_aeolus', 'Aeolus', 'veh_auto_br_dongfeng', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_faw', 'FAW', 'veh_automobile', 'brand', 61);
SELECT public._seed_car_node('veh_auto_br_faw_besturn_b30', 'Besturn B30', 'veh_auto_br_faw', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_faw_besturn_x40', 'Besturn X40', 'veh_auto_br_faw', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_faw_besturn_x80', 'Besturn X80', 'veh_auto_br_faw', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_foton', 'Foton', 'veh_automobile', 'brand', 62);
SELECT public._seed_car_node('veh_auto_br_foton_tunland', 'Tunland', 'veh_auto_br_foton', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_foton_view', 'View', 'veh_auto_br_foton', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_maxus', 'Maxus', 'veh_automobile', 'brand', 63);
SELECT public._seed_car_node('veh_auto_br_maxus_t60', 'T60', 'veh_auto_br_maxus', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_maxus_v80', 'V80', 'veh_auto_br_maxus', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_maxus_d60', 'D60', 'veh_auto_br_maxus', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_maxus_d90', 'D90', 'veh_auto_br_maxus', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_lifan', 'Lifan', 'veh_automobile', 'brand', 64);
SELECT public._seed_car_node('veh_auto_br_lifan_320', '320', 'veh_auto_br_lifan', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_lifan_520', '520', 'veh_auto_br_lifan', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_lifan_620', '620', 'veh_auto_br_lifan', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_lifan_x50', 'X50', 'veh_auto_br_lifan', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_lifan_x60', 'X60', 'veh_auto_br_lifan', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_saipa', 'Saipa', 'veh_automobile', 'brand', 65);
SELECT public._seed_car_node('veh_auto_br_saipa_tiba', 'Tiba', 'veh_auto_br_saipa', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_saipa_131', '131', 'veh_auto_br_saipa', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_saipa_132', '132', 'veh_auto_br_saipa', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_saipa_141', '141', 'veh_auto_br_saipa', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_saipa_saina', 'Saina', 'veh_auto_br_saipa', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_iran_khodro', 'Iran Khodro', 'veh_automobile', 'brand', 66);
SELECT public._seed_car_node('veh_auto_br_iran_khodro_samand', 'Samand', 'veh_auto_br_iran_khodro', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_iran_khodro_dena', 'Dena', 'veh_auto_br_iran_khodro', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_iran_khodro_soren', 'Soren', 'veh_auto_br_iran_khodro', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_iran_khodro_runna', 'Runna', 'veh_auto_br_iran_khodro', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_iran_khodro_tara', 'Tara', 'veh_auto_br_iran_khodro', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_hummer', 'Hummer', 'veh_automobile', 'brand', 67);
SELECT public._seed_car_node('veh_auto_br_hummer_h2', 'H2', 'veh_auto_br_hummer', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_hummer_h3', 'H3', 'veh_auto_br_hummer', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_jaguar', 'Jaguar', 'veh_automobile', 'brand', 68);
SELECT public._seed_car_node('veh_auto_br_jaguar_xe', 'XE', 'veh_auto_br_jaguar', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_jaguar_xf', 'XF', 'veh_auto_br_jaguar', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_jaguar_xj', 'XJ', 'veh_auto_br_jaguar', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_jaguar_f_type', 'F-Type', 'veh_auto_br_jaguar', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_jaguar_s_type', 'S-Type', 'veh_auto_br_jaguar', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_jaguar_x_type', 'X-Type', 'veh_auto_br_jaguar', 'model', 6);
SELECT public._seed_car_node('veh_auto_br_jaguar_xk8', 'XK8', 'veh_auto_br_jaguar', 'model', 7);
SELECT public._seed_car_node('veh_auto_br_daihatsu', 'Daihatsu', 'veh_automobile', 'brand', 69);
SELECT public._seed_car_node('veh_auto_br_daihatsu_charade', 'Charade', 'veh_auto_br_daihatsu', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_daihatsu_terios', 'Terios', 'veh_auto_br_daihatsu', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_daihatsu_sirion', 'Sirion', 'veh_auto_br_daihatsu', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_daihatsu_feroza', 'Feroza', 'veh_auto_br_daihatsu', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_ssangyong', 'SsangYong', 'veh_automobile', 'brand', 70);
SELECT public._seed_car_node('veh_auto_br_ssangyong_rexton', 'Rexton', 'veh_auto_br_ssangyong', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_ssangyong_tivoli', 'Tivoli', 'veh_auto_br_ssangyong', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_ssangyong_korando', 'Korando', 'veh_auto_br_ssangyong', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_ssangyong_musso', 'Musso', 'veh_auto_br_ssangyong', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_ssangyong_torres', 'Torres', 'veh_auto_br_ssangyong', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_mini', 'Mini', 'veh_automobile', 'brand', 71);
SELECT public._seed_car_node('veh_auto_br_mini_cooper', 'Cooper', 'veh_auto_br_mini', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_mini_clubman', 'Clubman', 'veh_auto_br_mini', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_mini_countryman', 'Countryman', 'veh_auto_br_mini', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_mini_paceman', 'Paceman', 'veh_auto_br_mini', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_pontiac', 'Pontiac', 'veh_automobile', 'brand', 72);
SELECT public._seed_car_node('veh_auto_br_pontiac_grand_am', 'Grand Am', 'veh_auto_br_pontiac', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_pontiac_grand_prix', 'Grand Prix', 'veh_auto_br_pontiac', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_pontiac_torrent', 'Torrent', 'veh_auto_br_pontiac', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_pontiac_montana', 'Montana', 'veh_auto_br_pontiac', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_pontiac_vibe', 'Vibe', 'veh_auto_br_pontiac', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_buick', 'Buick', 'veh_automobile', 'brand', 73);
SELECT public._seed_car_node('veh_auto_br_buick_encore', 'Encore', 'veh_auto_br_buick', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_buick_enclave', 'Enclave', 'veh_auto_br_buick', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_buick_regal', 'Regal', 'veh_auto_br_buick', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_buick_lacrosse', 'LaCrosse', 'veh_auto_br_buick', 'model', 4);
SELECT public._seed_car_node('veh_auto_br_buick_electra', 'Electra', 'veh_auto_br_buick', 'model', 5);
SELECT public._seed_car_node('veh_auto_br_oldsmobile', 'Oldsmobile', 'veh_automobile', 'brand', 74);
SELECT public._seed_car_node('veh_auto_br_oldsmobile_delta_88', 'Delta 88', 'veh_auto_br_oldsmobile', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_oldsmobile_silhouette', 'Silhouette', 'veh_auto_br_oldsmobile', 'model', 2);
SELECT public._seed_car_node('veh_auto_br_oldsmobile_cutlass', 'Cutlass', 'veh_auto_br_oldsmobile', 'model', 3);
SELECT public._seed_car_node('veh_auto_br_scion', 'Scion', 'veh_automobile', 'brand', 75);
SELECT public._seed_car_node('veh_auto_br_scion_tc', 'tC', 'veh_auto_br_scion', 'model', 1);
SELECT public._seed_car_node('veh_auto_br_scion_iq', 'iQ', 'veh_auto_br_scion', 'model', 2);
SELECT public._seed_car_node('veh_suv_br_toyota', 'Toyota', 'veh_suv_pickup', 'brand', 1);
SELECT public._seed_car_node('veh_suv_br_toyota_land_cruiser', 'Land Cruiser', 'veh_suv_br_toyota', 'model', 1);
SELECT public._seed_car_node('veh_suv_br_toyota_land_cruiser_prado', 'Land Cruiser Prado', 'veh_suv_br_toyota', 'model', 2);
SELECT public._seed_car_node('veh_suv_br_toyota_4runner', '4Runner', 'veh_suv_br_toyota', 'model', 3);
SELECT public._seed_car_node('veh_suv_br_toyota_sequoia', 'Sequoia', 'veh_suv_br_toyota', 'model', 4);
SELECT public._seed_car_node('veh_suv_br_toyota_rav4', 'RAV4', 'veh_suv_br_toyota', 'model', 5);
SELECT public._seed_car_node('veh_suv_br_toyota_highlander', 'Highlander', 'veh_suv_br_toyota', 'model', 6);
SELECT public._seed_car_node('veh_suv_br_toyota_fj_cruiser', 'FJ Cruiser', 'veh_suv_br_toyota', 'model', 7);
SELECT public._seed_car_node('veh_suv_br_land_rover', 'Land Rover', 'veh_suv_pickup', 'brand', 2);
SELECT public._seed_car_node('veh_suv_br_land_rover_range_rover', 'Range Rover', 'veh_suv_br_land_rover', 'model', 1);
SELECT public._seed_car_node('veh_suv_br_land_rover_range_rover_sport', 'Range Rover Sport', 'veh_suv_br_land_rover', 'model', 2);
SELECT public._seed_car_node('veh_suv_br_land_rover_range_rover_vogue', 'Range Rover Vogue', 'veh_suv_br_land_rover', 'model', 3);
SELECT public._seed_car_node('veh_suv_br_land_rover_defender', 'Defender', 'veh_suv_br_land_rover', 'model', 4);
SELECT public._seed_car_node('veh_suv_br_land_rover_discovery', 'Discovery', 'veh_suv_br_land_rover', 'model', 5);
SELECT public._seed_car_node('veh_suv_br_land_rover_freelander', 'Freelander', 'veh_suv_br_land_rover', 'model', 6);
SELECT public._seed_car_node('veh_suv_br_land_rover_evoque', 'Evoque', 'veh_suv_br_land_rover', 'model', 7);
SELECT public._seed_car_node('veh_suv_br_land_rover_velar', 'Velar', 'veh_suv_br_land_rover', 'model', 8);
SELECT public._seed_car_node('veh_suv_br_land_rover_lr2', 'LR2', 'veh_suv_br_land_rover', 'model', 9);
SELECT public._seed_car_node('veh_suv_br_land_rover_lr3', 'LR3', 'veh_suv_br_land_rover', 'model', 10);
SELECT public._seed_car_node('veh_suv_br_land_rover_lr4', 'LR4', 'veh_suv_br_land_rover', 'model', 11);
SELECT public._seed_car_node('veh_suv_br_jeep', 'Jeep', 'veh_suv_pickup', 'brand', 3);
SELECT public._seed_car_node('veh_suv_br_jeep_grand_cherokee', 'Grand Cherokee', 'veh_suv_br_jeep', 'model', 1);
SELECT public._seed_car_node('veh_suv_br_jeep_wrangler', 'Wrangler', 'veh_suv_br_jeep', 'model', 2);
SELECT public._seed_car_node('veh_suv_br_jeep_cherokee', 'Cherokee', 'veh_suv_br_jeep', 'model', 3);
SELECT public._seed_car_node('veh_suv_br_jeep_compass', 'Compass', 'veh_suv_br_jeep', 'model', 4);
SELECT public._seed_car_node('veh_suv_br_jeep_commander', 'Commander', 'veh_suv_br_jeep', 'model', 5);
SELECT public._seed_car_node('veh_suv_br_jeep_gladiator', 'Gladiator', 'veh_suv_br_jeep', 'model', 6);
SELECT public._seed_car_node('veh_suv_br_jeep_renegade', 'Renegade', 'veh_suv_br_jeep', 'model', 7);
SELECT public._seed_car_node('veh_suv_br_jeep_wagoneer', 'Wagoneer', 'veh_suv_br_jeep', 'model', 8);
SELECT public._seed_car_node('veh_suv_br_jeep_grand_wagoneer', 'Grand Wagoneer', 'veh_suv_br_jeep', 'model', 9);
SELECT public._seed_car_node('veh_suv_br_lexus', 'Lexus', 'veh_suv_pickup', 'brand', 4);
SELECT public._seed_car_node('veh_suv_br_lexus_lx', 'LX', 'veh_suv_br_lexus', 'model', 1);
SELECT public._seed_car_node('veh_suv_br_lexus_gx', 'GX', 'veh_suv_br_lexus', 'model', 2);
SELECT public._seed_car_node('veh_suv_br_lexus_rx', 'RX', 'veh_suv_br_lexus', 'model', 3);
SELECT public._seed_car_node('veh_ev_br_tesla', 'Tesla', 'veh_electric', 'brand', 1);
SELECT public._seed_car_node('veh_ev_br_tesla_model_3', 'Model 3', 'veh_ev_br_tesla', 'model', 1);
SELECT public._seed_car_node('veh_ev_br_tesla_model_s', 'Model S', 'veh_ev_br_tesla', 'model', 2);
SELECT public._seed_car_node('veh_ev_br_tesla_model_x', 'Model X', 'veh_ev_br_tesla', 'model', 3);
SELECT public._seed_car_node('veh_ev_br_tesla_model_y', 'Model Y', 'veh_ev_br_tesla', 'model', 4);
SELECT public._seed_car_node('veh_ev_br_tesla_cybertruck', 'Cybertruck', 'veh_ev_br_tesla', 'model', 5);
SELECT public._seed_car_node('veh_ev_br_bmw', 'BMW', 'veh_electric', 'brand', 2);
SELECT public._seed_car_node('veh_ev_br_bmw_i3', 'i3', 'veh_ev_br_bmw', 'model', 1);
SELECT public._seed_car_node('veh_ev_br_bmw_i4', 'i4', 'veh_ev_br_bmw', 'model', 2);
SELECT public._seed_car_node('veh_ev_br_bmw_i5', 'i5', 'veh_ev_br_bmw', 'model', 3);
SELECT public._seed_car_node('veh_ev_br_bmw_ix', 'iX', 'veh_ev_br_bmw', 'model', 4);
SELECT public._seed_car_node('veh_ev_br_bmw_ix1', 'iX1', 'veh_ev_br_bmw', 'model', 5);
SELECT public._seed_car_node('veh_ev_br_bmw_ix3', 'iX3', 'veh_ev_br_bmw', 'model', 6);
SELECT public._seed_car_node('veh_ev_br_audi', 'Audi', 'veh_electric', 'brand', 3);
SELECT public._seed_car_node('veh_ev_br_audi_q4_e_tron', 'Q4 e-tron', 'veh_ev_br_audi', 'model', 1);
SELECT public._seed_car_node('veh_ev_br_mercedes_benz', 'Mercedes-Benz', 'veh_electric', 'brand', 4);
SELECT public._seed_car_node('veh_ev_br_mercedes_benz_eqe', 'EQE', 'veh_ev_br_mercedes_benz', 'model', 1);
SELECT public._seed_car_node('veh_ev_br_mercedes_benz_eqs', 'EQS', 'veh_ev_br_mercedes_benz', 'model', 2);
SELECT public._seed_car_node('veh_comm_br_iveco', 'IVECO', 'veh_commercial', 'brand', 1);
SELECT public._seed_car_node('veh_comm_br_iveco_daily', 'Daily', 'veh_comm_br_iveco', 'model', 1);
SELECT public._seed_car_node('veh_comm_br_hino', 'Hino', 'veh_commercial', 'brand', 2);
SELECT public._seed_car_node('veh_comm_br_hino_300', '300', 'veh_comm_br_hino', 'model', 1);
SELECT public._seed_car_node('veh_comm_br_king_long', 'King Long', 'veh_commercial', 'brand', 3);
SELECT public._seed_car_node('veh_comm_br_king_long_king_long', 'King Long', 'veh_comm_br_king_long', 'model', 1);
SELECT public._seed_car_node('veh_comm_br_jinbei', 'Jinbei', 'veh_commercial', 'brand', 4);
SELECT public._seed_car_node('veh_comm_br_jinbei_haise', 'Haise', 'veh_comm_br_jinbei', 'model', 1);
DROP FUNCTION public._seed_car_node(TEXT, TEXT, TEXT, TEXT, INT);
