-- Seed localized descriptions for subcategories missing description_en (Home Help, Electronics, Pets).
-- Safe to re-run: overwrites description columns for listed slugs only.

UPDATE public.categories SET description_ar = 'تنظيف يومي ، تنظيف أسبوعي ، تنظيف عميق ، تنظيف بعد البناء', description_en = 'Daily cleaning, Weekly cleaning, Deep cleaning, Post-construction', description_ku = 'پاککردنەوەی ڕۆژانە، هەفتانە، قووڵ، دوای بیناسازی', description_tr = 'Günlük temizlik, Haftalık temizlik, Derin temizlik, İnşaat sonrası' WHERE slug = 'home_cleaning';
UPDATE public.categories SET description_ar = 'طباخة منزلية ، طبخ مناسبات ، حلويات ، وجبات صحية', description_en = 'Daily home cook, Event catering, Sweets, Healthy meals', description_ku = 'چێشتلێنانی ماڵ، بۆنە، شیرینی، خواردنی تەندروست', description_tr = 'Ev aşçısı, Etkinlik yemeği, Tatlılar, Sağlıklı yemekler' WHERE slug = 'home_cooking';
UPDATE public.categories SET description_ar = 'مربية أطفال ، جليسة بالساعة ، رعاية الرضع ، مساعدة واجبات', description_en = 'Nanny, Hourly babysitter, Infant care, Homework help', description_ku = 'مامانی منداڵ، چاودێری کاتژمێر، نوێزاد، یارمەتی وانە', description_tr = 'Dadı, Saatlik bakıcı, Bebek bakımı, Ödev yardımı' WHERE slug = 'home_childcare';
UPDATE public.categories SET description_ar = 'مرافق كبار السن ، ممرض منزلي ، مساعد شخصي ، فيزيوثيرابي', description_en = 'Elder companion, Home nurse, Patient helper, Physiotherapy', description_ku = 'هاوڕێی پیر، پەرستاری ماڵ، یارمەتیدەری نەخۆش، فیزیۆ', description_tr = 'Yaşlı refakat, Ev hemşiresi, Hasta bakıcı, Fizyoterapi' WHERE slug = 'home_eldercare';
UPDATE public.categories SET description_ar = 'سائق عائلي ، سائق بالساعة ، سائق مدرسي ، سائق لكبار السن', description_en = 'Family driver, Hourly driver, School driver, Senior driver', description_ku = 'شۆفێری خێزان، کاتژمێر، قوتابخانە، پیر', description_tr = 'Aile şoförü, Saatlik şoför, Okul şoförü, Yaşlı şoför' WHERE slug = 'home_driver';
UPDATE public.categories SET description_ar = 'تنسيق حدائق ، قص العشب ، ري النباتات ، تنظيف المسابح', description_en = 'Garden design, Lawn mowing, Plant care, Pool cleaning', description_ku = 'دیزاینی باخ، چەندکردنی گیا، ئاودان، پاککردنەوەی حەوز', description_tr = 'Bahçe düzenleme, Çim biçme, Bitki bakımı, Havuz temizliği' WHERE slug = 'home_gardening';
UPDATE public.categories SET description_ar = 'سباك ، كهربائي ، نجار ، دهان', description_en = 'Plumber, Electrician, Carpenter, Painter', description_ku = 'borîçî، کارەba، necar، boyax', description_tr = 'Tesisatçı, Elektrikçi, Marangoz, Boyacı' WHERE slug = 'home_maintenance';
UPDATE public.categories SET description_ar = 'نقل داخل المدينة ، نقل بين المحافظات ، تغليف وتخزين ، شركة نقل', description_en = 'Local moving, Intercity moving, Packing & storage, Moving company', description_ku = 'گواستنەوەی ناو شار، نێوان پارێزگا، پاکەت، کۆmpaniya', description_tr = 'Şehir içi taşıma, Şehirler arası, Paketleme, Nakliye firması' WHERE slug = 'home_moving';
UPDATE public.categories SET description_ar = 'حارس منزل ، كاميرات ، أنظمة إنذار ، حراسة شخصية', description_en = 'House guard, CCTV, Alarm systems, Personal security', description_ku = 'پاسەوانی ماڵ، کامێra، ئاگادارکردنەوە، ئاسایشی کەسی', description_tr = 'Ev bekçisi, Kamera, Alarm, Özel güvenlik' WHERE slug = 'home_security';
UPDATE public.categories SET description_ar = 'غسيل منزلي ، كي الملابس ، مغسلة بالتوصيل ، تنظيف جاف', description_en = 'Home laundry, Ironing, Pickup laundry, Dry cleaning', description_ku = 'جلوبرگی ماڵ، ئistri، گوastnەوە، پاککردنەوەی وشک', description_tr = 'Evde çamaşır, Ütü, Teslimatlı çamaşır, Kuru temizleme' WHERE slug = 'home_laundry';

UPDATE public.categories SET description_ar = 'Apple, Samsung, Huawei, Lenovo', description_en = 'Apple, Samsung, Huawei, Lenovo', description_ku = 'Apple, Samsung, Huawei, Lenovo', description_tr = 'Apple, Samsung, Huawei, Lenovo' WHERE slug = 'elec_tablets';
UPDATE public.categories SET description_ar = 'Apple, Dell, HP, Lenovo', description_en = 'Apple, Dell, HP, Lenovo', description_ku = 'Apple, Dell, HP, Lenovo', description_tr = 'Apple, Dell, HP, Lenovo' WHERE slug = 'elec_laptops';
UPDATE public.categories SET description_ar = 'Samsung, LG, Sony, TCL', description_en = 'Samsung, LG, Sony, TCL', description_ku = 'Samsung, LG, Sony, TCL', description_tr = 'Samsung, LG, Sony, TCL' WHERE slug = 'elec_displays';
UPDATE public.categories SET description_ar = 'Canon, Nikon, Sony, GoPro', description_en = 'Canon, Nikon, Sony, GoPro', description_ku = 'Canon, Nikon, Sony, GoPro', description_tr = 'Canon, Nikon, Sony, GoPro' WHERE slug = 'elec_cameras';
UPDATE public.categories SET description_ar = 'JBL, Sony, Bose, Apple', description_en = 'JBL, Sony, Bose, Apple', description_ku = 'JBL, Sony, Bose, Apple', description_tr = 'JBL, Sony, Bose, Apple' WHERE slug = 'elec_audio';
UPDATE public.categories SET description_ar = 'PlayStation, Xbox, Nintendo, PC Gaming', description_en = 'PlayStation, Xbox, Nintendo, PC Gaming', description_ku = 'PlayStation, Xbox, Nintendo, PC Gaming', description_tr = 'PlayStation, Xbox, Nintendo, PC Gaming' WHERE slug = 'elec_gaming';
UPDATE public.categories SET description_ar = 'Apple Watch, Samsung, Xiaomi, Fitbit', description_en = 'Apple Watch, Samsung, Xiaomi, Fitbit', description_ku = 'Apple Watch, Samsung, Xiaomi, Fitbit', description_tr = 'Apple Watch, Samsung, Xiaomi, Fitbit' WHERE slug = 'elec_wearables';
UPDATE public.categories SET description_ar = 'HP, Canon, Epson, Brother', description_en = 'HP, Canon, Epson, Brother', description_ku = 'HP, Canon, Epson, Brother', description_tr = 'HP, Canon, Epson, Brother' WHERE slug = 'elec_printers';
UPDATE public.categories SET description_ar = 'TP-Link, Huawei, Netgear, Cisco', description_en = 'TP-Link, Huawei, Netgear, Cisco', description_ku = 'TP-Link, Huawei, Netgear, Cisco', description_tr = 'TP-Link, Huawei, Netgear, Cisco' WHERE slug = 'elec_networking';
UPDATE public.categories SET description_ar = 'Google, Amazon, Xiaomi, Philips Hue', description_en = 'Google, Amazon, Xiaomi, Philips Hue', description_ku = 'Google, Amazon, Xiaomi, Philips Hue', description_tr = 'Google, Amazon, Xiaomi, Philips Hue' WHERE slug = 'elec_smart_home';
UPDATE public.categories SET description_ar = 'Batteries, Chargers, Cables, Cases', description_en = 'Batteries, Chargers, Cables, Cases', description_ku = 'Batteries, Chargers, Cables, Cases', description_tr = 'Piller, Şarj cihazları, Kablolar, Kılıflar' WHERE slug = 'elec_parts';
UPDATE public.categories SET description_ar = 'Samsung, LG, Bosch, Siemens', description_en = 'Samsung, LG, Bosch, Siemens', description_ku = 'Samsung, LG, Bosch, Siemens', description_tr = 'Samsung, LG, Bosch, Siemens' WHERE slug = 'elec_appliances';
UPDATE public.categories SET description_ar = 'Gree, Carrier, LG, Samsung', description_en = 'Gree, Carrier, LG, Samsung', description_ku = 'Gree, Carrier, LG, Samsung', description_tr = 'Gree, Carrier, LG, Samsung' WHERE slug = 'elec_ac';

UPDATE public.categories SET description_ar = 'German Shepherd, Husky, Labrador, Maltese', description_en = 'German Shepherd, Husky, Labrador, Maltese', description_ku = 'German Shepherd, Husky, Labrador, Maltese', description_tr = 'Alman Kurdu, Husky, Labrador, Maltese' WHERE slug = 'pets_dogs';
UPDATE public.categories SET description_ar = 'Persian, Scottish Fold, British, Ragdoll', description_en = 'Persian, Scottish Fold, British, Ragdoll', description_ku = 'Persian, Scottish Fold, British, Ragdoll', description_tr = 'Persian, Scottish Fold, British, Ragdoll' WHERE slug = 'pets_cats';
UPDATE public.categories SET description_ar = 'Parrot, Canary, Budgie, Lovebird', description_en = 'Parrot, Canary, Budgie, Lovebird', description_ku = 'Parrot, Canary, Budgie, Lovebird', description_tr = 'Papağan, Kanarya, Muhabbet, Lovebird' WHERE slug = 'pets_birds';
UPDATE public.categories SET description_ar = 'Freshwater, Saltwater, Aquarium, Accessories', description_en = 'Freshwater, Saltwater, Aquarium, Accessories', description_ku = 'Freshwater, Saltwater, Aquarium, Accessories', description_tr = 'Tatlı su, Tuzlu su, Akvaryum, Aksesuar' WHERE slug = 'pets_fish';
UPDATE public.categories SET description_ar = 'Sheep, Goats, Cows, Chickens', description_en = 'Sheep, Goats, Cows, Chickens', description_ku = 'Sheep, Goats, Cows, Chickens', description_tr = 'Koyun, Keçi, İnek, Tavuk' WHERE slug = 'pets_farm';
UPDATE public.categories SET description_ar = 'Turtles, Snakes, Lizards, Frogs', description_en = 'Turtles, Snakes, Lizards, Frogs', description_ku = 'Turtles, Snakes, Lizards, Frogs', description_tr = 'Kaplumbağa, Yılan, Kertenkele, Kurbağa' WHERE slug = 'pets_reptiles';
UPDATE public.categories SET description_ar = 'Rabbits, Hamsters, Guinea pigs, Mice', description_en = 'Rabbits, Hamsters, Guinea pigs, Mice', description_ku = 'Rabbits, Hamsters, Guinea pigs, Mice', description_tr = 'Tavşan, Hamster, Gine domuzu, Fare' WHERE slug = 'pets_rabbits';
UPDATE public.categories SET description_ar = 'Food, Toys, Cages, Grooming', description_en = 'Food, Toys, Cages, Grooming', description_ku = 'Food, Toys, Cages, Grooming', description_tr = 'Mama, Oyuncak, Kafes, Bakım' WHERE slug = 'pets_accessories';
UPDATE public.categories SET description_ar = 'Vet, Grooming, Training, Boarding', description_en = 'Vet, Grooming, Training, Boarding', description_ku = 'Vet, Grooming, Training, Boarding', description_tr = 'Veteriner, Tımar, Eğitim, Pansiyon' WHERE slug = 'pets_services';
UPDATE public.categories SET description_ar = 'Lost pets, Found pets, Adoption', description_en = 'Lost pets, Found pets, Adoption', description_ku = 'Lost pets, Found pets, Adoption', description_tr = 'Kayıp, Bulunan, Sahiplendirme' WHERE slug = 'pets_lost_found';
