-- دراجات (veh_motorcycle) — rename + full brand/model tree
-- Replaces 20260607–20260610 motorcycle migrations (single source of truth).
-- Safe to re-run: cleans prior subtype/brand data then upserts by slug.

ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS logo_url TEXT;

UPDATE public.categories
SET name_ar = 'دراجات'
WHERE slug = 'veh_motorcycle';

CREATE OR REPLACE FUNCTION public._seed_moto_node(
  p_slug TEXT,
  p_name_ar TEXT,
  p_parent_slug TEXT,
  p_icon TEXT DEFAULT 'category',
  p_display_order INT DEFAULT 0,
  p_logo_url TEXT DEFAULT NULL
) RETURNS VOID AS $$
DECLARE
  v_parent_id INT;
BEGIN
  SELECT id INTO v_parent_id FROM public.categories WHERE slug = p_parent_slug;
  IF v_parent_id IS NULL THEN
    RAISE EXCEPTION 'Parent category not found: %', p_parent_slug;
  END IF;

  INSERT INTO public.categories (slug, name_ar, name_ku, name_en, icon, parent_id, display_order, logo_url)
  VALUES (p_slug, p_name_ar, NULL, NULL, p_icon, v_parent_id, p_display_order, p_logo_url)
  ON CONFLICT (slug) DO UPDATE SET
    name_ar = EXCLUDED.name_ar,
    name_ku = NULL,
    name_en = NULL,
    icon = EXCLUDED.icon,
    parent_id = EXCLUDED.parent_id,
    display_order = EXCLUDED.display_order,
    logo_url = EXCLUDED.logo_url;
END;
$$ LANGUAGE plpgsql;

-- Orphans from prior partial runs (models → brands → subtypes).
DELETE FROM public.categories WHERE icon = 'model' AND slug LIKE 'veh_moto_%';
DELETE FROM public.categories WHERE icon = 'brand' AND slug LIKE 'veh_moto_%';
DELETE FROM public.categories
WHERE slug IN ('veh_motorcycle_motor', 'veh_motorcycle_bicycle', 'veh_motorcycle_scooter');

DELETE FROM public.categories
WHERE id IN (
  WITH RECURSIVE subtree AS (
    SELECT c.id FROM public.categories c
    WHERE c.parent_id = (SELECT id FROM public.categories WHERE slug = 'veh_motorcycle')
    UNION ALL
    SELECT c.id FROM public.categories c
    INNER JOIN subtree s ON c.parent_id = s.id
  )
  SELECT id FROM subtree
);

SELECT public._seed_moto_node('veh_moto_br_yamaha', 'Yamaha', 'veh_motorcycle', 'brand', 1, 'https://www.carlogos.org/motorcycle-logos/yamaha-logo.png');
SELECT public._seed_moto_node('veh_moto_br_yamaha_yzf_r125', 'YZF-R125', 'veh_moto_br_yamaha', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yzf_r3', 'YZF-R3', 'veh_moto_br_yamaha', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yzf_r6', 'YZF-R6', 'veh_moto_br_yamaha', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yzf_r7', 'YZF-R7', 'veh_moto_br_yamaha', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yzf_r1', 'YZF-R1', 'veh_moto_br_yamaha', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_mt_125', 'MT-125', 'veh_moto_br_yamaha', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_mt_03', 'MT-03', 'veh_moto_br_yamaha', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_mt_07', 'MT-07', 'veh_moto_br_yamaha', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_mt_09', 'MT-09', 'veh_moto_br_yamaha', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_mt_10', 'MT-10', 'veh_moto_br_yamaha', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_t_n_r_700', 'Ténéré 700', 'veh_moto_br_yamaha', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_tracer_7', 'Tracer 7', 'veh_moto_br_yamaha', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_tracer_9', 'Tracer 9', 'veh_moto_br_yamaha', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_nmax_125', 'NMAX 125', 'veh_moto_br_yamaha', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_nmax_155', 'NMAX 155', 'veh_moto_br_yamaha', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_nmax_160', 'NMAX 160', 'veh_moto_br_yamaha', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_xmax_250', 'XMAX 250', 'veh_moto_br_yamaha', 'model', 17, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_xmax_300', 'XMAX 300', 'veh_moto_br_yamaha', 'model', 18, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_xmax_400', 'XMAX 400', 'veh_moto_br_yamaha', 'model', 19, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_tmax_560', 'TMAX 560', 'veh_moto_br_yamaha', 'model', 20, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_aerox_155', 'Aerox 155', 'veh_moto_br_yamaha', 'model', 21, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_ybr_125', 'YBR 125', 'veh_moto_br_yamaha', 'model', 22, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yz125', 'YZ125', 'veh_moto_br_yamaha', 'model', 23, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yz250', 'YZ250', 'veh_moto_br_yamaha', 'model', 24, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_yz450f', 'YZ450F', 'veh_moto_br_yamaha', 'model', 25, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_wr250f', 'WR250F', 'veh_moto_br_yamaha', 'model', 26, NULL);
SELECT public._seed_moto_node('veh_moto_br_yamaha_wr450f', 'WR450F', 'veh_moto_br_yamaha', 'model', 27, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda', 'Honda', 'veh_motorcycle', 'brand', 2, 'https://www.carlogos.org/motorcycle-logos/honda-logo.png');
SELECT public._seed_moto_node('veh_moto_br_honda_cb125f', 'CB125F', 'veh_moto_br_honda', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cb150f', 'CB150F', 'veh_moto_br_honda', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cb500f', 'CB500F', 'veh_moto_br_honda', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cb650r', 'CB650R', 'veh_moto_br_honda', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cbr125r', 'CBR125R', 'veh_moto_br_honda', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cbr500r', 'CBR500R', 'veh_moto_br_honda', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cbr650r', 'CBR650R', 'veh_moto_br_honda', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_cbr1000rr', 'CBR1000RR', 'veh_moto_br_honda', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_crf250l', 'CRF250L', 'veh_moto_br_honda', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_crf300l', 'CRF300L', 'veh_moto_br_honda', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_crf450r', 'CRF450R', 'veh_moto_br_honda', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_africa_twin_1100', 'Africa Twin 1100', 'veh_moto_br_honda', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_gold_wing', 'Gold Wing', 'veh_moto_br_honda', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_rebel_300', 'Rebel 300', 'veh_moto_br_honda', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_rebel_500', 'Rebel 500', 'veh_moto_br_honda', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_pcx_125', 'PCX 125', 'veh_moto_br_honda', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_pcx_160', 'PCX 160', 'veh_moto_br_honda', 'model', 17, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_forza_125', 'Forza 125', 'veh_moto_br_honda', 'model', 18, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_forza_350', 'Forza 350', 'veh_moto_br_honda', 'model', 19, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_forza_750', 'Forza 750', 'veh_moto_br_honda', 'model', 20, NULL);
SELECT public._seed_moto_node('veh_moto_br_honda_adv_350', 'ADV 350', 'veh_moto_br_honda', 'model', 21, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki', 'Kawasaki', 'veh_motorcycle', 'brand', 3, 'https://www.carlogos.org/motorcycle-logos/kawasaki-logo.png');
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_125', 'Ninja 125', 'veh_moto_br_kawasaki', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_250', 'Ninja 250', 'veh_moto_br_kawasaki', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_400', 'Ninja 400', 'veh_moto_br_kawasaki', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_650', 'Ninja 650', 'veh_moto_br_kawasaki', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_1000', 'Ninja 1000', 'veh_moto_br_kawasaki', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_zx_6r', 'Ninja ZX-6R', 'veh_moto_br_kawasaki', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_zx_10r', 'Ninja ZX-10R', 'veh_moto_br_kawasaki', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_ninja_zx_4r', 'Ninja ZX-4R', 'veh_moto_br_kawasaki', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_z125', 'Z125', 'veh_moto_br_kawasaki', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_z400', 'Z400', 'veh_moto_br_kawasaki', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_z650', 'Z650', 'veh_moto_br_kawasaki', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_z900', 'Z900', 'veh_moto_br_kawasaki', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_versys_300', 'Versys 300', 'veh_moto_br_kawasaki', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_versys_650', 'Versys 650', 'veh_moto_br_kawasaki', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_versys_1000', 'Versys 1000', 'veh_moto_br_kawasaki', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_vulcan_s', 'Vulcan S', 'veh_moto_br_kawasaki', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_klx_110', 'KLX 110', 'veh_moto_br_kawasaki', 'model', 17, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_klx_230', 'KLX 230', 'veh_moto_br_kawasaki', 'model', 18, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_klx_300', 'KLX 300', 'veh_moto_br_kawasaki', 'model', 19, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_kx_125', 'KX 125', 'veh_moto_br_kawasaki', 'model', 20, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_kx_250', 'KX 250', 'veh_moto_br_kawasaki', 'model', 21, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_kx_450', 'KX 450', 'veh_moto_br_kawasaki', 'model', 22, NULL);
SELECT public._seed_moto_node('veh_moto_br_kawasaki_klr_650', 'KLR 650', 'veh_moto_br_kawasaki', 'model', 23, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki', 'Suzuki', 'veh_motorcycle', 'brand', 4, 'https://www.carlogos.org/motorcycle-logos/suzuki-logo.png');
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_r125', 'GSX-R125', 'veh_moto_br_suzuki', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_r150', 'GSX-R150', 'veh_moto_br_suzuki', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_r600', 'GSX-R600', 'veh_moto_br_suzuki', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_r750', 'GSX-R750', 'veh_moto_br_suzuki', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_r1000', 'GSX-R1000', 'veh_moto_br_suzuki', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_s125', 'GSX-S125', 'veh_moto_br_suzuki', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_s750', 'GSX-S750', 'veh_moto_br_suzuki', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gsx_s1000', 'GSX-S1000', 'veh_moto_br_suzuki', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_v_strom_250', 'V-Strom 250', 'veh_moto_br_suzuki', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_v_strom_650', 'V-Strom 650', 'veh_moto_br_suzuki', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_v_strom_800', 'V-Strom 800', 'veh_moto_br_suzuki', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_v_strom_1050', 'V-Strom 1050', 'veh_moto_br_suzuki', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_sv650', 'SV650', 'veh_moto_br_suzuki', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gixxer_150', 'Gixxer 150', 'veh_moto_br_suzuki', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_gixxer_250', 'Gixxer 250', 'veh_moto_br_suzuki', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_burgman_125', 'Burgman 125', 'veh_moto_br_suzuki', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_burgman_200', 'Burgman 200', 'veh_moto_br_suzuki', 'model', 17, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_burgman_400', 'Burgman 400', 'veh_moto_br_suzuki', 'model', 18, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_burgman_650', 'Burgman 650', 'veh_moto_br_suzuki', 'model', 19, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_dr650', 'DR650', 'veh_moto_br_suzuki', 'model', 20, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_rm_z250', 'RM-Z250', 'veh_moto_br_suzuki', 'model', 21, NULL);
SELECT public._seed_moto_node('veh_moto_br_suzuki_rm_z450', 'RM-Z450', 'veh_moto_br_suzuki', 'model', 22, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm', 'KTM', 'veh_motorcycle', 'brand', 5, 'https://www.carlogos.org/motorcycle-logos/ktm-logo.png');
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_125', 'Duke 125', 'veh_moto_br_ktm', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_200', 'Duke 200', 'veh_moto_br_ktm', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_250', 'Duke 250', 'veh_moto_br_ktm', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_390', 'Duke 390', 'veh_moto_br_ktm', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_790', 'Duke 790', 'veh_moto_br_ktm', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_890', 'Duke 890', 'veh_moto_br_ktm', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_duke_1290', 'Duke 1290', 'veh_moto_br_ktm', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_rc_125', 'RC 125', 'veh_moto_br_ktm', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_rc_200', 'RC 200', 'veh_moto_br_ktm', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_rc_390', 'RC 390', 'veh_moto_br_ktm', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_rc_990', 'RC 990', 'veh_moto_br_ktm', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_adventure_390', 'Adventure 390', 'veh_moto_br_ktm', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_adventure_790', 'Adventure 790', 'veh_moto_br_ktm', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_adventure_890', 'Adventure 890', 'veh_moto_br_ktm', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_adventure_1290', 'Adventure 1290', 'veh_moto_br_ktm', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_exc_125', 'EXC 125', 'veh_moto_br_ktm', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_exc_250', 'EXC 250', 'veh_moto_br_ktm', 'model', 17, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_exc_300', 'EXC 300', 'veh_moto_br_ktm', 'model', 18, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_exc_450', 'EXC 450', 'veh_moto_br_ktm', 'model', 19, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_exc_500', 'EXC 500', 'veh_moto_br_ktm', 'model', 20, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_sx_125', 'SX 125', 'veh_moto_br_ktm', 'model', 21, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_sx_250', 'SX 250', 'veh_moto_br_ktm', 'model', 22, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_sx_350', 'SX 350', 'veh_moto_br_ktm', 'model', 23, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_sx_450', 'SX 450', 'veh_moto_br_ktm', 'model', 24, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_supermoto_390', 'Supermoto 390', 'veh_moto_br_ktm', 'model', 25, NULL);
SELECT public._seed_moto_node('veh_moto_br_ktm_supermoto_690', 'Supermoto 690', 'veh_moto_br_ktm', 'model', 26, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw', 'BMW', 'veh_motorcycle', 'brand', 6, 'https://www.carlogos.org/motorcycle-logos/bmw-motorrad-logo.png');
SELECT public._seed_moto_node('veh_moto_br_bmw_g_310_r', 'G 310 R', 'veh_moto_br_bmw', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_g_310_gs', 'G 310 GS', 'veh_moto_br_bmw', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_f_750_gs', 'F 750 GS', 'veh_moto_br_bmw', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_f_850_gs', 'F 850 GS', 'veh_moto_br_bmw', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_f_900_r', 'F 900 R', 'veh_moto_br_bmw', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_f_900_xr', 'F 900 XR', 'veh_moto_br_bmw', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_r_1250_gs', 'R 1250 GS', 'veh_moto_br_bmw', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_r_1250_adventure', 'R 1250 Adventure', 'veh_moto_br_bmw', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_r_1250_r', 'R 1250 R', 'veh_moto_br_bmw', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_r_1250_rt', 'R 1250 RT', 'veh_moto_br_bmw', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_r_1250_rs', 'R 1250 RS', 'veh_moto_br_bmw', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_s_1000_rr', 'S 1000 RR', 'veh_moto_br_bmw', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_s_1000_r', 'S 1000 R', 'veh_moto_br_bmw', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_s_1000_xr', 'S 1000 XR', 'veh_moto_br_bmw', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_k_1600_gt', 'K 1600 GT', 'veh_moto_br_bmw', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_k_1600_gtl', 'K 1600 GTL', 'veh_moto_br_bmw', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_k_1600_b', 'K 1600 B', 'veh_moto_br_bmw', 'model', 17, NULL);
SELECT public._seed_moto_node('veh_moto_br_bmw_ce_04', 'CE 04', 'veh_moto_br_bmw', 'model', 18, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati', 'Ducati', 'veh_motorcycle', 'brand', 7, 'https://www.carlogos.org/motorcycle-logos/ducati-logo.png');
SELECT public._seed_moto_node('veh_moto_br_ducati_panigale_v2', 'Panigale V2', 'veh_moto_br_ducati', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_panigale_v4', 'Panigale V4', 'veh_moto_br_ducati', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_panigale_v4s', 'Panigale V4S', 'veh_moto_br_ducati', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_streetfighter_v2', 'Streetfighter V2', 'veh_moto_br_ducati', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_streetfighter_v4', 'Streetfighter V4', 'veh_moto_br_ducati', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_monster_797', 'Monster 797', 'veh_moto_br_ducati', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_monster_821', 'Monster 821', 'veh_moto_br_ducati', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_monster_937', 'Monster 937', 'veh_moto_br_ducati', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_multistrada_v2', 'Multistrada V2', 'veh_moto_br_ducati', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_multistrada_v4', 'Multistrada V4', 'veh_moto_br_ducati', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_multistrada_v4s', 'Multistrada V4S', 'veh_moto_br_ducati', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_scrambler_icon', 'Scrambler Icon', 'veh_moto_br_ducati', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_scrambler_desert_sled', 'Scrambler Desert Sled', 'veh_moto_br_ducati', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_hypermotard_950', 'Hypermotard 950', 'veh_moto_br_ducati', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_diavel_v4', 'Diavel V4', 'veh_moto_br_ducati', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_ducati_xdiavel', 'XDiavel', 'veh_moto_br_ducati', 'model', 16, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson', 'Harley-Davidson', 'veh_motorcycle', 'brand', 8, 'https://www.carlogos.org/motorcycle-logos/harley-davidson-logo.png');
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_sportster_s', 'Sportster S', 'veh_moto_br_harley_davidson', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_iron_883', 'Iron 883', 'veh_moto_br_harley_davidson', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_iron_1200', 'Iron 1200', 'veh_moto_br_harley_davidson', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_nightster', 'Nightster', 'veh_moto_br_harley_davidson', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_street_bob', 'Street Bob', 'veh_moto_br_harley_davidson', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_fat_bob', 'Fat Bob', 'veh_moto_br_harley_davidson', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_fat_boy', 'Fat Boy', 'veh_moto_br_harley_davidson', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_heritage_classic', 'Heritage Classic', 'veh_moto_br_harley_davidson', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_road_king', 'Road King', 'veh_moto_br_harley_davidson', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_street_glide', 'Street Glide', 'veh_moto_br_harley_davidson', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_road_glide', 'Road Glide', 'veh_moto_br_harley_davidson', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_harley_davidson_pan_america_1250', 'Pan America 1250', 'veh_moto_br_harley_davidson', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield', 'Royal Enfield', 'veh_motorcycle', 'brand', 9, 'https://www.carlogos.org/motorcycle-logos/royal-enfield-logo.png');
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_classic_350', 'Classic 350', 'veh_moto_br_royal_enfield', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_classic_500', 'Classic 500', 'veh_moto_br_royal_enfield', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_hunter_350', 'Hunter 350', 'veh_moto_br_royal_enfield', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_meteor_350', 'Meteor 350', 'veh_moto_br_royal_enfield', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_bullet_350', 'Bullet 350', 'veh_moto_br_royal_enfield', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_himalayan_411', 'Himalayan 411', 'veh_moto_br_royal_enfield', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_himalayan_450', 'Himalayan 450', 'veh_moto_br_royal_enfield', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_interceptor_650', 'Interceptor 650', 'veh_moto_br_royal_enfield', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_continental_gt_650', 'Continental GT 650', 'veh_moto_br_royal_enfield', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_super_meteor_650', 'Super Meteor 650', 'veh_moto_br_royal_enfield', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_enfield_shotgun_650', 'Shotgun 650', 'veh_moto_br_royal_enfield', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph', 'Triumph', 'veh_motorcycle', 'brand', 10, 'https://www.carlogos.org/motorcycle-logos/triumph-logo.png');
SELECT public._seed_moto_node('veh_moto_br_triumph_bonneville_t100', 'Bonneville T100', 'veh_moto_br_triumph', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_bonneville_t120', 'Bonneville T120', 'veh_moto_br_triumph', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_speed_twin_900', 'Speed Twin 900', 'veh_moto_br_triumph', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_speed_twin_1200', 'Speed Twin 1200', 'veh_moto_br_triumph', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_scrambler_400x', 'Scrambler 400X', 'veh_moto_br_triumph', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_scrambler_900', 'Scrambler 900', 'veh_moto_br_triumph', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_scrambler_1200', 'Scrambler 1200', 'veh_moto_br_triumph', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_street_triple_765', 'Street Triple 765', 'veh_moto_br_triumph', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_speed_triple_1200_rs', 'Speed Triple 1200 RS', 'veh_moto_br_triumph', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_rocket_3_r', 'Rocket 3 R', 'veh_moto_br_triumph', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_rocket_3_gt', 'Rocket 3 GT', 'veh_moto_br_triumph', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_daytona_660', 'Daytona 660', 'veh_moto_br_triumph', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_daytona_675', 'Daytona 675', 'veh_moto_br_triumph', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_bobber', 'Bobber', 'veh_moto_br_triumph', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_triumph_speedmaster', 'Speedmaster', 'veh_moto_br_triumph', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian', 'Indian', 'veh_motorcycle', 'brand', 11, 'https://www.carlogos.org/motorcycle-logos/indian-logo.png');
SELECT public._seed_moto_node('veh_moto_br_indian_scout_bobber', 'Scout Bobber', 'veh_moto_br_indian', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_scout_rogue', 'Scout Rogue', 'veh_moto_br_indian', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_scout_sixty', 'Scout Sixty', 'veh_moto_br_indian', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_chief_dark_horse', 'Chief Dark Horse', 'veh_moto_br_indian', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_chief_bobber', 'Chief Bobber', 'veh_moto_br_indian', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_springfield', 'Springfield', 'veh_moto_br_indian', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_chieftain', 'Chieftain', 'veh_moto_br_indian', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_roadmaster', 'Roadmaster', 'veh_moto_br_indian', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_indian_ftr_1200', 'FTR 1200', 'veh_moto_br_indian', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia', 'Aprilia', 'veh_motorcycle', 'brand', 12, 'https://www.carlogos.org/motorcycle-logos/aprilia-logo.png');
SELECT public._seed_moto_node('veh_moto_br_aprilia_rsv4', 'RSV4', 'veh_moto_br_aprilia', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_tuono_125', 'Tuono 125', 'veh_moto_br_aprilia', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_tuono_660', 'Tuono 660', 'veh_moto_br_aprilia', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_tuono_v4', 'Tuono V4', 'veh_moto_br_aprilia', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_shiver_750', 'Shiver 750', 'veh_moto_br_aprilia', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_shiver_900', 'Shiver 900', 'veh_moto_br_aprilia', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_dorsoduro_750', 'Dorsoduro 750', 'veh_moto_br_aprilia', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_dorsoduro_900', 'Dorsoduro 900', 'veh_moto_br_aprilia', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_sr_gt_125', 'SR GT 125', 'veh_moto_br_aprilia', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_aprilia_sr_gt_200', 'SR GT 200', 'veh_moto_br_aprilia', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa', 'Vespa', 'veh_motorcycle', 'brand', 13, 'https://www.carlogos.org/motorcycle-logos/vespa-logo.png');
SELECT public._seed_moto_node('veh_moto_br_vespa_primavera_50', 'Primavera 50', 'veh_moto_br_vespa', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_primavera_125', 'Primavera 125', 'veh_moto_br_vespa', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_primavera_150', 'Primavera 150', 'veh_moto_br_vespa', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_sprint_50', 'Sprint 50', 'veh_moto_br_vespa', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_sprint_125', 'Sprint 125', 'veh_moto_br_vespa', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_sprint_150', 'Sprint 150', 'veh_moto_br_vespa', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_gts_125', 'GTS 125', 'veh_moto_br_vespa', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_gts_300', 'GTS 300', 'veh_moto_br_vespa', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_gts_310', 'GTS 310', 'veh_moto_br_vespa', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_gtv_300', 'GTV 300', 'veh_moto_br_vespa', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_px_125', 'PX 125', 'veh_moto_br_vespa', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_px_150', 'PX 150', 'veh_moto_br_vespa', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_vespa_elettrica', 'Elettrica', 'veh_moto_br_vespa', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio', 'Piaggio', 'veh_motorcycle', 'brand', 14, 'https://www.carlogos.org/motorcycle-logos/piaggio-logo.png');
SELECT public._seed_moto_node('veh_moto_br_piaggio_liberty_50', 'Liberty 50', 'veh_moto_br_piaggio', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_liberty_125', 'Liberty 125', 'veh_moto_br_piaggio', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_liberty_150', 'Liberty 150', 'veh_moto_br_piaggio', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_beverly_300', 'Beverly 300', 'veh_moto_br_piaggio', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_beverly_400', 'Beverly 400', 'veh_moto_br_piaggio', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_medley_125', 'Medley 125', 'veh_moto_br_piaggio', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_medley_150', 'Medley 150', 'veh_moto_br_piaggio', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_mp3_300', 'MP3 300', 'veh_moto_br_piaggio', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_mp3_400', 'MP3 400', 'veh_moto_br_piaggio', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_mp3_500', 'MP3 500', 'veh_moto_br_piaggio', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_typhoon_50', 'Typhoon 50', 'veh_moto_br_piaggio', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_typhoon_125', 'Typhoon 125', 'veh_moto_br_piaggio', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_zip_50', 'Zip 50', 'veh_moto_br_piaggio', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_piaggio_zip_100', 'Zip 100', 'veh_moto_br_piaggio', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna', 'Husqvarna', 'veh_motorcycle', 'brand', 15, 'https://www.carlogos.org/motorcycle-logos/husqvarna-logo.png');
SELECT public._seed_moto_node('veh_moto_br_husqvarna_vitpilen_125', 'Vitpilen 125', 'veh_moto_br_husqvarna', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_vitpilen_401', 'Vitpilen 401', 'veh_moto_br_husqvarna', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_vitpilen_701', 'Vitpilen 701', 'veh_moto_br_husqvarna', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_svartpilen_125', 'Svartpilen 125', 'veh_moto_br_husqvarna', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_svartpilen_401', 'Svartpilen 401', 'veh_moto_br_husqvarna', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_svartpilen_701', 'Svartpilen 701', 'veh_moto_br_husqvarna', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_norden_901', 'Norden 901', 'veh_moto_br_husqvarna', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_te_125', 'TE 125', 'veh_moto_br_husqvarna', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_te_250', 'TE 250', 'veh_moto_br_husqvarna', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_te_300', 'TE 300', 'veh_moto_br_husqvarna', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_fe_250', 'FE 250', 'veh_moto_br_husqvarna', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_fe_350', 'FE 350', 'veh_moto_br_husqvarna', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_fe_450', 'FE 450', 'veh_moto_br_husqvarna', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_tc_125', 'TC 125', 'veh_moto_br_husqvarna', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_husqvarna_tc_250', 'TC 250', 'veh_moto_br_husqvarna', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj', 'Bajaj', 'veh_motorcycle', 'brand', 16, 'https://www.carlogos.org/motorcycle-logos/bajaj-logo.png');
SELECT public._seed_moto_node('veh_moto_br_bajaj_pulsar_125', 'Pulsar 125', 'veh_moto_br_bajaj', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_pulsar_150', 'Pulsar 150', 'veh_moto_br_bajaj', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_pulsar_160', 'Pulsar 160', 'veh_moto_br_bajaj', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_pulsar_180', 'Pulsar 180', 'veh_moto_br_bajaj', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_pulsar_200', 'Pulsar 200', 'veh_moto_br_bajaj', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_pulsar_220', 'Pulsar 220', 'veh_moto_br_bajaj', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_dominar_250', 'Dominar 250', 'veh_moto_br_bajaj', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_dominar_400', 'Dominar 400', 'veh_moto_br_bajaj', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_avenger_160', 'Avenger 160', 'veh_moto_br_bajaj', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_avenger_220', 'Avenger 220', 'veh_moto_br_bajaj', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_boxer_100', 'Boxer 100', 'veh_moto_br_bajaj', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_boxer_150', 'Boxer 150', 'veh_moto_br_bajaj', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_platina_100', 'Platina 100', 'veh_moto_br_bajaj', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_platina_110', 'Platina 110', 'veh_moto_br_bajaj', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_bajaj_platina_125', 'Platina 125', 'veh_moto_br_bajaj', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs', 'TVS', 'veh_motorcycle', 'brand', 17, 'https://www.carlogos.org/motorcycle-logos/tvs-logo.png');
SELECT public._seed_moto_node('veh_moto_br_tvs_apache_rtr_160', 'Apache RTR 160', 'veh_moto_br_tvs', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_apache_rtr_180', 'Apache RTR 180', 'veh_moto_br_tvs', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_apache_rtr_200', 'Apache RTR 200', 'veh_moto_br_tvs', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_apache_rtr_310', 'Apache RTR 310', 'veh_moto_br_tvs', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_raider_125', 'Raider 125', 'veh_moto_br_tvs', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_ronin_225', 'Ronin 225', 'veh_moto_br_tvs', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_ntorq_125', 'Ntorq 125', 'veh_moto_br_tvs', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_tvs_iqube', 'iQube', 'veh_moto_br_tvs', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero', 'Hero', 'veh_motorcycle', 'brand', 18, 'https://www.carlogos.org/motorcycle-logos/hero-logo.png');
SELECT public._seed_moto_node('veh_moto_br_hero_splendor_plus', 'Splendor Plus', 'veh_moto_br_hero', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero_hf_deluxe', 'HF Deluxe', 'veh_moto_br_hero', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero_glamour_125', 'Glamour 125', 'veh_moto_br_hero', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero_xtreme_160r', 'Xtreme 160R', 'veh_moto_br_hero', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero_xtreme_200s', 'Xtreme 200S', 'veh_moto_br_hero', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero_xpulse_200', 'XPulse 200', 'veh_moto_br_hero', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_hero_passion_pro', 'Passion Pro', 'veh_moto_br_hero', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli', 'Benelli', 'veh_motorcycle', 'brand', 19, 'https://www.carlogos.org/motorcycle-logos/benelli-logo.png');
SELECT public._seed_moto_node('veh_moto_br_benelli_tnt_125', 'TNT 125', 'veh_moto_br_benelli', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_tnt_135', 'TNT 135', 'veh_moto_br_benelli', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_tnt_150', 'TNT 150', 'veh_moto_br_benelli', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_tnt_249', 'TNT 249', 'veh_moto_br_benelli', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_tnt_300', 'TNT 300', 'veh_moto_br_benelli', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_tnt_600', 'TNT 600', 'veh_moto_br_benelli', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_leoncino_250', 'Leoncino 250', 'veh_moto_br_benelli', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_leoncino_500', 'Leoncino 500', 'veh_moto_br_benelli', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_leoncino_800', 'Leoncino 800', 'veh_moto_br_benelli', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_trk_251', 'TRK 251', 'veh_moto_br_benelli', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_trk_502', 'TRK 502', 'veh_moto_br_benelli', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_trk_702', 'TRK 702', 'veh_moto_br_benelli', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_trk_800', 'TRK 800', 'veh_moto_br_benelli', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_imperiale_400', 'Imperiale 400', 'veh_moto_br_benelli', 'model', 14, NULL);
SELECT public._seed_moto_node('veh_moto_br_benelli_302r', '302R', 'veh_moto_br_benelli', 'model', 15, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto', 'CFMoto', 'veh_motorcycle', 'brand', 20, 'https://www.carlogos.org/motorcycle-logos/cf-moto-logo.png');
SELECT public._seed_moto_node('veh_moto_br_cfmoto_150nk', '150NK', 'veh_moto_br_cfmoto', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_250nk', '250NK', 'veh_moto_br_cfmoto', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_300nk', '300NK', 'veh_moto_br_cfmoto', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_450nk', '450NK', 'veh_moto_br_cfmoto', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_650nk', '650NK', 'veh_moto_br_cfmoto', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_300sr', '300SR', 'veh_moto_br_cfmoto', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_450sr', '450SR', 'veh_moto_br_cfmoto', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_675sr', '675SR', 'veh_moto_br_cfmoto', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_650mt', '650MT', 'veh_moto_br_cfmoto', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_800mt', '800MT', 'veh_moto_br_cfmoto', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_450mt', '450MT', 'veh_moto_br_cfmoto', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_400gt', '400GT', 'veh_moto_br_cfmoto', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_cfmoto_650gt', '650GT', 'veh_moto_br_cfmoto', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco', 'Kymco', 'veh_motorcycle', 'brand', 21, 'https://www.carlogos.org/motorcycle-logos/kymco-logo.png');
SELECT public._seed_moto_node('veh_moto_br_kymco_agility_125', 'Agility 125', 'veh_moto_br_kymco', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_agility_150', 'Agility 150', 'veh_moto_br_kymco', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_like_125', 'Like 125', 'veh_moto_br_kymco', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_like_150', 'Like 150', 'veh_moto_br_kymco', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_like_200', 'Like 200', 'veh_moto_br_kymco', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_xciting_400', 'Xciting 400', 'veh_moto_br_kymco', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_xciting_500', 'Xciting 500', 'veh_moto_br_kymco', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_downtown_125', 'Downtown 125', 'veh_moto_br_kymco', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_downtown_350', 'Downtown 350', 'veh_moto_br_kymco', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_kymco_ak_550', 'AK 550', 'veh_moto_br_kymco', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym', 'SYM', 'veh_motorcycle', 'brand', 22, 'https://www.carlogos.org/motorcycle-logos/sym-logo.png');
SELECT public._seed_moto_node('veh_moto_br_sym_jet_14_125', 'Jet 14 125', 'veh_moto_br_sym', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_jet_14_200', 'Jet 14 200', 'veh_moto_br_sym', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_symphony_125', 'Symphony 125', 'veh_moto_br_sym', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_symphony_200', 'Symphony 200', 'veh_moto_br_sym', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_fiddle_125', 'Fiddle 125', 'veh_moto_br_sym', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_fiddle_200', 'Fiddle 200', 'veh_moto_br_sym', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_joymax_125', 'Joymax 125', 'veh_moto_br_sym', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_joymax_250', 'Joymax 250', 'veh_moto_br_sym', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_joymax_300', 'Joymax 300', 'veh_moto_br_sym', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_wolf_125', 'Wolf 125', 'veh_moto_br_sym', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_cruisym_250', 'Cruisym 250', 'veh_moto_br_sym', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_sym_cruisym_300', 'Cruisym 300', 'veh_moto_br_sym', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway', 'Keeway', 'veh_motorcycle', 'brand', 23, 'https://www.carlogos.org/motorcycle-logos/keeway-logo.png');
SELECT public._seed_moto_node('veh_moto_br_keeway_rkf_125', 'RKF 125', 'veh_moto_br_keeway', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_rkf_150', 'RKF 150', 'veh_moto_br_keeway', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_rkf_200', 'RKF 200', 'veh_moto_br_keeway', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_rks_125', 'RKS 125', 'veh_moto_br_keeway', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_rks_150', 'RKS 150', 'veh_moto_br_keeway', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_superlight_125', 'Superlight 125', 'veh_moto_br_keeway', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_vieste_125', 'Vieste 125', 'veh_moto_br_keeway', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_vieste_300', 'Vieste 300', 'veh_moto_br_keeway', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_keeway_k_light_125', 'K-Light 125', 'veh_moto_br_keeway', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan', 'Lifan', 'veh_motorcycle', 'brand', 24, 'https://www.carlogos.org/motorcycle-logos/lifan-logo.png');
SELECT public._seed_moto_node('veh_moto_br_lifan_lf100', 'LF100', 'veh_moto_br_lifan', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_lf125', 'LF125', 'veh_moto_br_lifan', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_lf150', 'LF150', 'veh_moto_br_lifan', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_lf200', 'LF200', 'veh_moto_br_lifan', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_lf250', 'LF250', 'veh_moto_br_lifan', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_kpr_150', 'KPR 150', 'veh_moto_br_lifan', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_kpt_200', 'KPT 200', 'veh_moto_br_lifan', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_kpt_400', 'KPT 400', 'veh_moto_br_lifan', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_lifan_v16_250', 'V16 250', 'veh_moto_br_lifan', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_loncin', 'Loncin', 'veh_motorcycle', 'brand', 25, 'https://www.carlogos.org/motorcycle-logos/loncin-logo.png');
SELECT public._seed_moto_node('veh_moto_br_loncin_lx125', 'LX125', 'veh_moto_br_loncin', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_loncin_lx150', 'LX150', 'veh_moto_br_loncin', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_loncin_lx200', 'LX200', 'veh_moto_br_loncin', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_loncin_lx250', 'LX250', 'veh_moto_br_loncin', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_loncin_cr_series', 'CR Series', 'veh_moto_br_loncin', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_loncin_gp_series', 'GP Series', 'veh_moto_br_loncin', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen', 'Zongshen', 'veh_motorcycle', 'brand', 26, 'https://www.carlogos.org/motorcycle-logos/zongshen-logo.png');
SELECT public._seed_moto_node('veh_moto_br_zongshen_zs125', 'ZS125', 'veh_moto_br_zongshen', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_zs150', 'ZS150', 'veh_moto_br_zongshen', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_rx1_200', 'RX1 200', 'veh_moto_br_zongshen', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_rx3_250', 'RX3 250', 'veh_moto_br_zongshen', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_rx4_400', 'RX4 400', 'veh_moto_br_zongshen', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_zs200gy', 'ZS200GY', 'veh_moto_br_zongshen', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_atv_250', 'ATV 250', 'veh_moto_br_zongshen', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_atv_300', 'ATV 300', 'veh_moto_br_zongshen', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_zongshen_atv_400', 'ATV 400', 'veh_moto_br_zongshen', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes', 'Zontes', 'veh_motorcycle', 'brand', 27, 'https://www.carlogos.org/motorcycle-logos/zontes-logo.png');
SELECT public._seed_moto_node('veh_moto_br_zontes_125u', '125U', 'veh_moto_br_zontes', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_155u', '155U', 'veh_moto_br_zontes', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_250r', '250R', 'veh_moto_br_zontes', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_250u', '250U', 'veh_moto_br_zontes', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_310r', '310R', 'veh_moto_br_zontes', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_310x', '310X', 'veh_moto_br_zontes', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_310t', '310T', 'veh_moto_br_zontes', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_350r', '350R', 'veh_moto_br_zontes', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_350x', '350X', 'veh_moto_br_zontes', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_350t', '350T', 'veh_moto_br_zontes', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_703f', '703F', 'veh_moto_br_zontes', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_zontes_703rr', '703RR', 'veh_moto_br_zontes', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge', 'Voge', 'veh_motorcycle', 'brand', 28, 'https://www.carlogos.org/motorcycle-logos/voge-logo.png');
SELECT public._seed_moto_node('veh_moto_br_voge_125r', '125R', 'veh_moto_br_voge', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_300r', '300R', 'veh_moto_br_voge', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_500r', '500R', 'veh_moto_br_voge', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_525r', '525R', 'veh_moto_br_voge', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_300ac', '300AC', 'veh_moto_br_voge', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_500ac', '500AC', 'veh_moto_br_voge', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_300ds', '300DS', 'veh_moto_br_voge', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_525ds', '525DS', 'veh_moto_br_voge', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_650ds', '650DS', 'veh_moto_br_voge', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_voge_sr4_max', 'SR4 Max', 'veh_moto_br_voge', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj', 'QJ', 'veh_motorcycle', 'brand', 29, 'https://www.carlogos.org/motorcycle-logos/qj-logo.png');
SELECT public._seed_moto_node('veh_moto_br_qj_srk_125', 'SRK 125', 'veh_moto_br_qj', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srk_250', 'SRK 250', 'veh_moto_br_qj', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srk_400', 'SRK 400', 'veh_moto_br_qj', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srk_550', 'SRK 550', 'veh_moto_br_qj', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srk_600', 'SRK 600', 'veh_moto_br_qj', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srk_700', 'SRK 700', 'veh_moto_br_qj', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srt_550', 'SRT 550', 'veh_moto_br_qj', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srt_700', 'SRT 700', 'veh_moto_br_qj', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srt_800', 'SRT 800', 'veh_moto_br_qj', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_flash_300', 'Flash 300', 'veh_moto_br_qj', 'model', 10, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_flash_350', 'Flash 350', 'veh_moto_br_qj', 'model', 11, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srv_300', 'SRV 300', 'veh_moto_br_qj', 'model', 12, NULL);
SELECT public._seed_moto_node('veh_moto_br_qj_srv_550', 'SRV 550', 'veh_moto_br_qj', 'model', 13, NULL);
SELECT public._seed_moto_node('veh_moto_br_jawa', 'Jawa', 'veh_motorcycle', 'brand', 30, 'https://www.carlogos.org/motorcycle-logos/jawa-logo.png');
SELECT public._seed_moto_node('veh_moto_br_jawa_jawa_42', 'Jawa 42', 'veh_moto_br_jawa', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_jawa_jawa_42_bobber', 'Jawa 42 Bobber', 'veh_moto_br_jawa', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_jawa_jawa_perak', 'Jawa Perak', 'veh_moto_br_jawa', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_jawa_jawa_standard_300', 'Jawa Standard 300', 'veh_moto_br_jawa', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_jawa_jawa_350', 'Jawa 350', 'veh_moto_br_jawa', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_can_am', 'Can-Am', 'veh_motorcycle', 'brand', 31, 'https://www.carlogos.org/motorcycle-logos/can-am-logo.png');
SELECT public._seed_moto_node('veh_moto_br_can_am_spyder_rt', 'Spyder RT', 'veh_moto_br_can_am', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_can_am_spyder_f3', 'Spyder F3', 'veh_moto_br_can_am', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_can_am_ryker_600', 'Ryker 600', 'veh_moto_br_can_am', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_can_am_ryker_900', 'Ryker 900', 'veh_moto_br_can_am', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_can_am_canyon', 'Canyon', 'veh_moto_br_can_am', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas', 'GasGas', 'veh_motorcycle', 'brand', 32, 'https://www.carlogos.org/motorcycle-logos/gasgas-logo.png');
SELECT public._seed_moto_node('veh_moto_br_gasgas_ec_125', 'EC 125', 'veh_moto_br_gasgas', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_ec_250', 'EC 250', 'veh_moto_br_gasgas', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_ec_300', 'EC 300', 'veh_moto_br_gasgas', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_mc_125', 'MC 125', 'veh_moto_br_gasgas', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_mc_250', 'MC 250', 'veh_moto_br_gasgas', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_mc_450', 'MC 450', 'veh_moto_br_gasgas', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_ex_250', 'EX 250', 'veh_moto_br_gasgas', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_ex_300', 'EX 300', 'veh_moto_br_gasgas', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_gasgas_sm_700', 'SM 700', 'veh_moto_br_gasgas', 'model', 9, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco', 'Sherco', 'veh_motorcycle', 'brand', 33, 'https://www.carlogos.org/motorcycle-logos/sherco-logo.png');
SELECT public._seed_moto_node('veh_moto_br_sherco_se_125', 'SE 125', 'veh_moto_br_sherco', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco_se_250', 'SE 250', 'veh_moto_br_sherco', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco_se_300', 'SE 300', 'veh_moto_br_sherco', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco_sef_250', 'SEF 250', 'veh_moto_br_sherco', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco_sef_300', 'SEF 300', 'veh_moto_br_sherco', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco_sef_450', 'SEF 450', 'veh_moto_br_sherco', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_sherco_sm_r_125', 'SM-R 125', 'veh_moto_br_sherco', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_beta', 'Beta', 'veh_motorcycle', 'brand', 34, 'https://www.carlogos.org/motorcycle-logos/beta-logo.png');
SELECT public._seed_moto_node('veh_moto_br_beta_rr_125', 'RR 125', 'veh_moto_br_beta', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_beta_rr_200', 'RR 200', 'veh_moto_br_beta', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_beta_rr_250', 'RR 250', 'veh_moto_br_beta', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_beta_rr_300', 'RR 300', 'veh_moto_br_beta', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_beta_xtrainer_250', 'Xtrainer 250', 'veh_moto_br_beta', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_beta_alp_200', 'Alp 200', 'veh_moto_br_beta', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi', 'Moto Guzzi', 'veh_motorcycle', 'brand', 35, 'https://www.carlogos.org/motorcycle-logos/moto-guzzi-logo.png');
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_v7_stone', 'V7 Stone', 'veh_moto_br_moto_guzzi', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_v7_special', 'V7 Special', 'veh_moto_br_moto_guzzi', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_v9_bobber', 'V9 Bobber', 'veh_moto_br_moto_guzzi', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_v9_roamer', 'V9 Roamer', 'veh_moto_br_moto_guzzi', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_california_1400', 'California 1400', 'veh_moto_br_moto_guzzi', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_v85_tt', 'V85 TT', 'veh_moto_br_moto_guzzi', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_moto_guzzi_griso_1200', 'Griso 1200', 'veh_moto_br_moto_guzzi', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_norton', 'Norton', 'veh_motorcycle', 'brand', 36, 'https://www.carlogos.org/motorcycle-logos/norton-logo.png');
SELECT public._seed_moto_node('veh_moto_br_norton_commando_961', 'Commando 961', 'veh_moto_br_norton', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_norton_v4_rr', 'V4 RR', 'veh_moto_br_norton', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_norton_v4_sv', 'V4 SV', 'veh_moto_br_norton', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_norton_atlas_ranger', 'Atlas Ranger', 'veh_moto_br_norton', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_norton_atlas_nomad', 'Atlas Nomad', 'veh_moto_br_norton', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta', 'MV Agusta', 'veh_motorcycle', 'brand', 37, 'https://www.carlogos.org/motorcycle-logos/mv-agusta-logo.png');
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_brutale_800', 'Brutale 800', 'veh_moto_br_mv_agusta', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_brutale_1000', 'Brutale 1000', 'veh_moto_br_mv_agusta', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_dragster_800', 'Dragster 800', 'veh_moto_br_mv_agusta', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_f3_675', 'F3 675', 'veh_moto_br_mv_agusta', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_f3_800', 'F3 800', 'veh_moto_br_mv_agusta', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_f4', 'F4', 'veh_moto_br_mv_agusta', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_turismo_veloce', 'Turismo Veloce', 'veh_moto_br_mv_agusta', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_mv_agusta_superveloce_800', 'Superveloce 800', 'veh_moto_br_mv_agusta', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung', 'Hyosung', 'veh_motorcycle', 'brand', 38, 'https://www.carlogos.org/motorcycle-logos/hyosung-logo.png');
SELECT public._seed_moto_node('veh_moto_br_hyosung_gt125', 'GT125', 'veh_moto_br_hyosung', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung_gt250', 'GT250', 'veh_moto_br_hyosung', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung_gt650', 'GT650', 'veh_moto_br_hyosung', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung_gv125', 'GV125', 'veh_moto_br_hyosung', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung_gv250', 'GV250', 'veh_moto_br_hyosung', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung_gd250n', 'GD250N', 'veh_moto_br_hyosung', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_hyosung_gd250r', 'GD250R', 'veh_moto_br_hyosung', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton', 'Brixton', 'veh_motorcycle', 'brand', 39, 'https://www.carlogos.org/motorcycle-logos/brixton-logo.png');
SELECT public._seed_moto_node('veh_moto_br_brixton_cromwell_125', 'Cromwell 125', 'veh_moto_br_brixton', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_cromwell_250', 'Cromwell 250', 'veh_moto_br_brixton', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_cromwell_500', 'Cromwell 500', 'veh_moto_br_brixton', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_felsberg_125', 'Felsberg 125', 'veh_moto_br_brixton', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_felsberg_250', 'Felsberg 250', 'veh_moto_br_brixton', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_crossfire_125', 'Crossfire 125', 'veh_moto_br_brixton', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_crossfire_250', 'Crossfire 250', 'veh_moto_br_brixton', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_brixton_crossfire_500', 'Crossfire 500', 'veh_moto_br_brixton', 'model', 8, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_alloy', 'Royal Alloy', 'veh_motorcycle', 'brand', 40, 'https://www.carlogos.org/motorcycle-logos/royal-alloy-logo.png');
SELECT public._seed_moto_node('veh_moto_br_royal_alloy_gp125', 'GP125', 'veh_moto_br_royal_alloy', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_alloy_gp300', 'GP300', 'veh_moto_br_royal_alloy', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_alloy_tg125', 'TG125', 'veh_moto_br_royal_alloy', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_royal_alloy_tg300', 'TG300', 'veh_moto_br_royal_alloy', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_regal_raptor', 'Regal Raptor', 'veh_motorcycle', 'brand', 41, 'https://www.carlogos.org/motorcycle-logos/regal-raptor-logo.png');
SELECT public._seed_moto_node('veh_moto_br_regal_raptor_dd125e', 'DD125E', 'veh_moto_br_regal_raptor', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_regal_raptor_dd250e', 'DD250E', 'veh_moto_br_regal_raptor', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_regal_raptor_dd350e', 'DD350E', 'veh_moto_br_regal_raptor', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_regal_raptor_daytona_250', 'Daytona 250', 'veh_moto_br_regal_raptor', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_regal_raptor_spyder_350', 'Spyder 350', 'veh_moto_br_regal_raptor', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim', 'Daelim', 'veh_motorcycle', 'brand', 42, 'https://www.carlogos.org/motorcycle-logos/daelim-logo.png');
SELECT public._seed_moto_node('veh_moto_br_daelim_s1_125', 'S1 125', 'veh_moto_br_daelim', 'model', 1, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim_s1_250', 'S1 250', 'veh_moto_br_daelim', 'model', 2, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim_s2_125', 'S2 125', 'veh_moto_br_daelim', 'model', 3, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim_roadwin_125', 'Roadwin 125', 'veh_moto_br_daelim', 'model', 4, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim_roadwin_250', 'Roadwin 250', 'veh_moto_br_daelim', 'model', 5, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim_daystar_125', 'Daystar 125', 'veh_moto_br_daelim', 'model', 6, NULL);
SELECT public._seed_moto_node('veh_moto_br_daelim_daystar_250', 'Daystar 250', 'veh_moto_br_daelim', 'model', 7, NULL);
SELECT public._seed_moto_node('veh_moto_br_kove', 'Kove', 'veh_motorcycle', 'brand', 43, 'https://www.carlogos.org/motorcycle-logos/kove-logo.png');
SELECT public._seed_moto_node('veh_moto_br_minsk', 'Minsk', 'veh_motorcycle', 'brand', 44, 'https://www.carlogos.org/motorcycle-logos/minsk-logo.png');
SELECT public._seed_moto_node('veh_moto_br_puch', 'Puch', 'veh_motorcycle', 'brand', 45, 'https://www.carlogos.org/motorcycle-logos/puch-logo.png');
SELECT public._seed_moto_node('veh_moto_br_lambretta', 'Lambretta', 'veh_motorcycle', 'brand', 46, 'https://www.carlogos.org/motorcycle-logos/lambretta-logo.png');
SELECT public._seed_moto_node('veh_moto_br_bimota', 'Bimota', 'veh_motorcycle', 'brand', 47, 'https://www.carlogos.org/motorcycle-logos/bimota-logo.png');
SELECT public._seed_moto_node('veh_moto_br_buell', 'Buell', 'veh_motorcycle', 'brand', 48, 'https://www.carlogos.org/motorcycle-logos/buell-logo.png');
SELECT public._seed_moto_node('veh_moto_br_energica', 'Energica', 'veh_motorcycle', 'brand', 49, 'https://www.carlogos.org/motorcycle-logos/energica-logo.png');
SELECT public._seed_moto_node('veh_moto_br_fantic', 'Fantic', 'veh_motorcycle', 'brand', 50, 'https://www.carlogos.org/motorcycle-logos/fantic-logo.png');
SELECT public._seed_moto_node('veh_moto_br_talaria', 'Talaria', 'veh_motorcycle', 'brand', 51, 'https://www.carlogos.org/motorcycle-logos/talaria-logo.png');
SELECT public._seed_moto_node('veh_moto_br_mz', 'MZ', 'veh_motorcycle', 'brand', 52, 'https://www.carlogos.org/motorcycle-logos/mz-logo.png');
SELECT public._seed_moto_node('veh_moto_br_izh', 'IZH', 'veh_motorcycle', 'brand', 53, 'https://www.carlogos.org/motorcycle-logos/izh-logo.png');
SELECT public._seed_moto_node('veh_moto_br_bsa', 'BSA', 'veh_motorcycle', 'brand', 54, 'https://www.carlogos.org/motorcycle-logos/bsa-logo.png');
DROP FUNCTION public._seed_moto_node(TEXT, TEXT, TEXT, TEXT, INT, TEXT);
