import 'dart:math' as math;

/// Canonical Iraqi neighborhood/area centers for heat-map plotting and area_name.
class IraqNeighborhood {
  const IraqNeighborhood({
    required this.slug,
    required this.nameAr,
    required this.governorateSlug,
    required this.latitude,
    required this.longitude,
    this.displayOrder = 0,
  });

  final String slug;
  final String nameAr;
  final String governorateSlug;
  final double latitude;
  final double longitude;
  final int displayOrder;

  /// Localized label — non-Arabic uses a readable slug suffix until EN names exist.
  String displayName(String locale) {
    if (locale == 'ar') return nameAr;
    final parts = slug.split('_');
    final suffix = parts.length > 1 ? parts.sublist(1).join(' ') : slug;
    return suffix
        .split('_')
        .map((part) =>
            part.isEmpty ? part : '${part[0].toUpperCase()}${part.substring(1)}')
        .join(' ');
  }
}

/// Static neighborhood list — mirrors `public.listing_area_centers` seed data.
const iraqNeighborhoods = <IraqNeighborhood>[
  IraqNeighborhood(
    slug: 'baghdad_karrada',
    nameAr: 'الكرادة',
    governorateSlug: 'baghdad',
    latitude: 33.3152,
    longitude: 44.4560,
    displayOrder: 1,
  ),
  IraqNeighborhood(
    slug: 'baghdad_mansour',
    nameAr: 'المنصور',
    governorateSlug: 'baghdad',
    latitude: 33.3128,
    longitude: 44.3375,
    displayOrder: 2,
  ),
  IraqNeighborhood(
    slug: 'baghdad_jadriya',
    nameAr: 'الجادرية',
    governorateSlug: 'baghdad',
    latitude: 33.2778,
    longitude: 44.4000,
    displayOrder: 3,
  ),
  IraqNeighborhood(
    slug: 'baghdad_zayona',
    nameAr: 'زيونة',
    governorateSlug: 'baghdad',
    latitude: 33.3050,
    longitude: 44.4450,
    displayOrder: 4,
  ),
  IraqNeighborhood(
    slug: 'baghdad_dora',
    nameAr: 'الدورة',
    governorateSlug: 'baghdad',
    latitude: 33.2380,
    longitude: 44.3850,
    displayOrder: 5,
  ),
  IraqNeighborhood(
    slug: 'baghdad_kadhimiya',
    nameAr: 'الكاظمية',
    governorateSlug: 'baghdad',
    latitude: 33.3808,
    longitude: 44.3403,
    displayOrder: 6,
  ),
  IraqNeighborhood(
    slug: 'baghdad_adhamiya',
    nameAr: 'الأعظمية',
    governorateSlug: 'baghdad',
    latitude: 33.3614,
    longitude: 44.3842,
    displayOrder: 7,
  ),
  IraqNeighborhood(
    slug: 'baghdad_sadr_city',
    nameAr: 'مدينة الصدر',
    governorateSlug: 'baghdad',
    latitude: 33.3667,
    longitude: 44.4167,
    displayOrder: 8,
  ),
  IraqNeighborhood(
    slug: 'baghdad_shuala',
    nameAr: 'الشعلة',
    governorateSlug: 'baghdad',
    latitude: 33.3950,
    longitude: 44.3600,
    displayOrder: 9,
  ),
  IraqNeighborhood(
    slug: 'baghdad_hurriya',
    nameAr: 'الحرية',
    governorateSlug: 'baghdad',
    latitude: 33.3300,
    longitude: 44.4200,
    displayOrder: 10,
  ),
  IraqNeighborhood(
    slug: 'baghdad_ghazaliya',
    nameAr: 'الغزالية',
    governorateSlug: 'baghdad',
    latitude: 33.3150,
    longitude: 44.2800,
    displayOrder: 11,
  ),
  IraqNeighborhood(
    slug: 'baghdad_rusafa',
    nameAr: 'الرصافة',
    governorateSlug: 'baghdad',
    latitude: 33.3400,
    longitude: 44.4100,
    displayOrder: 12,
  ),
  IraqNeighborhood(
    slug: 'baghdad_karkh',
    nameAr: 'الكرخ',
    governorateSlug: 'baghdad',
    latitude: 33.3200,
    longitude: 44.3700,
    displayOrder: 13,
  ),
  IraqNeighborhood(
    slug: 'baghdad_bab_al_muadham',
    nameAr: 'باب المعظم',
    governorateSlug: 'baghdad',
    latitude: 33.3520,
    longitude: 44.3920,
    displayOrder: 14,
  ),
  IraqNeighborhood(
    slug: 'baghdad_amriya',
    nameAr: 'العامرية',
    governorateSlug: 'baghdad',
    latitude: 33.2680,
    longitude: 44.3180,
    displayOrder: 15,
  ),
  IraqNeighborhood(
    slug: 'baghdad_yarmouk',
    nameAr: 'اليرموك',
    governorateSlug: 'baghdad',
    latitude: 33.2980,
    longitude: 44.3580,
    displayOrder: 16,
  ),
  IraqNeighborhood(
    slug: 'baghdad_bayaa',
    nameAr: 'البياع',
    governorateSlug: 'baghdad',
    latitude: 33.2550,
    longitude: 44.3680,
    displayOrder: 17,
  ),
  IraqNeighborhood(
    slug: 'baghdad_shaab',
    nameAr: 'الشعب',
    governorateSlug: 'baghdad',
    latitude: 33.3780,
    longitude: 44.4320,
    displayOrder: 18,
  ),
  IraqNeighborhood(
    slug: 'basra_ashar',
    nameAr: 'العشار',
    governorateSlug: 'basra',
    latitude: 30.5085,
    longitude: 47.7804,
    displayOrder: 30,
  ),
  IraqNeighborhood(
    slug: 'basra_jumhuriya',
    nameAr: 'الجمهورية',
    governorateSlug: 'basra',
    latitude: 30.5250,
    longitude: 47.8150,
    displayOrder: 31,
  ),
  IraqNeighborhood(
    slug: 'basra_zubair',
    nameAr: 'الزبير',
    governorateSlug: 'basra',
    latitude: 30.3890,
    longitude: 47.7080,
    displayOrder: 32,
  ),
  IraqNeighborhood(
    slug: 'basra_tanuma',
    nameAr: 'التنومة',
    governorateSlug: 'basra',
    latitude: 30.5450,
    longitude: 47.8350,
    displayOrder: 33,
  ),
  IraqNeighborhood(
    slug: 'basra_maqal',
    nameAr: 'المعقل',
    governorateSlug: 'basra',
    latitude: 30.5450,
    longitude: 47.7900,
    displayOrder: 34,
  ),
  IraqNeighborhood(
    slug: 'basra_abu_al_khaseeb',
    nameAr: 'أبو الخصيب',
    governorateSlug: 'basra',
    latitude: 30.4200,
    longitude: 47.9200,
    displayOrder: 35,
  ),
  IraqNeighborhood(
    slug: 'basra_hartha',
    nameAr: 'الهارثة',
    governorateSlug: 'basra',
    latitude: 30.6300,
    longitude: 47.6900,
    displayOrder: 36,
  ),
  IraqNeighborhood(
    slug: 'basra_qurna',
    nameAr: 'القرنة',
    governorateSlug: 'basra',
    latitude: 31.0100,
    longitude: 47.4300,
    displayOrder: 37,
  ),
  IraqNeighborhood(
    slug: 'basra_fao',
    nameAr: 'الفاو',
    governorateSlug: 'basra',
    latitude: 29.9700,
    longitude: 48.4700,
    displayOrder: 38,
  ),
  IraqNeighborhood(
    slug: 'basra_hayyaniyah',
    nameAr: 'الحيانية',
    governorateSlug: 'basra',
    latitude: 30.5300,
    longitude: 47.7500,
    displayOrder: 39,
  ),
  IraqNeighborhood(
    slug: 'basra_andalus',
    nameAr: 'الأندلس',
    governorateSlug: 'basra',
    latitude: 30.4900,
    longitude: 47.7700,
    displayOrder: 40,
  ),
  IraqNeighborhood(
    slug: 'erbil_center',
    nameAr: 'مركز أربيل',
    governorateSlug: 'erbil',
    latitude: 36.1911,
    longitude: 44.0092,
    displayOrder: 41,
  ),
  IraqNeighborhood(
    slug: 'erbil_ankawa',
    nameAr: 'عنكاوا',
    governorateSlug: 'erbil',
    latitude: 36.2380,
    longitude: 44.0080,
    displayOrder: 42,
  ),
  IraqNeighborhood(
    slug: 'erbil_italian_village',
    nameAr: 'القرية الإيطالية',
    governorateSlug: 'erbil',
    latitude: 36.1750,
    longitude: 44.0450,
    displayOrder: 43,
  ),
  IraqNeighborhood(
    slug: 'erbil_dream_city',
    nameAr: 'دريم سيتي',
    governorateSlug: 'erbil',
    latitude: 36.1500,
    longitude: 43.9700,
    displayOrder: 44,
  ),
  IraqNeighborhood(
    slug: 'erbil_empire',
    nameAr: 'إمباير وورلد',
    governorateSlug: 'erbil',
    latitude: 36.1650,
    longitude: 44.0550,
    displayOrder: 45,
  ),
  IraqNeighborhood(
    slug: 'erbil_zanko',
    nameAr: 'زانكو (١٠٠ متري)',
    governorateSlug: 'erbil',
    latitude: 36.1850,
    longitude: 44.0200,
    displayOrder: 46,
  ),
  IraqNeighborhood(
    slug: 'erbil_shorsh',
    nameAr: 'شورش',
    governorateSlug: 'erbil',
    latitude: 36.1950,
    longitude: 43.9950,
    displayOrder: 47,
  ),
  IraqNeighborhood(
    slug: 'erbil_iskan',
    nameAr: 'اسكان',
    governorateSlug: 'erbil',
    latitude: 36.1700,
    longitude: 43.9850,
    displayOrder: 48,
  ),
  IraqNeighborhood(
    slug: 'erbil_bakhtiari',
    nameAr: 'بختياري',
    governorateSlug: 'erbil',
    latitude: 36.2000,
    longitude: 44.0300,
    displayOrder: 49,
  ),
  IraqNeighborhood(
    slug: 'nineveh_mosul_center',
    nameAr: 'مركز الموصل',
    governorateSlug: 'nineveh',
    latitude: 36.3450,
    longitude: 43.1450,
    displayOrder: 50,
  ),
  IraqNeighborhood(
    slug: 'nineveh_tel_afar',
    nameAr: 'تلعفر',
    governorateSlug: 'nineveh',
    latitude: 36.3790,
    longitude: 42.4470,
    displayOrder: 51,
  ),
  IraqNeighborhood(
    slug: 'nineveh_left_coast',
    nameAr: 'الساحل الأيسر',
    governorateSlug: 'nineveh',
    latitude: 36.3600,
    longitude: 43.1600,
    displayOrder: 52,
  ),
  IraqNeighborhood(
    slug: 'nineveh_maidan',
    nameAr: 'الميدان',
    governorateSlug: 'nineveh',
    latitude: 36.3350,
    longitude: 43.1300,
    displayOrder: 53,
  ),
  IraqNeighborhood(
    slug: 'nineveh_hamdaniya',
    nameAr: 'الحمدانية',
    governorateSlug: 'nineveh',
    latitude: 36.2500,
    longitude: 43.4700,
    displayOrder: 54,
  ),
  IraqNeighborhood(
    slug: 'nineveh_bashiqa',
    nameAr: 'بعشيقة',
    governorateSlug: 'nineveh',
    latitude: 36.4200,
    longitude: 43.4900,
    displayOrder: 55,
  ),
  IraqNeighborhood(
    slug: 'nineveh_sinjar',
    nameAr: 'سنجار',
    governorateSlug: 'nineveh',
    latitude: 36.3200,
    longitude: 41.8700,
    displayOrder: 56,
  ),
  IraqNeighborhood(
    slug: 'nineveh_qayyarah',
    nameAr: 'القيارة',
    governorateSlug: 'nineveh',
    latitude: 35.8200,
    longitude: 43.3100,
    displayOrder: 57,
  ),
  IraqNeighborhood(
    slug: 'najaf_center',
    nameAr: 'مركز النجف',
    governorateSlug: 'najaf',
    latitude: 32.0000,
    longitude: 44.3330,
    displayOrder: 60,
  ),
  IraqNeighborhood(
    slug: 'najaf_kufa',
    nameAr: 'الكوفة',
    governorateSlug: 'najaf',
    latitude: 32.0300,
    longitude: 44.4030,
    displayOrder: 61,
  ),
  IraqNeighborhood(
    slug: 'najaf_meshkhab',
    nameAr: 'المشخاب',
    governorateSlug: 'najaf',
    latitude: 31.7900,
    longitude: 44.4700,
    displayOrder: 62,
  ),
  IraqNeighborhood(
    slug: 'najaf_hurriya',
    nameAr: 'الحرية',
    governorateSlug: 'najaf',
    latitude: 32.0100,
    longitude: 44.3400,
    displayOrder: 63,
  ),
  IraqNeighborhood(
    slug: 'najaf_old_city',
    nameAr: 'المدينة القديمة',
    governorateSlug: 'najaf',
    latitude: 31.9950,
    longitude: 44.3200,
    displayOrder: 64,
  ),
  IraqNeighborhood(
    slug: 'karbala_center',
    nameAr: 'مركز كربلاء',
    governorateSlug: 'karbala',
    latitude: 32.6160,
    longitude: 44.0240,
    displayOrder: 70,
  ),
  IraqNeighborhood(
    slug: 'karbala_hindiya',
    nameAr: 'الهندية',
    governorateSlug: 'karbala',
    latitude: 32.7400,
    longitude: 44.2600,
    displayOrder: 71,
  ),
  IraqNeighborhood(
    slug: 'karbala_ain_tamur',
    nameAr: 'عين التمر',
    governorateSlug: 'karbala',
    latitude: 32.5700,
    longitude: 43.6800,
    displayOrder: 72,
  ),
  IraqNeighborhood(
    slug: 'karbala_husseiniya',
    nameAr: 'الحسينية',
    governorateSlug: 'karbala',
    latitude: 32.6300,
    longitude: 44.0500,
    displayOrder: 73,
  ),
  IraqNeighborhood(
    slug: 'karbala_bab_salalem',
    nameAr: 'باب السلالم',
    governorateSlug: 'karbala',
    latitude: 32.6100,
    longitude: 44.0350,
    displayOrder: 74,
  ),
  IraqNeighborhood(
    slug: 'sulaymaniyah_center',
    nameAr: 'مركز السليمانية',
    governorateSlug: 'sulaymaniyah',
    latitude: 35.5650,
    longitude: 45.4347,
    displayOrder: 90,
  ),
  IraqNeighborhood(
    slug: 'sulaymaniyah_bakrajo',
    nameAr: 'بكرجو',
    governorateSlug: 'sulaymaniyah',
    latitude: 35.5900,
    longitude: 45.3800,
    displayOrder: 91,
  ),
  IraqNeighborhood(
    slug: 'sulaymaniyah_sarchinar',
    nameAr: 'سه‌رچنار',
    governorateSlug: 'sulaymaniyah',
    latitude: 35.5450,
    longitude: 45.4550,
    displayOrder: 92,
  ),
  IraqNeighborhood(
    slug: 'sulaymaniyah_rania',
    nameAr: 'رانية',
    governorateSlug: 'sulaymaniyah',
    latitude: 36.2500,
    longitude: 44.8900,
    displayOrder: 93,
  ),
  IraqNeighborhood(
    slug: 'sulaymaniyah_chwarchra',
    nameAr: 'چوارچرا',
    governorateSlug: 'sulaymaniyah',
    latitude: 35.5550,
    longitude: 45.4200,
    displayOrder: 94,
  ),
  IraqNeighborhood(
    slug: 'sulaymaniyah_malik_mahmud',
    nameAr: 'ملك محمود',
    governorateSlug: 'sulaymaniyah',
    latitude: 35.5750,
    longitude: 45.4400,
    displayOrder: 95,
  ),
  IraqNeighborhood(
    slug: 'duhok_center',
    nameAr: 'مركز دهوك',
    governorateSlug: 'duhok',
    latitude: 36.8617,
    longitude: 42.9885,
    displayOrder: 110,
  ),
  IraqNeighborhood(
    slug: 'duhok_zakho',
    nameAr: 'زاخو',
    governorateSlug: 'duhok',
    latitude: 37.1440,
    longitude: 42.6820,
    displayOrder: 111,
  ),
  IraqNeighborhood(
    slug: 'duhok_simele',
    nameAr: 'سميل',
    governorateSlug: 'duhok',
    latitude: 36.9000,
    longitude: 42.8300,
    displayOrder: 112,
  ),
  IraqNeighborhood(
    slug: 'duhok_amedi',
    nameAr: 'العمادية',
    governorateSlug: 'duhok',
    latitude: 37.0930,
    longitude: 43.4890,
    displayOrder: 113,
  ),
  IraqNeighborhood(
    slug: 'duhok_akre',
    nameAr: 'عقرة',
    governorateSlug: 'duhok',
    latitude: 36.7440,
    longitude: 43.8900,
    displayOrder: 114,
  ),
  IraqNeighborhood(
    slug: 'kirkuk_center',
    nameAr: 'مركز كركوك',
    governorateSlug: 'kirkuk',
    latitude: 35.4681,
    longitude: 44.3922,
    displayOrder: 130,
  ),
  IraqNeighborhood(
    slug: 'kirkuk_rahimawa',
    nameAr: 'رحيماوة',
    governorateSlug: 'kirkuk',
    latitude: 35.4750,
    longitude: 44.4000,
    displayOrder: 131,
  ),
  IraqNeighborhood(
    slug: 'kirkuk_iskan',
    nameAr: 'اسكان',
    governorateSlug: 'kirkuk',
    latitude: 35.4600,
    longitude: 44.3700,
    displayOrder: 132,
  ),
  IraqNeighborhood(
    slug: 'kirkuk_shorja',
    nameAr: 'الشورجة',
    governorateSlug: 'kirkuk',
    latitude: 35.4550,
    longitude: 44.4100,
    displayOrder: 133,
  ),
  IraqNeighborhood(
    slug: 'kirkuk_dibs',
    nameAr: 'الدبس',
    governorateSlug: 'kirkuk',
    latitude: 35.5850,
    longitude: 44.0450,
    displayOrder: 134,
  ),
  IraqNeighborhood(
    slug: 'anbar_ramadi',
    nameAr: 'الرمادي',
    governorateSlug: 'anbar',
    latitude: 33.4200,
    longitude: 43.3000,
    displayOrder: 150,
  ),
  IraqNeighborhood(
    slug: 'anbar_fallujah',
    nameAr: 'الفلوجة',
    governorateSlug: 'anbar',
    latitude: 33.3489,
    longitude: 43.7840,
    displayOrder: 151,
  ),
  IraqNeighborhood(
    slug: 'anbar_qaim',
    nameAr: 'القائم',
    governorateSlug: 'anbar',
    latitude: 34.3700,
    longitude: 41.1500,
    displayOrder: 152,
  ),
  IraqNeighborhood(
    slug: 'anbar_haditha',
    nameAr: 'حديثة',
    governorateSlug: 'anbar',
    latitude: 34.1300,
    longitude: 42.3700,
    displayOrder: 153,
  ),
  IraqNeighborhood(
    slug: 'anbar_rutba',
    nameAr: 'الرطبة',
    governorateSlug: 'anbar',
    latitude: 33.0350,
    longitude: 40.2850,
    displayOrder: 154,
  ),
  IraqNeighborhood(
    slug: 'anbar_habbaniyah',
    nameAr: 'الحبانية',
    governorateSlug: 'anbar',
    latitude: 33.3700,
    longitude: 43.5600,
    displayOrder: 155,
  ),
  IraqNeighborhood(
    slug: 'babil_hillah',
    nameAr: 'الحلة',
    governorateSlug: 'babil',
    latitude: 32.4830,
    longitude: 44.4200,
    displayOrder: 170,
  ),
  IraqNeighborhood(
    slug: 'babil_musayyib',
    nameAr: 'المسيب',
    governorateSlug: 'babil',
    latitude: 32.7800,
    longitude: 44.2900,
    displayOrder: 171,
  ),
  IraqNeighborhood(
    slug: 'babil_hashimiyah',
    nameAr: 'الهاشمية',
    governorateSlug: 'babil',
    latitude: 32.4000,
    longitude: 44.6300,
    displayOrder: 172,
  ),
  IraqNeighborhood(
    slug: 'babil_mahawil',
    nameAr: 'المحاويل',
    governorateSlug: 'babil',
    latitude: 32.6100,
    longitude: 44.3300,
    displayOrder: 173,
  ),
  IraqNeighborhood(
    slug: 'babil_iskandariya',
    nameAr: 'الإسكندرية',
    governorateSlug: 'babil',
    latitude: 33.0000,
    longitude: 44.2900,
    displayOrder: 174,
  ),
  IraqNeighborhood(
    slug: 'diyala_baqubah',
    nameAr: 'بعقوبة',
    governorateSlug: 'diyala',
    latitude: 33.7460,
    longitude: 44.6420,
    displayOrder: 190,
  ),
  IraqNeighborhood(
    slug: 'diyala_khalis',
    nameAr: 'الخالص',
    governorateSlug: 'diyala',
    latitude: 33.8130,
    longitude: 44.5330,
    displayOrder: 191,
  ),
  IraqNeighborhood(
    slug: 'diyala_muqdadiyah',
    nameAr: 'المقدادية',
    governorateSlug: 'diyala',
    latitude: 33.9860,
    longitude: 44.9520,
    displayOrder: 192,
  ),
  IraqNeighborhood(
    slug: 'diyala_khanaqin',
    nameAr: 'خانقين',
    governorateSlug: 'diyala',
    latitude: 34.3450,
    longitude: 45.3850,
    displayOrder: 193,
  ),
  IraqNeighborhood(
    slug: 'diyala_balad_ruz',
    nameAr: 'بلدروز',
    governorateSlug: 'diyala',
    latitude: 33.7180,
    longitude: 44.9270,
    displayOrder: 194,
  ),
  IraqNeighborhood(
    slug: 'wasit_kut',
    nameAr: 'الكوت',
    governorateSlug: 'wasit',
    latitude: 32.5120,
    longitude: 45.8180,
    displayOrder: 210,
  ),
  IraqNeighborhood(
    slug: 'wasit_hai',
    nameAr: 'الحي',
    governorateSlug: 'wasit',
    latitude: 32.1660,
    longitude: 46.0280,
    displayOrder: 211,
  ),
  IraqNeighborhood(
    slug: 'wasit_suwaira',
    nameAr: 'الصويرة',
    governorateSlug: 'wasit',
    latitude: 32.9330,
    longitude: 44.9530,
    displayOrder: 212,
  ),
  IraqNeighborhood(
    slug: 'wasit_numaniyah',
    nameAr: 'النعمانية',
    governorateSlug: 'wasit',
    latitude: 32.6870,
    longitude: 45.2790,
    displayOrder: 213,
  ),
  IraqNeighborhood(
    slug: 'wasit_badra',
    nameAr: 'بدرة',
    governorateSlug: 'wasit',
    latitude: 33.1120,
    longitude: 45.9760,
    displayOrder: 214,
  ),
  IraqNeighborhood(
    slug: 'maysan_amarah',
    nameAr: 'العمارة',
    governorateSlug: 'maysan',
    latitude: 31.8350,
    longitude: 47.1450,
    displayOrder: 230,
  ),
  IraqNeighborhood(
    slug: 'maysan_majar_kabir',
    nameAr: 'المجر الكبير',
    governorateSlug: 'maysan',
    latitude: 31.6600,
    longitude: 47.1400,
    displayOrder: 231,
  ),
  IraqNeighborhood(
    slug: 'maysan_ali_gharbi',
    nameAr: 'علي الغربي',
    governorateSlug: 'maysan',
    latitude: 32.4570,
    longitude: 46.7040,
    displayOrder: 232,
  ),
  IraqNeighborhood(
    slug: 'maysan_qalat_salih',
    nameAr: 'قلعة صالح',
    governorateSlug: 'maysan',
    latitude: 31.8500,
    longitude: 47.0000,
    displayOrder: 233,
  ),
  IraqNeighborhood(
    slug: 'maysan_kahla',
    nameAr: 'الكحلاء',
    governorateSlug: 'maysan',
    latitude: 31.6120,
    longitude: 47.0400,
    displayOrder: 234,
  ),
  IraqNeighborhood(
    slug: 'dhi_qar_nasiriyah',
    nameAr: 'الناصرية',
    governorateSlug: 'dhi_qar',
    latitude: 31.0430,
    longitude: 46.2570,
    displayOrder: 250,
  ),
  IraqNeighborhood(
    slug: 'dhi_qar_shatra',
    nameAr: 'الشطرة',
    governorateSlug: 'dhi_qar',
    latitude: 31.4200,
    longitude: 46.1900,
    displayOrder: 251,
  ),
  IraqNeighborhood(
    slug: 'dhi_qar_rifai',
    nameAr: 'الرفاعي',
    governorateSlug: 'dhi_qar',
    latitude: 31.8090,
    longitude: 46.1150,
    displayOrder: 252,
  ),
  IraqNeighborhood(
    slug: 'dhi_qar_suq_shuyukh',
    nameAr: 'سوق الشيوخ',
    governorateSlug: 'dhi_qar',
    latitude: 30.8280,
    longitude: 46.4550,
    displayOrder: 253,
  ),
  IraqNeighborhood(
    slug: 'dhi_qar_chibayish',
    nameAr: 'الجبايش',
    governorateSlug: 'dhi_qar',
    latitude: 30.9070,
    longitude: 46.9020,
    displayOrder: 254,
  ),
  IraqNeighborhood(
    slug: 'muthanna_samawah',
    nameAr: 'السماوة',
    governorateSlug: 'muthanna',
    latitude: 31.3160,
    longitude: 45.2870,
    displayOrder: 270,
  ),
  IraqNeighborhood(
    slug: 'muthanna_rumaitha',
    nameAr: 'الرميثة',
    governorateSlug: 'muthanna',
    latitude: 31.5290,
    longitude: 45.1900,
    displayOrder: 271,
  ),
  IraqNeighborhood(
    slug: 'muthanna_khidr',
    nameAr: 'الخضر',
    governorateSlug: 'muthanna',
    latitude: 31.8020,
    longitude: 45.5710,
    displayOrder: 272,
  ),
  IraqNeighborhood(
    slug: 'muthanna_salman',
    nameAr: 'السلمان',
    governorateSlug: 'muthanna',
    latitude: 30.4880,
    longitude: 44.5310,
    displayOrder: 273,
  ),
  IraqNeighborhood(
    slug: 'qadisiyyah_diwaniyah',
    nameAr: 'الديوانية',
    governorateSlug: 'qadisiyyah',
    latitude: 31.9930,
    longitude: 44.9260,
    displayOrder: 290,
  ),
  IraqNeighborhood(
    slug: 'qadisiyyah_shamiya',
    nameAr: 'الشامية',
    governorateSlug: 'qadisiyyah',
    latitude: 31.8560,
    longitude: 44.6220,
    displayOrder: 291,
  ),
  IraqNeighborhood(
    slug: 'qadisiyyah_afaq',
    nameAr: 'عفك',
    governorateSlug: 'qadisiyyah',
    latitude: 32.0740,
    longitude: 45.2510,
    displayOrder: 292,
  ),
  IraqNeighborhood(
    slug: 'qadisiyyah_hamza',
    nameAr: 'الحمزة',
    governorateSlug: 'qadisiyyah',
    latitude: 31.6510,
    longitude: 44.9770,
    displayOrder: 293,
  ),
  IraqNeighborhood(
    slug: 'saladin_tikrit',
    nameAr: 'تكريت',
    governorateSlug: 'saladin',
    latitude: 34.6000,
    longitude: 43.6790,
    displayOrder: 310,
  ),
  IraqNeighborhood(
    slug: 'saladin_samarra',
    nameAr: 'سامراء',
    governorateSlug: 'saladin',
    latitude: 34.1970,
    longitude: 43.8890,
    displayOrder: 311,
  ),
  IraqNeighborhood(
    slug: 'saladin_baiji',
    nameAr: 'بيجي',
    governorateSlug: 'saladin',
    latitude: 34.9350,
    longitude: 43.4930,
    displayOrder: 312,
  ),
  IraqNeighborhood(
    slug: 'saladin_balad',
    nameAr: 'بلد',
    governorateSlug: 'saladin',
    latitude: 34.0170,
    longitude: 44.1450,
    displayOrder: 313,
  ),
  IraqNeighborhood(
    slug: 'saladin_dour',
    nameAr: 'الدور',
    governorateSlug: 'saladin',
    latitude: 34.4700,
    longitude: 43.7500,
    displayOrder: 314,
  ),
];

IraqNeighborhood? neighborhoodBySlug(String slug) {
  for (final area in iraqNeighborhoods) {
    if (area.slug == slug) return area;
  }
  return null;
}

IraqNeighborhood? neighborhoodByNameAr(String nameAr) {
  final trimmed = nameAr.trim();
  for (final area in iraqNeighborhoods) {
    if (area.nameAr == trimmed) return area;
  }
  return null;
}

List<IraqNeighborhood> neighborhoodsForGovernorate(String? governorateSlug) {
  if (governorateSlug == null || governorateSlug.trim().isEmpty) {
    return iraqNeighborhoods;
  }
  return iraqNeighborhoods
      .where((area) => area.governorateSlug == governorateSlug)
      .toList();
}

/// Nearest neighborhood by squared Euclidean distance on lat/lng (same as SQL backfill).
IraqNeighborhood? nearestNeighborhood({
  required double latitude,
  required double longitude,
  String? governorateSlug,
}) {
  final candidates = neighborhoodsForGovernorate(governorateSlug);
  if (candidates.isEmpty) return null;

  IraqNeighborhood? best;
  var bestDistance = double.infinity;

  for (final area in candidates) {
    final distance = math.pow(latitude - area.latitude, 2) +
        math.pow(longitude - area.longitude, 2);
    if (distance < bestDistance) {
      bestDistance = distance.toDouble();
      best = area;
    }
  }

  return best;
}

/// Baghdad map default center (midpoint of major Baghdad neighborhoods).
const baghdadMapCenterLat = 33.3152;
const baghdadMapCenterLng = 44.4000;
